### ISSUE TITLE
Asset directory per metadata file not working

### ISSUE THREAD

**Issue by rfgamaral** [Kometa-Team/Kometa#1014]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

I have my Movies library configured like this:

```yaml
libraries:
  Movies:
    metadata_path:
      - file: config/metadata/Movies/collections.yml
        asset_directory: config/assets/Movies/Collections
      - file: config/metadata/Movies/posters.yml
        asset_directory: config/assets/Movies/Posters
    operations:
      delete_unmanaged_collections: false
```

And I also have these configuration options:

```yaml
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
```

Now, when I run PMM, I expect that collection posters to be saved in `config/assets/Movies/Collections`, and movie posters to be saved in `config/assets/Movies/Posters`. But as you can see from the logs, that's not the case, only the collections metadata is saving posters in the correct folder, the posters metadata is saving them in the default `config/assets`.

Am I doing something wrong, or is this a bug?

### Logs

https://gist.github.com/rfgamaral/1f969094d11aa48ed043f37edc5e5bc9

**Comment by rfgamaral** [comment]
I found a workaround to achieve what I was looking for, like this:

```yml
libraries:
  Movies:
    metadata_path:
      - file: config/metadata/Movies/metadata.yml
      - file: config/metadata/Movies/collections.yml
        asset_directory: config/assets/Movies/Collections
    settings:
      asset_directory: config/assets/Movies/Metadata # acts as the "default" for `Movies` library
```

But I still think that we should be able to overwrite the `asset_directory` for `each metadata_path`. It's working for the `collections.yml` one (i.e. `collections:`), but not for the `metadata.yml` (i.e. `metadata:`).
