### ISSUE TITLE
Plex_search: Genre: seems to be erroring out

### ISSUE THREAD

**Issue by SerinitySW** [Kometa-Team/Kometa#105]
Using 1.4.0, the `genre:` builder seems to not be working - spitting out `Unknown Error: Unknown filter category: genre`. Snippet from logs here: https://pastebin.com/yuwPmLnd

Config:

```
    Adventure:
        plex_search:
            genre: 
                - Adventure
                - Action/Adventure
        trakt_list:
            - https://trakt.tv/users/retrogran/lists/adventure-movies?sort=title,asc
            - https://trakt.tv/users/niklcc/lists/action-adventure-movies
```

Also doesn't work with only one genre:

`genre: Adventure`
