### ISSUE TITLE
[Bug]: Overlays say successfully applied but no change occurs in Plex

### ISSUE THREAD

**Issue by MYanello** [Kometa-Team/Kometa#1079]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

Meta.log shows overlays applied, but when viewing in Plex, the artwork remains the same.
This was discussed in [discord ](https://discordapp.com/channels/822460010649878528/1026193148290015332) but no resolution was found. The 'Overlay' label gets applied to the movie. Searching through unselected posters it does not appear. I was able to get PMM to create a collection so this issue is just with the overlays. 

Things I've tried:
Switching to nightly
Docker and bare linux
Different overlays

### Relevant Collection/Overlay/Playlist Definition

```yml
## This file is a template remove the .template to use the file

libraries:                                      # This is called out once within the config.yml file                                       
  Movies:                                       # Each library must match the Plex library name
    # metadata_path:
    # - file: config/Movies.yml                   # This is a local file on the system
#    - folder: /Movies/                    # This is a local directory on the system
#    - git: PMM/chart/basic                      # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
#    - git: PMM/chart/imdb                       # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
    overlay_path:
#    - remove_overlays: false                    # Set this to true to remove all overlays
    - file: config/Overlays.yml                 # This is a local file on the system
    - git: PMM/overlays/resolution            # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
    - git: PMM/overlays/audio_codec
#  TV Shows:                           
#    metadata_path:
#      - file: config/TVShows.yml
#      - folder: /TV Shows/
#      - git: PMM/chart/basic                    # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
#      - git: PMM/chart/imdb                     # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
#    overlay_path:
#      - remove_overlays: false                  # Set this to true to remove all overlays
#     - file: config/Overlays.yml               # This is a local file on the system
#      - git: PMM/overlays/imdb_top_250          # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
#  Music:
#    metadata_path:
#      - file: config/Music.yml
#playlist_files:
#- file: config/playlists.yml
#- git: PMM/playlist                             # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
webhooks:                                       # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
plex:                                           # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://plex.yanello.net
  token: *****
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                                           # REQUIRED for the script to run
  apikey: ****
  language: en
  cache_expiration: 60
  region:
# tautulli:                                       # Can be individually specified per library as well
#   url: http://tautulli.yanello.net
#   apikey: ****
# omdb:
#   apikey: ****
#   cache_expiration: 60
# radarr:                                         # Can be individually specified per library as well
#   url: http://radarr.yanello.net
#   token: ****
#   add_missing: false
#   add_existing: false
#   root_folder_path: S:/Movies
#   monitor: true
#   availability: announced
#   quality_profile: HD-1080p
#   tag:
#   search: false
#   radarr_path:
#   plex_path:
#   upgrade_existing: false
sonarr:                                         # Can be individually specified per library as well
  url: http://sonarr.yanello.net
  token: ****
  add_missing: false
  add_existing: false
  root_folder_path: S:/TV Shows
  monitor: all
  quality_profile: HD-1080p
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
  upgrade_existing: false
  # everything below is autofilled by the script
#    access_token:
#    token_type:
#    expires_in:
#    refresh_token:
#    scope: public
#    created_at:
mal:
  client_id: ################################
  client_secret: ################################################################
  authorization:
    # everything below is autofilled by the script
    access_token:
    token_type:
    expires_in:
    refresh_token:
```

### Logs

https://gist.github.com/MYanello/bc18c4583c44bbf8b5853bd8a89fabc7
