### ISSUE TITLE
[Bug]: metadata backup file must exist in advance

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#1095]
### Version Number

Version: 1.17.3-develop93

### What branch are you on?

nightly

### Describe the Bug

I enabled metadata backup as a test, using the default path:
```
libraries:
  Movies:
...
    operations:
      metadata_backup:
        sync_tags: true
        add_blank_entries: true
```
The run failed with:
```
[CRITICAL] | Config Error: no path attribute found and the default path /config/Movies_Metadata_Backup.yml could not be found
```

On the command line I then did:
```
touch config/Movies_Metadata_Backup.yml
```
and restarted the run, which is continuing without error.

I would have expected PMM to create the export file rather than complaining it isn't present.

### Logs

https://gist.github.com/chazlarson/5f4dd610efe92150066cad7c0ddadbf9
