### ISSUE TITLE
[Bug]: addind to radarr failing for a collection

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#1108]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

everything works OK, but for one collection (didn't see any other), while adding movies to radarr it fails.
it does add some, but stop during the process

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  Studio:
    schedule: weekly(wednesday)
    optional:
      - company
    tmdb_company: <<company>>
    sort_title: +2_<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
    url_poster: <<poster>>
collections:
  Walt Disney:
    template: {name: Studio, company: "6125, 1, 2, 3475, 13571, 3166, 15935, 112779, 171657, 670, 3202, 20193, 111619, 135745", poster: https://theposterdb.com/api/assets/81861}
    summary: Walt Disney Animation Studios (WDAS), sometimes shortened to Disney Animation, is an American animation studio that creates animated features and short films for The Walt Disney Company. Founded on October 16, 1923 by brothers Walt Disney and Roy O. Disney, it is one of the oldest-running animation studios in the world. It is currently organized as a division of Walt Disney Studios and is headquartered at the Roy E. Disney Animation Building at the Walt Disney Studios lot in Burbank, California.
```

### Logs

https://gist.github.com/Nexius2/17b8885fef0844bdc2fb52020f0af4d7
