### ISSUE TITLE
[Docs]: Docker Swarm

### ISSUE THREAD

**Issue by corbin-lounsbury** [Kometa-Team/Kometa#1111]
### What is the improvement or update to the Wiki you wish to see?

Hi, 

I wanted to contribute to the documentation my findings for those that want to make use of Docker Swarm. 

Here's generally the code I used to get it to work:

```
version: "3"
services:
  plex-meta-manager:
    image: meisnate12/plex-meta-manager
    container_name: meta-manager
    environment:
      - PUID=1000 # optional
      - PGID=1000 # optional
      - TZ=America/New_York # optional, useful if trying to correlate log timestamps with your timezone
    volumes:
      - <path to local config folder>:/config # required 
      - <path to media>:/media # optional if your media resides in a different folder
    restart: unless-stopped
```

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/home/guides/docker.html
