### ISSUE TITLE
[Bug]: sync_to_trakt_list stopped working

### ISSUE THREAD

**Issue by benfishbus** [Kometa-Team/Kometa#1119]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

I was using this feature successfully to sync existing Plex collections to Trakt lists. Suddenly it doesn't work. It gives me an error every time of the sort:  `Trakt Error: List shows-needsubs is empty`

I have tried using different builders, but the problem isn't the builder - those are working fine as you can see in the log. The sync to Trakt is just failing. Why is it objecting to an empty list?

I have tried with both private and public Trakt lists. Also, PMM's Trakt connection is working ok.

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
  SubtitlesNeeded:
    sonarr_taglist: subs
    sync_to_trakt_list: shows-needsubs
```

### Logs

https://gist.github.com/benfishbus/33509aede4e6765261791b306399c291
