### ISSUE TITLE
[Feature]: Use current_year in a plex_search collection

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#1143]
### Is your feature request related to a problem? Please elaborate.

I have about 6 different collections, scattered throughout 6 different files, and they check for media released in the last 5 years.

example
```
collections:
  "Collection1":
    plex_search:
      any:
        year.gt: 2017
```

So every year I have to remember to update each of those files.

### Describe the solution you'd like

I noticed on [this page](https://metamanager.wiki/en/latest/metadata/dynamic.html#number) there was a way to do that math using a `current_year` variable.

It would be nice if we could do something similar with the `plex_search`, so I could write something like this and not have to update the collections each year:
```
collections:
  "Collection1":
    plex_search:
      any:
        year.gt: current_year-5
```
