### ISSUE TITLE
[Bug]: Official Trakt Lists Not Valid

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#1159]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

It appears that PMM does not support official Trakt lists, I am thinking this is because the list does not contain a username as is standard with user lists.

Example link: https://trakt.tv/lists/official/one-piece-collection?sort=rank,asc

Error Extract: Trakt Error: No valid Trakt Lists in ['https://trakt.tv/lists/official/one-piece-collection']

Discord Thread: https://discord.com/channels/822460010649878528/1038521086838587463

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  playlist:
    default:
      libraries: Movies, TV Shows, Anime Shows, Anime Movies
    sync_mode: sync
    libraries: <<libraries>>
    url_poster: https://raw.githubusercontent.com/Frazzer951/Plex-Meta-Manager-Images/master/playlist/<<playlist_name_encoded>>.jpg

  One Piece (Timeline Order):
    template:
      - name: playlist
    trakt_list: https://trakt.tv/lists/official/one-piece-collection
    libraries: Anime Movies
    radarr_add_missing: true
```

### Logs

https://discord.com/channels/822460010649878528/1038521086838587463
