### ISSUE TITLE
[Bug]: `mdb_tomatoesaudience` or `rt_popcorn` not working correctly?

### ISSUE THREAD

**Issue by KnifeFed** [Kometa-Team/Kometa#1160]
### Version Number

1.17.3

### What branch are you on?

master

### Describe the Bug

With this config, I get this poster:

<img src="https://user-images.githubusercontent.com/85502276/200183334-696329f9-cabb-4255-ad1b-4b687a01c27a.png" width="666">

As you can see on [Rotten Tomatoes](https://www.rottentomatoes.com/m/21_jump_street_2011) and [mdblist](https://mdblist.com/movie/tt1232829), the audience score is incorrect and it looks like it's actually getting the IMDb score.

(also, `horizontal_position: right` isn't working but it seems that may be fixed in https://github.com/meisnate12/Plex-Meta-Manager-Configs/pull/502... although it happens on both images for me.)

### Relevant Collection/Overlay/Playlist Definition

```yml
- git: PMM/overlays/ratings
  template_variables:
    rating1: critic
    rating2: audience
    rating1_image: rt_tomato
    rating2_image: rt_popcorn
    horizontal_position: right
    vertical_position: bottom
    rating_alignment: horizontal
  operations:
    mass_critic_rating_update: mdb_tomatoes
    mass_audience_rating_update: mdb_tomatoesaudience
```

### Logs

No error in logs

**Comment by chrislentz** [comment]
This is not a bug. The reason you are seeing the ratings shift towards the left is because there are 3 slots at the bottom, but you are not using the third one (far right). If you update your config to use 2 & 3 instead of 1 & 2, you should be good to go.

I tested found no issues with right alignment.

```
- git: PMM/overlays/ratings
  template_variables:
    rating2: critic
    rating3: audience
    rating2_image: rt_tomato
    rating3_image: rt_popcorn
    horizontal_position: right
    vertical_position: bottom
    rating_alignment: horizontal
```
