### ISSUE TITLE
Regression in content_rating_mapper to map rating to none

### ISSUE THREAD

**Issue by burkasaurusrex** [Kometa-Team/Kometa#1174]
### Version Number

1.18.0 

### What branch are you on?

master

### Describe the Bug

`content_rating_mapper` appears to work except for when I map a rating to an empty rating. For the movies where it should be removed, there is an extra log line that says `No Content Rating Found`. I should note that I've tried it with and without double quotes around the mapped rating.

### Relevant Collection/Overlay/Playlist Definition

```yml
operations:
      content_rating_mapper:
        "TV-G": G
        "TV-PG": PG
        "TV-14": PG-13
        "TV-MA": R
        Approved: PG
        Passed: PG
        NR: 
        "Not Rated": 
        Unrated:
```

### Logs

https://gist.github.com/burkasaurusrex/0754a8e6f69fd2119beedfe4b38ae6da
