### ISSUE TITLE
[Anilist] free variable 'default' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by Tawagot0** [Kometa-Team/Kometa#118]
Hello! When i set a collection with `AniList Seasonal Anime` (https://github.com/meisnate12/Plex-Meta-Manager/wiki/AniList-Builders#anilist-seasonal-anime)  like this: 

```yml
collections:
  Fall 2020:
    anilist_season:
      season: fall
      year: 2020
    sync_mode: sync
```

Logs:
```
| Scanning Fall 2020 Collection                                                                   |
| Collection Warning: anilist_season sort_by attribute not found using score as default              |
| free variable 'default' referenced before assignment in enclosing scope                            |
```

But it works very well with studios for example.
