### ISSUE TITLE
Resolution & Edition Overlapping Each Other

### ISSUE THREAD

**Issue by Celeggur** [Kometa-Team/Kometa#1189]
### Version Number

1.18.0 

### What branch are you on?

master

### Describe the Bug

When using the Resolution overlay and moving the position to the bottom of the poster it is causing any edition detail to be placed in the same place as the resolution image. 

<img width="1209" alt="Capture" src="https://user-images.githubusercontent.com/66747212/202870825-a4ea1217-dfcf-4a40-b946-170d441782d1.PNG">

### Relevant Collection/Overlay/Playlist Definition

```yml
overlay_path:
    - pmm: resolution
      template_variables:
        horizontal_offset: 15
        horizontal_align: left
        vertical_offset: 15
        vertical_align: bottom
```

### Logs

https://gist.github.com/Celeggur/93a0b2b2a8edfdeee8047b4310f2b2f2
