### ISSUE TITLE
[Feature Request] New Poster Attributes

### ISSUE THREAD

**Issue by Tawagot0** [Kometa-Team/Kometa#119]
If you use `popular` or filter by rate, popular or other criteria, can pick in local the poster of the first result like this:
```py
data[0].poster
```

For example:
```yml
collections:
  Most Popular Movies (30 Days):
    sync_mode: sync
    tautulli_popular:
      list_days: 30
      list_size: 10
```
Maybe for other API like Anilist:

- anilist_popular

TMDB and other:
- tmdb_popular
- tmdb_top_rated

An option to get the first popular movie and set her poster.
