### ISSUE TITLE
[Defaults]: Show status not following templates_variables position

### ISSUE THREAD

**Issue by alejakun** [Kometa-Team/Kometa#1197]
### Link to File

No file to report

### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

While configuring the overlay show status indicating a different location from default, fails to take the new settings. My configuration is as follows (based on Default's configuration example):

```
    - pmm: status                                   # Airing, Returning, Ended, Canceled and works with overlay_level show
      templates_variables:
        horizontal_offset: 15
        horizontal_align: left
        vertical_offset: 30
        vertical_align: bottom
```

While specifying the location of the status overlay it keeps the same location as default configuration.

Note: This position is exactly the default for Video Format, this is not an accident, the overlya for Video Format has been commented and status overlay is expected to be located in this location.
