### ISSUE TITLE
tvdb_list stopped working

### ISSUE THREAD

**Issue by Nexius2** [Kometa-Team/Kometa#1205]
### Version Number

1.18

### What branch are you on?

master

### Describe the Bug

since recently (tvdb page has change and it might explain) tvdb_list is not gathering tvdb ids.

### Relevant Collection/Overlay/Playlist Definition

```yml
tvdb_list: https://thetvdb.com/lists/indiana-jones
returns:
TVDb Error: No TVDb IDs found at {tvdb_url}
```

### Logs

https://gist.github.com/Nexius2/ba5c61fae1f7dc02f2f1a23832edbe65
