### ISSUE TITLE
Playlist not finding movies

### ISSUE THREAD

**Issue by cjohnk** [Kometa-Team/Kometa#1225]
### Version Number

1.18.0

### What branch are you on?

master

### Describe the Bug

Playlist returns error "Plex Error: No Items found in Plex" when playlist contains more than one library and one or more of the libraries does not return a result.

Details and screenshots here:

https://discord.com/channels/822460010649878528/1052263825044422777

### Relevant Collection/Overlay/Playlist Definition

```yml
playlists:
  To Watch:
    libraries: Movies, Kids Movies
    summary: New and Unwatched Movies
    plex_search:
      all:
        added: 10
        unplayed: true
```

### Logs

https://gist.github.com/cjohnk/9d20da0515745329c634f5bf01d004d0
