### ISSUE TITLE
Sonarr v3 Error regarding LanguageId

### ISSUE THREAD

**Issue by Procuria** [Kometa-Team/Kometa#1249]
### Version Number

Version: 1.18.1 (Docker)

### What branch are you on?

nightly

### Describe the Bug

Sonarr Version: 3.0.9.1549

When running the "Sonarr part" of my TV-library I hit  the following error:

`Sonarr Error: (500 [Internal Server Error]) {'message': 'Unexpected character encountered while parsing value: [. Path \'[0].languageProfileId\', line 1, position 1576. (Json snippet \'anguageProfileId": [<--error-->1], "seasonFolder": \')', 'description': 'Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: [. Path \'[0].languageProfileId\', line 1, position 1576. (Json snippet \'anguageProfileId": [<--error-->1], "seasonFolder": \') `

It seems that the languageID isn't parsed correctly.

I run the latest nightly docker image - build today [29.12] via _not modified_ Dockerfile.

### Relevant Collection/Overlay/Playlist Definition

```yml
sonarr:                          
      url: https://redacted.for.privacy/sonarr
      token: redacted.for.privacy
      add_missing: true
      add_existing: false
      root_folder_path: /home/media/tv
      monitor: all
      quality_profile: Series High Quality
      language_profile: English
      series_type: standard
      season_folder: true
      tag: pmm
      search: true
      cutoff_search: false
      sonarr_path:
      plex_path:
```

### Logs

https://gist.github.com/Procuria/4e508853fbae7f9bebbc2d07da5cdd65#file-sonarr_error_log-md
