### ISSUE TITLE
Critical error validating delete_not_scheduled

### ISSUE THREAD

**Issue by burkasaurusrex** [Kometa-Team/Kometa#1258]
### Version Number

1.18.2

### What branch are you on?

master

### Describe the Bug

This is a bit of a weird one. Relevant log lines are 4477 through 4539 and 5761 through 5772. This would be the first run where this collection should be deleted. It does delete the collection but has a critical error validating it is deleted. I don't seem to have issues with other `delete_not_scheduled` collections. I haven't been able to isolate if it's one of the following attributes of this collection causing the error: emoji in title, smart collection, `visible_home`, `visible_shared`, schedule list, list with commas. I'll try and do a bit more investigation as well.

As always, thanks for the great work! This is an amazing project

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
    Scheduled Year-end Smart Filter:
        smart_filter:
            any:
                collection: <<collection_filter>>
        delete_not_scheduled: true
        visible_library: false
        visible_home: true
        visible_shared: true
collections:
    "Rotten Tomatoes 🍅: Top 50 Movies of 2022":
        trakt_list: https://trakt.tv/users/lish408/lists/rotten-tomatoes-best-of-2022?sort=rank,asc
        summary: The top 100 movies released in 2022 according to Rotten Tomatoes (updated every week)
        limit: 50
        radarr_add_missing: true
        item_radarr_tag: PMM-Awards-RTTop50of2022
        collection_order: custom
    "Rotten Tomatoes 🍅 - Top 50 Movies of 2022":
        schedule: yearly(12/29), yearly(1/1), yearly(1/4), yearly(1/7), yearly(1/10), yearly(1/13), yearly(1/16), yearly(1/19), yearly(1/22), yearly(1/25), yearly(1/28), yearly(1/31), yearly(2/3), yearly(2/6)
        template: {name: Scheduled Year-end Smart Filter, collection_filter: "Rotten Tomatoes 🍅: Top 50 Movies of 2022"}
```

### Logs

https://gist.github.com/burkasaurusrex/6f8750956dd4a7fc1b5a92254dba3280
