### ISSUE TITLE
Anidb Api Limits on Mass Genre/Rating Update

### ISSUE THREAD

**Issue by Mezuror** [Kometa-Team/Kometa#1264]
### Version Number

1.18.2 

### What branch are you on?

master

### Describe the Bug

It appears that anidb starts returning errors after 269 shows have had genre and ratings updated. It has failed to find info at the 270th show every time I have tried running it, with and without using login and api app. It makes updating genres and user ratings impossible since it restarts alphabetically every time.

### Relevant Collection/Overlay/Playlist Definition

```yml
Anime:
    report_path: config/Anime/Anime_report.yml
    metadata_path:
    - file: config/Anime/Anime.yml
    - file: config/Anime/AnimeSeasons.yml
    - file: config/Anime/Anime_collections.yml
    overlay_path:
    - pmm: ratings                                  # Ratings with custom fonts>
      template_variables:
        rating1: critic
        rating1_image: anidb
        rating2: audience
        rating2_image: mal
        rating3: user
        rating3_image: tmdb
        horizontal_position: left
    settings:
      asset_directory: config/assets/anime
    operations:
      mass_user_rating_update: anidb_average         # Update user ratings with mdb_tomatoes
      mass_critic_rating_update: anidb_rating               # Update critic ratings with imdb
      mass_audience_rating_update: mal             # Update audience ratings with tmdb
      mass_genre_update: anidb                       # Update all genres from tmdb
      mass_content_rating_update: mal   # Changes Content Rating to "1", "2" etc. to specify appropriate age
      mass_originally_available_update: anidb        # Update all original available date from tmdb
```

### Logs

https://gist.github.com/Mezuror/3f1d090981aaec6fc98dc05e1c430247
