### ISSUE TITLE
Special Characters cause asset search to fail

### ISSUE THREAD

**Issue by JNR8** [Kometa-Team/Kometa#1279]
### Version Number

1.18.3

### What branch are you on?

master

### Describe the Bug

When placing a poster in the assets folder for TMDB Collections to grab during processing the script fails back to using the URL poster instead of the file poster.  It seems that the Collection folder cannot be found because Collection Name (and therefore the collection folder in the Asset folder) contains a special character.  

For example: 
  Mission: Impossible Collection
  Family Guy Trilogy Collection: Laugh It Up, Fuzzball!

This problem does not present itself for Collections that do not contain special characters.  

### Relevant Collection/Overlay/Playlist Definition

```yml
dynamic_collections:
  TMDb Collections:          # This name is the mapping name
    type: tmdb_collection
```

### Logs

https://gist.github.com/jennec/501566a515eb8c0799cd6abcc891c389
