### ISSUE TITLE
Ratings overlays are not cached

### ISSUE THREAD

**Issue by jacauc** [Kometa-Team/Kometa#1306]
### Version Number

1.18.3

### What branch are you on?

master

### Describe the Bug

Every time I run overlays each move is looked up and processed again. This takes forever, it does not seem like the cache is consulted at all.

![image](https://user-images.githubusercontent.com/18201320/217243291-aa61ab34-f62c-437b-a0f5-cc412aa90c44.png)

```
      - pmm: ratings
        template_variables:
          rating1: user                                                    # 4 as this is user and mass_user_rating_update: mdb_tomatoes
          rating1_image: rt_tomato                                         # 4 as this is user and mass_user_rating_update: mdb_tomatoes
          rating1_font: config/custom-fonts/Adlib.ttf                      # 4 local font accessible to PMM
          rating1_font_size: 63                                            # 4 adjusted font size to fit rating

          rating2: critic                                                  # 5 as this is critic and mass_critic_rating_update: imdb
          rating2_image: imdb                                              # 5 as this is critic and mass_critic_rating_update: imdb
          rating2_font: config/custom-fonts/Impact.ttf                     # 5 local font accessible to PMM
          rating2_font_size: 70                                            # 5 adjusted font size to fit rating

          horizontal_position: right                                       # the set of ratings is on the right of the poster
    operations:
      mass_user_rating_update: mdb_tomatoes                              # 4 This operation will update the user rating in plex with Rotten Tomatoes ratings information gathered through mdblist.com (mdblist config required)
      mass_critic_rating_update: imdb                                    # 5 This operation will update the critic rating in plex with IMDb ratings information
      mass_audience_rating_update: tmdb                                  # 6 This operation will update the audience rating in plex with TMDb ratings information 
          
```

**Comment by YozoraXCII** [comment]
Your screenshot is for the mass_x_rating_update but your description is for Overlays?

For context, each time you run PMM the mass_ operations will re-run. It will check each item in your library against the desired site and then update where necessary (i.e. The River Wild is fetching a 5.7 user rating from mdb_tomatoes).

Overlays work the same - every item is processed so that PMM can determine what needs to change and what stays unchanged.

We have been doing a lot of work to make Overlays and Mass Operations more reliable in the nightly branch, so you're welcome to try switching branch and see if whatever issue you are seeing is replicated there or not.

**Comment by jacauc** [comment]
> Your screenshot is for the mass_x_rating_update but your description is for Overlays?

Oh that makes sense! I wasn't aware that is related to the mass update. I commented the mass updates now. Is there any way to consult the cache for this and the overlays and maybe only process items that have expired cache lifetime?

> We have been doing a lot of work to make Overlays and Mass Operations more reliable in the nightly branch, so you're welcome to try switching branch and see if whatever issue you are seeing is replicated there or not.

I'm currently using the `lscr.io/linuxserver/plex-meta-manager` image on my unraid server. What is the tag I should use for the nightly branch?

**Comment by YozoraXCII** [comment]
> > Your screenshot is for the mass_x_rating_update but your description is for Overlays?
> 
> Oh that makes sense! I wasn't aware that is related to the mass update. I commented the mass updates now. Is there any way to consult the cache for this and the overlays and maybe only process items that have expired cache lifetime?
> 
> > We have been doing a lot of work to make Overlays and Mass Operations more reliable in the nightly branch, so you're welcome to try switching branch and see if whatever issue you are seeing is replicated there or not.
> 
> I'm currently using the `lscr.io/linuxserver/plex-meta-manager` image on my unraid server. What is the tag I should use for the nightly branch?

The Linuxserver.io image [linuxserver/plex-meta-manager] Is different to the official image [meisnate12/plex-meta-manager] in a few ways that cause problems.

The LSIO image only has latest, no develop or nightly. If you want to switch to develop or nightly to try a new feature, you can't with LSIO image.

It keeps the PMM files in a different place inside the image compared to official, so when you exec into it you can't just run PMM, you need to cd into another dir first.

It also resets ownership of the entire config dir every run. In tests, the ownership of the config dir and its contents was set to 911:911 with each run. The official image runs as root by default, and will set the ownership of the files it creates during that run to root if you don't specify a user, but lsio appears to reset the entire config tree rather than just a log file or two with every run.

Generally speaking, we suggest you use the official image instead of lsio.

**Comment by jacauc** [comment]
Good to know...

Based on the below screenshot, would I just be able to substitute the official image in the repository field and submit, or are there other variables I'd need to set?

**Comment by jacauc** [comment]
![image](https://user-images.githubusercontent.com/18201320/220130222-f9c4337f-77c7-4615-97e4-2a6ce0c2c0f3.png)

**Comment by YozoraXCII** [comment]
I don't use that OS myself, but I imagine you just swap Repository to `meisnate12/plex-meta-manager`, or `meisnate12/plex-meta-manager:nightly` if you wnt to use the nightly branch.

**Comment by chazlarson** [comment]
The official image won't use PGID, PUID, or UMASK, but having them there won't cause issues.  The other vars you have there are PMM-specific, so they'll continue to work.

**Comment by jacauc** [comment]
Thanks I'll run it like that for a while and see how it works. No visible difference in timing or otherwise since switching to nightly

**Comment by meisnate12** [comment]
@jacauc I would recommended to just use the official unraid pmm template from the start vs editing the linuxserver template

**Comment by jacauc** [comment]
I have two dockers - one for overlays another for metadata. They have the following configurations:

metadata config.yml:
```
libraries:                                                                           
  Movies:                                       
    metadata_path:
    - pmm: imdb
    - pmm: tmdb
    - file: config/MoviesYAML/Charts.yml
    - file: config/MoviesYAML/Holidays.yml
    - file: config/MoviesYAML/Genre.yml

    settings:
      missing_path: config/missing
      asset_directory: config/assets
    operations:
      assets_for_all: false
      split_duplicates: false
      delete_unmanaged_collections: true
      delete_collections:
        configured: false
        managed: true


  TV Shows:
    metadata_path:
    - file: config/TVYAML/Charts.yml
    - file: config/MoviesYAML/Genre.yml 


    settings:
      missing_path: config/missing
      asset_directory: config/assets
    operations:
      assets_for_all: false
      split_duplicates: false
      delete_unmanaged_collections: true
      delete_collections:
        configured: false
        managed: true
```

metadata charts.yml

```

templates:
  Suggestion:
    url_poster: https://theposterdb.com/api/assets/<<poster>>
    sort_title: ++++++++++_<<collection_name>>
    collection_mode: hide
    collection_order: release.desc
    sync_mode: sync
  Tautulli:
    url_poster: https://theposterdb.com/api/assets/<<poster>>
    sort_title: ++++++++++_<<collection_name>>
    collection_mode: hide
    collection_order: release.desc
    sync_mode: sync
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    url_poster: <<poster>>
    smart_label: release.desc
  Best of:
    trakt_list: https://trakt.tv/users/lish408/lists/rotten-tomatoes-best-of-<<year>>
    sort_title: +1_Best of <<year>>
    sync_mode: sync
    summary: Rotten Tomatoes Best Movies of <<year>>
    url_poster: <<poster>>
    smart_label: release.desc


collections:


  Oscars:
    template: { name: Chart, num: 6, poster: https://theposterdb.com/api/assets/244711 }
    imdb_list: https://www.imdb.com/search/title/?title_type=feature,documentary&groups=oscar_winner&sort=release_date,desc
    sort_title: ++++++++++++++++++_Oscars
    summary: Oscar Winning Movies
    smart_label: release.desc   
    
    
  Cannes Film Festival:
    template: { name: Chart, num: 7, poster: https://i0.wp.com/1.bp.blogspot.com/-_XAF61BRJo4/T7yIsuwAi0I/AAAAAAACUW8/tmgIu2wCGVc/s1600/cannes%2Blogo%2Band%2Bimage.jpg?resize=699%2C493&ssl=1 }
    imdb_list: https://www.imdb.com/list/ls560268601/?sort=date_added,desc&st_dt=&mode=detail&page=1&release_date=2018%2C&ref_=ttls_ref_yr
    sort_title: ++++++++++++++++++_Cannes
    summary: Cannes Festival Winners
    smart_label: release.desc   


  Sundance Film Festival:
    trakt_list: 
     - https://trakt.tv/users/pjcob/lists/2023-sundance
     - https://trakt.tv/users/pjcob/lists/2022-sundance
     - https://trakt.tv/users/pjcob/lists/2021-sundance
     - https://trakt.tv/users/pjcob/lists/2020-sundance
     - https://trakt.tv/users/pjcob/lists/2019-sundance

    sync_mode: sync
    smart_label: release.desc  
    sort_title: ++++++++++++++++++_Sundance Collection
    summary: Sundance Film Festival Movie Guide
    url_poster: https://store.sundance.org/site/images/2022%20Limited%20Edition%20Poster_Main-1.jpg
    url_background: https://i.imgur.com/goapGVl.jpg  

  Best of 2022:
    template: { name: Best of, year: 2022, poster: https://theposterdb.com/api/assets/199947}
  Best of 2023:
    template: { name: Best of, year: 2023, poster: https://theposterdb.com/api/assets/232601 }
 
  Plex Watched:
    template: { name: Chart, num: 1, poster: https://theposterdb.com/api/assets/136359 }
    tautulli_watched:
      list_days: 30
      list_size: 20
      list_buffer: 20
    summary: Movies Watched by all users on Plex
    
```
  
metadata genre.yml

```
templates:
  Genre:
    plex_search:
      genre: <<genre>>
    url_poster: <<poster>>
    sort_title: +3_<<collection_name>>
#    collection_order: release.desc
  IMDb Genre:
    default:
      title: feature
      limit: 100
    imdb_list:
      - url: https://www.imdb.com/search/title/?title_type=<<title>>&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>
        limit: <<limit>>
      - url: https://www.imdb.com/search/title/?title_type=<<title>>&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>&sort=user_rating,desc
        limit: <<limit>>
    sort_title: +3_<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
    url_poster: <<poster>>
  Other Genre:
    sort_title: +3_<<collection_name>>
    sync_mode: sync
    smart_label: release.desc
    url_poster: <<poster>>
  Trakt:
    sort_title: +3_<<collection_name>>
    trakt_list_details: <<list>>
    url_poster: <<poster>>
    sync_mode: sync
#    collection_order: release.desc

collections:

  Action:
    template: {name: Genre, genre: Action, poster: https://theposterdb.com/api/assets/52018}
    summary: Action film is a genre wherein physical action takes precedence in the storytelling. The film will often have continuous motion and action including physical stunts, chases, fights, battles, and races. The story usually revolves around a hero that has a goal, but is facing incredible odds to obtain it.
  Adventure:
    template: {name: Genre, genre: Adventure, poster: https://theposterdb.com/api/assets/52218}
    summary: Adventure film is a genre that revolves around the conquests and explorations of a protagonist. The purpose of the conquest can be to retrieve a person or treasure, but often the main focus is simply the pursuit of the unknown. These films generally take place in exotic locations and play on historical myths. Adventure films incorporate suspenseful puzzles and intricate obstacles that the protagonist must overcome in order to achieve the end goal.
  Animation:
    template: {name: Genre, genre: Animation, poster: https://theposterdb.com/api/assets/120090}
    summary: Animated film is a collection of illustrations that are photographed frame-by-frame and then played in a quick succession. Since its inception, animation has had a creative and imaginative tendency. Being able to bring animals and objects to life, this genre has catered towards fairy tales and children’s stories. However, animation has long been a genre enjoyed by all ages. As of recent, there has even been an influx of animation geared towards adults. Animation is commonly thought of as a technique, thus it’s ability to span over many different genres.
  Anime:
    template: {name: Genre, genre: Anime, poster: https://theposterdb.com/api/assets/126743}
    summary: A collection of Anime movies
  Biography:
    template: {name: Genre, genre: Biography, poster: https://theposterdb.com/api/assets/60369}
    summary: A collection of Biography movies
  Bond Films:
    template: {name: Other Genre}
    trakt_list:
     - https://trakt.tv/users/istoit/lists/james-bond-films
    smart_label: release_date.desc
    sync_mode: sync
    sort_title: +3_Bond Films
    summary: James Bond Film Collection
    url_poster: https://theposterdb.com/api/assets/102136
  
  Comedy:
    template: {name: Genre, genre: Comedy, poster: https://theposterdb.com/api/assets/51397}
    summary: Comedy is a genre of film that uses humor as a driving force. The aim of a comedy film is to illicit laughter from the audience through entertaining stories and characters. Although the comedy film may take on some serious material, most have a happy ending. Comedy film has the tendency to become a hybrid sub-genre because humor can be incorporated into many other genres. Comedies are more likely than other films to fall back on the success and popularity of an individual star.
  Crime:
    template: {name: Genre, genre: Crime, poster: https://theposterdb.com/api/assets/53057}
    summary: Crime film is a genre that revolves around the action of a criminal mastermind. A Crime film will often revolve around the criminal himself, chronicling his rise and fall. Some Crime films will have a storyline that follows the criminal's victim, yet others follow the person in pursuit of the criminal. This genre tends to be fast paced with an air of mystery – this mystery can come from the plot or from the characters themselves.
  Documentary:
    template: {name: Genre, genre: Documentary, poster: https://theposterdb.com/api/assets/51430}
    summary: Documentary film is a non-fiction genre intended to document reality primarily for the purposes of instruction, education, or maintaining a historical record.
  Drama:
    template: {name: Genre, genre: Drama, poster: https://theposterdb.com/api/assets/52016}
    summary: Drama film is a genre that relies on the emotional and relational development of realistic characters. While Drama film relies heavily on this kind of development, dramatic themes play a large role in the plot as well. Often, these dramatic themes are taken from intense, real life issues. Whether heroes or heroines are facing a conflict from the outside or a conflict within themselves, Drama film aims to tell an honest story of human struggles.
  Family:
    template: {name: Genre, genre: Family, poster: https://theposterdb.com/api/assets/53059}
    summary: Fantasy film is a genre that incorporates imaginative and fantastic themes. These themes usually involve magic, supernatural events, or fantasy worlds. Although it is its own distinct genre, these films can overlap into the horror and science fiction genres. Unlike science fiction, a fantasy film does not need to be rooted in fact. This element allows the audience to be transported into a new and unique world. Often, these films center on an ordinary hero in an extraordinary situation.
  Fantasy:
    template: {name: Genre, genre: Animation, poster: https://theposterdb.com/api/assets/51476}
    imdb_list:
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=fantasy
      limit: 100
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=fantasy&sort=user_rating,desc
      limit: 100
    summary: Fantasy film is a genre that incorporates imaginative and fantastic themes. These themes usually involve magic, supernatural events, or fantasy worlds. Although it is its own distinct genre, these films can overlap into the horror and science fiction genres. Unlike science fiction, a fantasy film does not need to be rooted in fact. This element allows the audience to be transported into a new and unique world. Often, these films center on an ordinary hero in an extraordinary situation.
  Gangster:
    template: {name: Other Genre, poster: https://theposterdb.com/api/assets/62561}
    imdb_list:
      - https://www.imdb.com/list/ls026270180/
      - https://www.imdb.com/list/ls000093502/
    summary: Gangster film is a sub-genre of crime films that center on organized crime or the mafia. Often the plot revolves around the rise and fall of an organized crime leader. Many Gangster films explore the destructive nature of organized crime, while others attempt to show the humanity of the individual characters.

  History:
    template: {name: Genre, genre: History, poster: https://theposterdb.com/api/assets/58022}
    summary: History film is a genre that takes historical events and people and interprets them in a larger scale. Historical accuracy is not the main focus, but rather the telling of a grandiose story. The drama of an History film is often accentuated by a sweeping musical score, lavish costumes, and high production value.
  Horror:
    template: {name: Genre, genre: Horror, poster: https://theposterdb.com/api/assets/51475}
    summary: Horror film is a genre that aims to create a sense of fear, panic, alarm, and dread for the audience. These films are often unsettling and rely on scaring the audience through a portrayal of their worst fears and nightmares. Horror films usually center on the arrival of an evil force, person, or event. Many Horror films include mythical creatures such as ghosts, vampires, and zombies. Traditionally, Horror films incorporate a large amount of violence and gore into the plot. Though it has its own style, Horror film often overlaps into Fantasy, Thriller, and Science-Fiction genres.
  Martial Arts:
    template: {name: Other Genre, poster: https://theposterdb.com/api/assets/51773}
    imdb_list:
      - https://www.imdb.com/list/ls000099643/
      - https://www.imdb.com/list/ls068611186/
      - https://www.imdb.com/list/ls068378513/
      - https://www.imdb.com/list/ls090404120/
    summary: Martial Arts film is a sub-genre of action films that feature numerous martial arts combat between characters. These combats are usually the films' primary appeal and entertainment value, and often are a method of storytelling and character expression and development. Martial Arts are frequently featured in training scenes and other sequences in addition to fights. Martial Arts films commonly include other types of action, such as hand-to-hand combat, stuntwork, chases, and gunfights.
  Mindfuck:
    trakt_list:
     - https://trakt.tv/users/hdlists/lists/mindfuck-movies
     - https://trakt.tv/users/benfranklin/lists/best-mindfucks
     - https://trakt.tv/users/lish408/lists/mindfuck
    smart_label: critic_rating.desc
    sync_mode: sync
    sort_title: +3_Mindfuck Movies
    summary: There’s nothing greater than a film that makes you think. A film that lingers on your mind long after the credits have rolled and is the subject of many conversation and discussion. Trying to piece together the puzzle of what you saw and coming to a conclusion that makes sense or still doesn’t add up.
    url_poster: https://theposterdb.com/api/assets/204495
#    url_background: https://i.imgur.com/DM1Im1X.jpeg
  Music:
    template: {name: Other Genre, poster: https://theposterdb.com/api/assets/51398}
    imdb_list:
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=music
      limit: 200
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=music&sort=user_rating,desc
      limit: 200
    summary: Music film is genre that revolves around music being an integral part of the characters lives.
  Musical:
    template: {name: Genre, genre: Musical, poster: https://theposterdb.com/api/assets/51427}
    summary: A Musical interweaves vocal and dance performances into the narrative of the film. The songs of a film can either be used to further the story or simply enhance the experience of the audience. These films are often done on a grand scale and incorporate lavish costumes and sets. Traditional musicals center on a well-known star, famous for their dancing or singing skills (i.e. Fred Astaire, Gene Kelly, Judy Garland). These films explore concepts such are love and success, allowing the audience to escape from reality.
  Mystery:
    template: {name: Genre, genre: Mystery, poster: https://theposterdb.com/api/assets/53060}
    summary: A Mystery film centers on a person of authority, usually a detective, that is trying to solve a mysterious crime. The main protagonist uses clues, investigation, and logical reasoning. The biggest element in these films is a sense of “whodunit” suspense, usually created through visual cues and unusual plot twists.

  Pandemic:
    template: {name: Other Genre, poster: https://theposterdb.com/api/assets/55837}
    imdb_list:
      - url: https://www.imdb.com/search/keyword/?keywords=deadly-virus%2Chealth-crisis%2Cpandemic%2Cpublic-health-epidemic%2Cvirus%2Ccoronavirus&sort=moviemeter,asc&mode=detail&page=1&ref_=kw_ref_key
        limit: 1000
      - url: https://www.imdb.com/list/ls041901506/
      - url: https://www.imdb.com/list/ls092321048/
    summary: A Pandemic film resolves around widespread viruses, plagues, and diseases.
  Romance:
    template: {name: Genre, genre: Romance, poster: https://theposterdb.com/api/assets/53062}
    summary: "Romance film can be defined as a genre wherein the plot revolves around the love between two protagonists. This genre usually has a theme that explores an issue within love, including but not limited to: love at first sight, forbidden love, love triangles, and sacrificial love. The tone of Romance film can vary greatly. Whether the end is happy or tragic, Romance film aims to evoke strong emotions in the audience."
  Science Fiction:
    template: {name: Genre, genre: Science Fiction, poster: https://theposterdb.com/api/assets/51772}
    summary: Science Fiction (Sci-Fi) film is a genre that incorporates hypothetical, science-based themes into the plot of the film. Often, this genre incorporates futuristic elements and technologies to explore social, political, and philosophical issues. The film itself is usually set in the future, either on earth or in space. Traditionally, a Science Fiction film will incorporate heroes, villains, unexplored locations, fantastical quests, and advanced technology.
  Short:
    template: {name: Genre, genre: Short, poster: https://theposterdb.com/api/assets/53063}
    summary: A collection of Short movies
  Sports:
    template: {name: Genre, genre: Sport, poster: https://theposterdb.com/api/assets/60371}
    imdb_list:
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=sport
      limit: 200
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=sport&sort=user_rating,desc
      limit: 200
    summary: A Sport Film revolves around a sport setting, event, or an athlete. Often, these films will center on a single sporting event that carries significant importance. Sports films traditionally have a simple plot that builds up to the significant sporting event. This genre is known for incorporating film techniques to build anticipation and intensity. Sport films have a large range of sub-genres, from comedies to dramas, and are more likely than other genres to be based true-life events.
  Stand Up Comedy:
    template: {name: Trakt, list: https://trakt.tv/users/giladg/lists/stand-up-comedy, poster: https://theposterdb.com/api/assets/74610}
    summary: Stand-up comedy is a comedic style in which a comedian performs in front of a live audience, speaking directly to them through a microphone. Comedians give the illusion that they are dialoguing, but in actuality, they are monologuing a grouping of humorous stories, jokes and one-liners, typically called a shtick, routine, act, or set. Some stand-up comedians use props, music or magic tricks to enhance their acts. Stand-up comedians perform quasi-autobiographical and fictionalized extensions of their offstage selves.
#  Submarine:
#    template: {name: Other Genre, poster: https://theposterdb.com/api/assets/89095}
#    imdb_list: https://www.imdb.com/search/keyword/?keywords=submarine-movie&ref_=fn_al_kw_1
#    summary: Collection of movies based around or about Submarines.
  Sword & Sorcery:
    template: {name: Other Genre, poster: https://theposterdb.com/api/assets/74604}
    imdb_list: https://www.imdb.com/list/ls022909805
    summary: Sword and Sorcery film is a sub-genre of Fantasy that tend to be more plot-driven. These films rely on heavy action and battle scenes. Common themes in Sword and Sorcery films include a rescue mission, saving a princess, and battling a fantastical monster. The worlds and characters in these films are often much less developed than in other fantasy sub-genres. Of all the Fantasy sub-genres, Sword and Sorcery is most likely to be geared towards a younger audience, as many of these films are animated.
  Thriller:
    template: {name: Genre, genre: Thriller, poster: https://theposterdb.com/api/assets/52019}
    summary: Thriller Film is a genre that revolves around anticipation and suspense. The aim for Thrillers is to keep the audience alert and on the edge of their seats. The protagonist in these films is set against a problem – an escape, a mission, or a mystery. No matter what sub-genre a Thriller film falls into, it will emphasize the danger that the protagonist faces. The tension with the main problem is built on throughout the film and leads to a highly stressful climax.
  War:
    template: {name: Genre, genre: War, poster: https://theposterdb.com/api/assets/51477}
    summary: War Film is a genre that looks at the reality of war on a grand scale. They often focus on landmark battles as well as political issues within war. This genre usually focuses on a main character and his team of support, giving the audience an inside look into the gritty reality of war.
  Western:
    template: {name: Genre, genre: Western, poster: https://theposterdb.com/api/assets/51774}
    summary: "Western Film is a genre that revolves around stories primarily set in the late 19th century in the American Old West. Most Westerns are set between the American Civil War (1865) and the early 1900s. Common themes within Western Film include: the conquest of the wild west, the cultural separation of the East and the West, the West’s resistance to modern change, the conflict between Cowboys and Indians, outlaws, and treasure/gold hunting. American Western Film usually revolves around a stoic hero and emphasizes the importance of honor and sacrifice."

```

metadata holidays.yml

```

templates:
    Holiday:
        sort_title: 9+++++++_<<collection_name>>
        url_poster: <<poster>>
        collection_order: release.desc
        collection_mode: hide
        delete_not_scheduled: false
        run_again: true
        visible_home: true
        visible_shared: true
        sync_mode: sync

collections:
  Christmas: #IMDB lists have been removed as they have all been merged into christmas-static-list
    template: {name: Holiday, holiday: "Christmas", poster: https://theposterdb.com/api/assets/212635}
    visible_home: range(12/01-12/31)
    visible_shared: range(12/01-12/31)
   #schedule: range(12/01-12/31)
    sort_title: 9+++++++_Christmas
    trakt_list:
      - https://trakt.tv/users/jjjonesjr33/lists/christmas
      - https://trakt.tv/users/jjjonesjr33/lists/christmas-static-list
    summary: This collection revolves around the plot involving Christmas.
  Halloween:
    template: {name: Holiday, holiday: "Halloween", poster: https://theposterdb.com/api/assets/212637}
    visible_home: range(10/01-10/31)
    visible_shared: range(10/01-10/31)
    #schedule: range(10/01-10/31)
    sort_title: 9+++++++_Halloween
    trakt_list:
      - https://trakt.tv/users/jjjonesjr33/lists/halloween
    summary: This collection revolves around the plot involving Halloween.
  New Year's Eve Movies:
    template: {name: Holiday, holiday: "New Year's Eve", poster: https://i.imgur.com/YCYXhAX.png}
    visible_home: range(12/26-01/05)
    visible_shared: range(12/26-01/05)
    #schedule: range(12/26-01/05)
    sort_title: 9+++++++_New Year
    imdb_list: 
      - https://www.imdb.com/list/ls066838460/
    summary: This collection revolves around the plot involving New Year's Eve.
  Valentine's Day Movies:
    template: {name: Holiday, holiday: "Valentine's Day", poster: https://theposterdb.com/api/assets/212641}
    visible_home: range(02/01-02/14)
    visible_shared: range(02/01-02/14)
    #schedule: range(02/01-02/14)
    sort_title: 9+++++++_Valentine
    imdb_list:
      - https://www.imdb.com/list/ls000094398/
      - https://www.imdb.com/list/ls057783436/
      - https://www.imdb.com/list/ls064427905/
    summary: This collection revolves around the plot involving Valentine's Day.
  St. Patrick's Day Movies:
    template: {name: Holiday, holiday: "St. Patrick's Day", poster: https://theposterdb.com/api/assets/240644}
    visible_home: range(03/01-03/17)
    visible_shared: range(03/01-03/17)
    #schedule: range(03/01-03/17)
    sort_title: 9+++++++_St Patrick
    imdb_list:
      - https://www.imdb.com/list/ls063934595/
    summary: This collection revolves around the plot involving St. Patrick's Day.
  Easter Movies:
    template: {name: Holiday, holiday: Easter, poster: https://theposterdb.com/api/assets/212636}
    visible_home: range(3/22-4/25)
    visible_shared: range(3/22-4/25)
    #schedule: range(3/22-4/25)
    sort_title: 9+++++++_Easter
    imdb_list: 
      - https://www.imdb.com/list/ls062665509/
      - https://www.imdb.com/list/ls051733651/
    summary: This collection revolves around the plot involving Easter.

```


overlays config:
```
libraries:                                      # This is called out once within the config.yml file                                       
  Movies:                                       # Each library must match the Plex library naome
    overlay_path:
      #- remove_overlays: true                        # Set to true if you want to remove overlays
      #- reapply_overlay: true                        # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays
      #- reset_overlays: tmdb                          # if you want to reset the poster to default poster from tmdb
          
  
      - pmm: ribbon            # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
      - pmm: resolution
      - pmm: oscars
      - pmm: streaming
        template_variables:
          horizontal_align: right
          vertical_align: top
          vertical_offset: 15
      - pmm: ratings
        template_variables:
          rating1: user                                                    # 4 as this is user and mass_user_rating_update: mdb_tomatoes
          rating1_image: rt_tomato                                         # 4 as this is user and mass_user_rating_update: mdb_tomatoes
          rating1_font: config/custom-fonts/Adlib.ttf                      # 4 local font accessible to PMM
          rating1_font_size: 63                                            # 4 adjusted font size to fit rating

          rating2: critic                                                  # 5 as this is critic and mass_critic_rating_update: imdb
          rating2_image: imdb                                              # 5 as this is critic and mass_critic_rating_update: imdb
          rating2_font: config/custom-fonts/Impact.ttf                     # 5 local font accessible to PMM
          rating2_font_size: 70                                            # 5 adjusted font size to fit rating

          horizontal_position: right                                       # the set of ratings is on the right of the poster
    operations:
     # mass_user_rating_update: mdb_tomatoes                              # 4 This operation will update the user rating in plex with Rotten Tomatoes ratings information gathered through mdblist.com (mdblist config required)
     # mass_critic_rating_update: imdb                                    # 5 This operation will update the critic rating in plex with IMDb ratings information
     # mass_audience_rating_update: tmdb                                  # 6 This operation will update the audience rating in plex with TMDb ratings information 
          
          
  

  TV Shows:
    overlay_path:
      #- remove_overlays: true                        # Set to true if you want to remove overlays
      #- reapply_overlay: true                        # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays
      #- reset_overlays: plex                          # if you want to reset the poster to default poster from tmdb
      
      - pmm: ribbon          # This is a file within the https://github.com/meisnate12/Plex-Meta-Manager-Configs Repository
      - pmm: resolution
     # - pmm: episode_info
      - pmm: streaming
        template_variables:
          horizontal_align: right
          vertical_align: top
      - pmm: ratings
        template_variables:
          rating1: critic
          rating1_image: imdb
          rating1_font: config/custom-fonts/Impact.ttf
          rating1_font_size: 70

          rating2: audience
          rating2_image: rt_popcorn
          rating2_font: config/custom-fonts/Adlib.ttf
          rating2_font_size: 63

          rating3: user
          rating3_image: tmdb
          rating3_font: config/custom-fonts/Avenir_95_Black.ttf
          rating3_font_size: 70

          horizontal_position: right                                       # the set of ratings is on the right of the poster
    operations:
      #mass_user_rating_update: mdb_tomatoes                              # 4 This operation will update the user rating in plex with Rotten Tomatoes ratings information gathered through mdblist.com (mdblist config required)
      #mass_critic_rating_update: imdb                                    # 5 This operation will update the critic rating in plex with IMDb ratings information
      #mass_audience_rating_update: tmdb                                  # 6 This operation will update the audience rating in plex with TMDb ratings information 

```

**Comment by jacauc** [comment]
I found that the collections, when sorting by release.desc has to be re-sorted during every run and it takes forever to sort, so I stopped sorting them

**Comment by chazlarson** [comment]
Are those two separate configs with different names?  If so they have independent cache files, so the one isn't going to reference the cache built by the other:

```
> cp test-config.yml A-config.yml
> cp test-config.yml B-config.yml
> docker run ... -c /config/A-config.yml --run
... time passes ...
> docker run ... -c /config/B-config.yml --run
... same amount of time passes ...
> ls *.cache
A-config.cache  B-config.cache  test-config.cache
```

**Comment by jacauc** [comment]
the one is for overlays and the other for metadata - didn't imagine there would be a lot of cache shared by them? Either way, once the cache is built after first run, does it really matter?

![image](https://user-images.githubusercontent.com/18201320/220698414-fd3100d3-ed63-4ab7-9063-ceb631a88c76.png)
![image](https://user-images.githubusercontent.com/18201320/220698482-688276c3-6e5b-4722-8c6f-a016ec4aa98a.png)

**Comment by chazlarson** [comment]
Perhaps I misunderstood the issue; "does not seem like the cache is consulted at all" combined with the two configs seemed to me like you wanted the one config to consult the cache generated by the other config.

**Comment by jacauc** [comment]
No, I'm more referring to subsequent runs. I'd imagine that the first run is slow to build a cache and thereafter runs should heavily rely on cache and be blazing fast to complete.
Alternatively, if there was a flag to only process content newer than say 2 days old on every daily run. This would only process the deltas and not start processing the library every single time. 
In my experience, the cache doesn't make a tremendous difference between first run and subsequent runs

**Comment by diblaze** [comment]
This is still quite slow. I have 762 movies, and it takes about 1 hours to finish mass updating. 

Is there anyway to speed this up? Ideally I only want to do this to recently added media, and for media where results were not found.

So media that was updated once, is not re-run again.

```yaml
operations:
      split_duplicates: false
      assets_for_all: true
      delete_collections:
        configured: false
        managed: false
        less: 99999
      mass_user_rating_update: mdb_tomatoes
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      mass_genre_update:
        - tmdb
        - imdb
        - tvdb
      mass_content_rating_update:
        - mdb_commonsense # Changes Content Rating to "1", "2" etc. to specify appropriate age
        - omdb # Changes Content Rating from omdb if not found on mdb_commonsense
      mass_studio_update:
        - tmdb # Update all studios from tmdb
      mass_originally_available_update:
        - tmdb # Update all original available date from tmdb
        - tvdb # Update all original available date from tvdb if not from tmdb
        - omdb # Update all original available date from omdb(imdb) if not from tvdb
      mass_imdb_parental_labels: none # Apply all Parental Labels with a value of None, Mild, Moderate, or Severe to match IMDb parental guide
      ```
