### ISSUE TITLE
item_assets slow search

### ISSUE THREAD

**Issue by ikwtif** [Kometa-Team/Kometa#1327]
### Version Number

1.18.3

### What branch are you on?

master

### Describe the Bug

See thread on discord:
https://discord.com/channels/822460010649878528/1079511593064349747

While creating a collection in pmm, pmm tries to update details of the items in the collection. I have 2 asset folders on in my config (depth 2), but I have no assets for the actual movies in the collection. Finding the poster for the collection, which I have, is no problem. But `Asset Warning: unable to find asset folder `is taking at least 10 seconds for each movie. 

### Relevant Collection/Overlay/Playlist Definition

```yml
######################################################
#              COLLECTIONS                           #
######################################################
templates:
  Chart:
    sort_title: 0<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
    collection_mode: hide               # hides in library
    visible_home: true                  # shows on home screen
    
  Collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    # item_assets: true
    collection_order: release
    delete_below_minimum: true
    
collections:
  IMDb Top 250 Movies:
    imdb_chart: top_movies
    collection_order: custom
    sync_mode: sync
    sort_title: 01-Top Movies
    visible_library: false
    collection_mode: hide               # hides in library

  Recently Released Movies:
    sort_title: 00-Recently Released
    smart_filter:
      all:
        release: 90
    summary: Released Movies in the last 90 Days
    collection_mode: hide
    visible_home: true                  # shows on home screen
    
  # ATMOS+DV:
   # plex_all: true
    # filters:
      # - has_dolby_vision: true
        # audio_track_title.regex: (?i)\batmos(\b|\d)
      # - has_dolby_vision: true
        # filepath.regex: (?i)\batmos(\b|\d)
  # Atmos:
    # sort_title: 00-Atmos
    # smart_filter:
      # all:
        # audio_codec: 
        # - dolby_atmos
        # - truehd_atmos
        # - plus_atmos
    # summary: Dolby Atmos
    # collection_mode: hide
    # visible_home: true                  # shows on home screen
  
  Trending Movies:
    template: { name: Chart, num: 2 }
    tmdb_trending_daily: 30
    tmdb_trending_weekly: 30
    sync_mode: sync
    summary: Trending Movies
    
  Popular Movies:
    template: { name: Chart, num: 3 }
    tmdb_popular: 40
    imdb_list:
      url: https://www.imdb.com/search/title/?title_type=feature,documentary,short
      limit: 40
    summary: Popular Movies Across The Internet
    radarr_add_missing: true
    radarr_tag: pmm - Popular

  DCU:
    template:
      name: Collection
    imdb_list: https://www.imdb.com/list/ls047446610/
  MCU:
    template:
      name: Collection
    imdb_list: https://www.imdb.com/list/ls066946827/
  MCU - Chronological:
    template:
      name: Collection
    imdb_list: https://www.imdb.com/list/ls021001839/


  Top 10 Pirated Movies:
    template: { name: Chart, num: 4 }
    # sort_title: 01-Top Movies
    trakt_list: https://trakt.tv/users/linaspurinis/lists/top-10-pirated-movies-of-the-week?sort=rank,asc
    sync_mode: sync

  Top 10 Watched Movies Of The Week:
    template: { name: Chart, num: 5 }
    trakt_list: https://trakt.tv/users/linaspurinis/lists/top-watched-movies-of-the-week?sort=rank,asc
    sync_mode: sync
    limit: 30

# dynamic_collections:
  # TMDb Collections:
    # type: tmdb_collection
    # remove_suffix: "Collection"
```

### Logs

https://gist.github.com/ikwtif/a06da7bd2d92fc1e0e59203931985617
