### ISSUE TITLE
plex_meta_manager.py hangs forever processing Netflix collection

### ISSUE THREAD

**Issue by tunerooster** [Kometa-Team/Kometa#1359]
### Version Number

Version: 1.18.3-nightly158 (Python 3.11.2) (Git: nightly) 

### What branch are you on?

nightly

### Describe the Bug

```
plex_meta_manager.py -rl 'TV Shows'
```
The above hangs forever processing Netflix Collection.

The log shows:
```
|=============================== Missing Shows from Library: Netflix ================================|
|                                                                                                    |
| Netflix Collection | ? | Hemlock Grove (TVDb: 259948)                                              |
| Netflix Collection | ? | The Get Down (TVDb: 300886)                                               |
| Netflix Collection | ? | Marvel's Luke Cage (TVDb: 304219)                                         |
| Netflix Collection | ? | A Series of Unfortunate Events (TVDb: 306304)                             |
| Netflix Collection | ? | Iron Fist (TVDb: 317953)                                                  |
| Netflix Collection | ? | 13 Reasons Why (TVDb: 323168)                                             |
| Netflix Collection | ? | Free Rein (TVDb: 329015)                                                  |
| Netflix Collection | ? | Gypsy (TVDb: 328292)                                                      |
| Netflix Collection | ? | Greenhouse Academy (TVDb: 334366)                                         |
| Netflix Collection | ? | Marvel's The Punisher (TVDb: 331980)                                      |
| Netflix Collection | ? | Seven Seconds (TVDb: 339602)                                              |
| Netflix Collection | ? | Lost in Space (2018) (TVDb: 343253)                      
...
...
...
| Netflix Collection | ? | The Pentaverate (TVDb: 404510)                                            |
| Netflix Collection | ? | Vampire in the Garden (TVDb: 387060)                                      |
| Netflix Collection | ? | The Boss Baby: Back in the Crib (TVDb: 419298)                            |
| Netflix Collection | ? | Sea of Love (TVDb: 419964)                                                |
| Netflix Collection | ? | My Little Pony: Make Your Mark (TVDb: 416741)                             |
| Netflix Collection | ? | The Sound of Magic (TVDb: 394389)                                         |
| Netflix Collection | ? | Welcome to Eden (TVDb: 393110)                                            |
| Netflix Collection | ? | 42 Days of Darkness (TVDb: 418730)                                        |
| Netflix Collection | ? | The Life and Movies of ErÅ
```
It hangs forever with the last line in STDOUT being:
```
| Netflix Collection | ? | The Life and Movies of ErÅ
```
I wonder if it has something to do with the special character "Å"?

Here is the relevant log file:
~/Plex-Meta-Manager/config/logs/TV Shows/collections/Netflix/collection.log
[collection.log](https://github.com/meisnate12/Plex-Meta-Manager/files/11121364/collection.log)

Let me know if there is anything else needed.

Thanks!

### Relevant Collection/Overlay/Playlist Definition

```yml
From config.yml:

libraries:
  TV Shows:
    metadata_path:
      - file: config/TV.yml
    overlay_path:
      # - remove_overlays: false                                                
      - reapply_overlays: true
      - file: config/overlays/QuickStartTV.yml
      - pmm: ribbon
        template_variables:
          use_rotten: false
          use_common: false
      - pmm: ratings
        template_variables:
          overlay_level: show

          rating1: critic
          rating1_image: rt_tomato
          rating1_font: config/custom_fonts/Adlib.ttf
          rating1_font_size: 63

          rating2: audience
          rating2_image: rt_popcorn
          rating2_font: config/custom_fonts/Adlib.ttf
          rating2_font_size: 63

          vertical_position: bottom
          horizontal_position: left
          rating_alignment: horizontal

    operations:
      mass_critic_rating_update: mdb_tomatoes
      mass_audience_rating_update: audiencemdb_tomatoes

From TV.yml:

collections:
 Netflix:
    url_poster: https://theposterdb.com/api/assets/248185/view
    imdb_list:
      - https://www.imdb.com/list/ls093971121/
      - https://www.imdb.com/list/ls050522997/
      - https://www.imdb.com/list/ls093350982/
    sort_title: "!10 Netflix"
    sync_mode: sync
```

**Comment by YozoraXCII** [comment]
@tunerooster can you provide your entire log file?

If there is no exit error, this normally indicates that something has caused PMM to crash (such as running out of memory)

**Comment by YozoraXCII** [comment]
@tunerooster chasing meta.log file please, else this will be closed.

**Comment by tunerooster** [comment]
Sorry, I have been away!  I will provide the log tomorrow.  Thanks for your
patience and understanding.

**Comment by tunerooster** [comment]
Well, I'm not sure why but...
* As I posted above, the STDOUT log hangs after displaying:
```
 Netflix Collection | ? | The Life and Movies of ErÅ
```
After about 10 minutes, it comples the partial line above with:
```
| Netflix Collection | ? | The Life and Movies of ErÅ<U+009F>an Kuneri (TVDb: 395465)  |
```
* It then continues normally to conclusion.

**I was apparently too impatient and assumed after 5 minutes of no output, that is was hung.**

Unless you want to investigate the 10 minute pause in STDOUT on the special character, you can close this issue.

Otherwise, let me know and I will post the full log files.   I'm good to go, as it is...  THANKS for your help and I apologize for the delayed response on my part!

**Comment by oilervoss** [comment]
I have similar issue. 
I'm running it in Docker.  PMM goes OK for the first Two movies libraries. Then it starts TV Shows operations. It hangs on `Downloading IMDb Interface:  93.95%` , when the memory is 0% free. I've tried to rise the Docker memory limit to 2G but that isn't the issue. Usually the memory usage stays below 500K.

<details>

<summary>Docker compose.yml</summary>

```yaml
# Docker compose.yml
services:
  pmm:
    container_name: pmm
    image: meisnate12/plex-meta-manager
    mem_reservation: 500m
    mem_limit: 2g
    volumes:
      - ./config/pmm:/config
      - /etc/localtime:/etc/localtime:ro
  environment:
    - PUID=${PUID:-1000}
    - PGID=${PGID:-44}
    - TZ=Canada/Eastern
  extra_hosts:
    - "host.docker.internal:host-gateway"
```

</details>


<details>

<summary>PMM config.yml</summary>

```yaml
# PMM config.yml
libraries:
#==================================================
  Movies: &movies
#==================================================
    template_variables: &moviestempl
      use_separator: false
    metadata_path: &moviesmeta
      - pmm: basic
      - pmm: imdb
      - pmm: streaming
        template_variables:
          region: us
#-------------------------------------------------
    overlay_path:
      - remove_overlays: false
      - reapply_overlay: true

      - pmm: resolution
        template_variables:
          vertical_align: top
          horizontal_align: left
      - pmm: audio_codec
        template_variables:
          vertical_offset: 10%
          horizontal_align: left
      - pmm: video_format
        template_variables:
          vertical_offset: 17%
          horizontal_align: left
      - pmm: streaming
        template_variables:
          vertical_align: bottom
          horizontal_align: left
      - pmm: flixpatrol
        template_variables:
          location: united_states
          vertical_offset: 65%
          horizontal_align: left
      - pmm: mediastinger
        template_variables:
          vertical_align: top
          horizontal_align: right
          back_radius: 35
          back_color: '#FF4500'
      - pmm: ribbon
        template_variables:
          weight_metacritic: 35
      - pmm: ratings
        template_variables:
          rating1: critic
          rating1_image: metacritic
          rating1_font: config/fonts/Adlib.ttf
          rating1_font_size: 71

          rating2: audience
          rating2_image: rt_tomato
          rating2_font: config/fonts/Impact.ttf
          rating2_font_size: 64

          rating3: user
          rating3_image: imdb
          rating3_font: config/fonts/Avenir_95_Black.ttf
          rating3_font_size: 70

          horizontal_position: right
    operations: &operations
      mass_critic_rating_update: mdb_metacritic
      mass_audience_rating_update: mdb_tomatoes
      mass_user_rating_update: imdb
#==================================================
  Movies 4K: *movies
#==================================================
  Series: &series
#==================================================
    template_variables: *moviestempl
    metadata_path: *moviesmeta
#-------------------------------------------------
    overlay_path:
      - remove_overlays: false
      - reapply_overlay: true

      - pmm: streaming
        template_variables:
          vertical_align: bottom
          horizontal_align: left
      - pmm: flixpatrol
        template_variables:
          location: united_states
          vertical_offset: 65%
          horizontal_align: left
      - pmm: mediastinger
        template_variables:
          vertical_align: top
          horizontal_align: right
          back_radius: 35
          back_color: '#FF4500'
      - pmm: ribbon
        template_variables:
          weight_metacritic: 35
      - pmm: ratings
        template_variables:
          rating1: critic
          rating1_image: metacritic
          rating1_font: config/fonts/Adlib.ttf
          rating1_font_size: 71

          rating2: audience
          rating2_image: rt_tomato
          rating2_font: config/fonts/Impact.ttf
          rating2_font_size: 64

          rating3: user
          rating3_image: imdb
          rating3_font: config/fonts/Avenir_95_Black.ttf
          rating3_font_size: 70

          horizontal_position: right
#--------------------------------------------------
      - pmm: resolution
        template_variables:
          vertical_align: top
          horizontal_align: left
          overlay_level: episode
      - pmm: audio_codec
        template_variables:
          vertical_offset: 10%
          horizontal_align: left
          overlay_level: episode
      - pmm: video_format
        template_variables:
          vertical_offset: 17%
          horizontal_align: left
          overlay_level: episode
      - pmm: mediastinger
        template_variables:
          vertical_align: top
          horizontal_align: right
          back_radius: 35
          back_color: '#FF4500'
          overlay_level: episode
      - pmm: episode_info
        template_variables:
          vertical_align: bottom
          horizontal_align: center
          font_size: 84
      - pmm: ratings
        template_variables:
          rating1: user
          rating1_image: imdb
          rating1_font: config/fonts/Adlib.ttf
          rating1_font_size: 72
          horizontal_position: right
          overlay_level: episode

    operations:
      <<: *operations
      mass_episode_user_rating_update: imdb

#==================================================
  Series 4K: *series
#==================================================
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: false
  save_report: false
  tvdb_language: eng
  ignore_ids: 365028,62721,70522
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
plex:
  url: xxx
  token: xxx
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
tmdb:
  apikey: xxx
  language: en
  cache_expiration: 60
  region:
tautulli:
  url: xxx
  apikey: xxx
omdb:
  apikey: xxx
  cache_expiration: 60
mdblist:
  apikey: xxx
  cache_expiration: 60
trakt:
  client_id: xxx
  client_secret: xxx
  pin:
  authorization:
    access_token: xxx
    token_type: Bearer
    expires_in: xxx
    refresh_token: xxx
    scope: public
    created_at: xxx
```

</details>
