### ISSUE TITLE
[Docs]: Sentence Not Matching Example

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1379]
### What is the improvement or update to the Wiki you wish to see?

From the wiki, I believe the line "An example of disabling separators at the library-level cam be seen here"
Should be changed to "An example of changing the style of separators at the library-level can be seen here"
The disabling of separators is shown in an example above this one.

--------------------------------------
The style of separator can be defined per-file and per-library.

An example of disabling separators at the library-level cam be seen here

```yaml
libraries:
  Movies:
    template_variables:
      sep_style: red
```

And at the file-level

```yaml
libraries:
  Movies:
    metadata_path:
      - pmm: studio
        template_variables:
          sep_style: stb
```

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/latest/defaults/separators.html
