### ISSUE TITLE
Localised posters are replaced by PMM on run.

### ISSUE THREAD

**Issue by martindahlswe** [Kometa-Team/Kometa#1383]
### Version Number

 1.19.0

### What branch are you on?

master

### Describe the Bug

To be honest I'm not sure if this is a bug or not, so please move it somewhere else if it's not considered one.

I've changed the posters a quite a few movies / tv shows in my Plex library and when adding "pmm: resolution" to the config they get replaced to the default / English ones with the overlay added.
Is this behaviour something that I can change somehow?

Gone through a lot of the documentation without finding anything that looks useful.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Movies:
    metadata_path:
    - pmm: basic
    - pmm: imdb
    overlay_path:
    - remove_overlays: false
    - pmm: ribbon
    - pmm: resolution
  TV Shows:
    metadata_path:
    - pmm: basic
    - pmm: imdb
    overlay_path:
    - remove_overlays: false
    - pmm: ribbon
    - pmm: resolution
```
