### ISSUE TITLE
Error for "plus" resolution overlay: "No builders were found"

### ISSUE THREAD

**Issue by mnkhouri** [Kometa-Team/Kometa#1407]
### Version Number

1.19.0 (Docker)

### What branch are you on?

master

### Describe the Bug

When enabling the "plus" overlay from the default "Resolution/Edition Overlay", I encounter an error: `Overlay Error: No builders were found`. 

### Relevant Collection/Overlay/Playlist Definition

```yml
overlay_path:
    - pmm: resolution
      template_variables:
        use_edition: true
        use_4k: true
        use_1080p: false
        use_720p: false
        use_576p: false
        use_480p: false
        use_plus: true
        use_dv: true
        use_hdr: true
```

### Logs

https://gist.github.com/mnkhouri/57c8511e3df464581476265fe32b838c
