### ISSUE TITLE
SSL Error when using ratings overlay

### ISSUE THREAD

**Issue by skatenroll** [Kometa-Team/Kometa#1440]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

Hello, I have searched far and wide for this answer and spent hours troubleshooting. 

I am trying to use the PMM ratings overlay without success. All other aspects of PMM work as intended from collection building to metadata editing, to radarr integration. When I try and build the overlay, it seems to run well up until I get a repeated SLL error as seen in the log below. It will build the overlay for the 3 movies in the library without any errors but will fail whenever it tries to put the overlay onto the poster. 

I have not tried to use a non-default script to build an overlay yet. Any troubleshooting steps or suggestions to fix this would be appreciated.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:                                      
  1movie:  ## https://metamanager.wiki/en/latest/home/guides/ratings.html ##
    overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating2: audience
        rating3: user
        rating1_image: metacritic
        rating2_image: tmdb
        rating3_image: imdb
    - reapply_overlays: true
    operations:
      mass_user_rating_update: imdb        
      mass_critic_rating_update: mdb_metacritic               
      mass_audience_rating_update: tmdb  

plex:                                          
  url: https://192.168.1.13:32400
  token: xxxxxxxxxxxxxx
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
```

### Logs

https://gist.github.com/skatenroll/f4b8852ed63dca2e732812049f71cb84
