### ISSUE TITLE
dimensional_asset_rename renaming formatted assets

### ISSUE THREAD

**Issue by polklabs** [Kometa-Team/Kometa#1457]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

When dimensional_asset_rename is true PMM will rename any file in the asset folder even if it is already formatted to another purpose.

Example:
 
`assets > Obi-Wan Kenobi > Season01.jpg` will be renamed to `poster.jpg` even though it has a valid asset name.

Assets with valid names should be ignored with dimensional_asset_rename  is on:

- Season##.ext
- Season##_background.ext
- S##E##.ext
- S##E##_background.ext

This allows me/user to keep the Plex assigned poster but override season posters or episode posters, while also not having to rename posters.ext when adding to asset directory.

This can be solved by just turning dimensional_asset_rename off and taking a few seconds to rename the file

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:                                 
  TV Shows:
    ...
    operations:
      assets_for_all: true
settings:
  dimensional_asset_rename: true
```
