### ISSUE TITLE
[Defaults]: Ratings Overlay Doesn't Use Percent Sign

### ISSUE THREAD

**Issue by Mjsciarabba** [Kometa-Team/Kometa#1478]
### Link to File

overlays/ratings

### Version Number

1.19.0

### What branch are you on?

nightly

### Describe the Bug

The ratings overlay will apply the proper number but won't add the percent at the end (for example, 72 vs 72%)

**Comment by meisnate12** [comment]
the rating should only default to percent for `rt_popcorn`, `rt_tomato`, and `tmdb` are you using one of those you can change the style your self using `rating#_style: "%"` switch out the `#` with your rating number

**Comment by chazlarson** [comment]
Something has changed WRT this in nightly.

example config:
```
libraries:
  Movies:
    overlay_path:
    - reapply_overlays: true
    - pmm: ratings
      template_variables:
        rating1: audience
        rating1_image: rt_popcorn
        rating1_horizontal_offset: 60
        rating1_vertical_offset: 55

        vertical_position: top
    operations:
      mass_audience_rating_update: mdb_tomatoesaudience
```

latest:
```
docker run --rm -ti -v /opt/pmm/config:/config meisnate12/plex-meta-manager -c /config/rating-test.yml --run
```
<img width="679" alt="image" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/62b53cd4-e69b-4470-afdf-d1fe5625d10b">

nightly:
```
docker run --rm -ti -v /opt/pmm/config:/config meisnate12/plex-meta-manager:nightly -c /config/rating-test.yml --run
```
<img width="679" alt="image" src="https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/c93ec08b-189a-4cc9-858d-2ded25ea3e61">
