### ISSUE TITLE
Mdblist issue: Unknown Error: At least one ID is required

### ISSUE THREAD

**Issue by rzilla75** [Kometa-Team/Kometa#1491]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

mdblist items are failing. I have a few lists that were working but now fail. It happens with both movies and TV shows. 

Error Message: Unknown Error: At least one ID is required

Log has been attached.

### Relevant Collection/Overlay/Playlist Definition

```yml
Here is the related part of my TVShows.yml:

  Best New Shows for 2023:
    mdblist_list: https://mdblist.com/lists/rzilla75/top-new-shows-2022
    collection_order: custom
    sync_mode: sync    
    sonarr_tag: pmm-bestnew2023
```

### Logs

https://gist.github.com/rzilla75/8a3d37dd243aaf8069a8e6b44bcbf954
