### ISSUE TITLE
Plex Error: actor: xxxx not found

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#151]
I have collections for concerts that search for title and actor. The metadata on concerts is not very consistent so searching on both a band name and the members will get me good result. But since the latest changes this has stopped working. If the actor in the plex search doesnt exist then the collection will fail

```
templates:
  Bands:
    sync_mode: sync
    collection_order: release
    name_mapping: "- Bands/<<collection_name>>"
    plex_search:
      title: <<collection_name>>

collections:
  King Crimson:
    template:
      name: Bands
    actor:
      - Robert Fripp


Scanning King Crimson Collection                                                                   |
| Plex Error: actor: Robert Fripp not found 
```

I also wonder if I can use lists with the templates? I'm quite sure I did it before but now it crashes if I do something like this:
```
templates:
  Bands:
    sync_mode: sync
    collection_order: release
    name_mapping: "- Bands/<<collection_name>>"
    plex_search:
      title: <<collection_name>>
      actor: <<members>>

collections:
  Led Zeppelin:
    template:
      name: Bands
      members:
        - Jimmy Page
        - Robert Plant
        - John Paul Jones
        - John Bonham
```

**Comment by meisnate12** [comment]
i can have it continue if it cant find the actor and I haven't tried lists in templates ill try it out and see if I can fix it

**Comment by Alaksin** [comment]
Makes more sense to treat it like `not found` instead of aborting the search

**Comment by meisnate12** [comment]
ok so for now no lists do not work with templates ill see if i can manage it but what you can do is give it a comma separated string like:
```yaml
collections:
  Led Zeppelin:
    template:
      name: Bands
      members: Jimmy Page, Robert Plant, John Paul Jones, John Bonham
```
