### ISSUE TITLE
Letterboxd ratings overlay issue

### ISSUE THREAD

**Issue by coreylane** [Kometa-Team/Kometa#1544]
### Version Number

1.19.0-nightly79

### What branch are you on?

nightly

### Describe the Bug

Letterboxd ratings appear as `user_rating/` on overlay

Related: https://github.com/meisnate12/Plex-Meta-Manager/pull/1516

### Relevant Collection/Overlay/Playlist Definition

```yml
overlay_path:
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: rt_tomato
        rating2: audience
        rating2_image: rt_popcorn
        rating3: user
        rating3_image: letterboxd
        rating3_style: "/"
    operations:
      mass_critic_rating_update: mdb_tomatoes
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: mdb_letterboxd
```
