### ISSUE TITLE
PMM crashes on Plex 406 not_acceptable error

### ISSUE THREAD

**Issue by WebAddict** [Kometa-Team/Kometa#1573]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

This request is asking to handle an error returned by Plex API  406 error without stopping the rest of the execution. Here is the output from the console log. This breaks reliably every time. I cannot process new overlays on this tv library.  The specific url it's resetting the overlay to item 71799 - maps to an episode of a show. It's not able to reset to the original overlay because it doesn't exist anymore (broken image inside plex episode edit poster has a broken image in plex). So the script breaks on the same episode every single time.

PMM should treat 406 errors like it does 404 error - TRYing and CATCHING EXCEPTIONS and moving on to next task without failing completely. In this case you probably just need to add a handler for the 406...

```
|=====================================================================================================================================================================|
|                                                                Removing Overlays for the TV Library                                                                 |
|=====================================================================================================================================================================|
| Traceback (most recent call last):                                                                                                                                  |
|   File "//plex_meta_manager.py", line 647, in run_libraries                                                                                                         |
|     run_operations_and_overlays()                                                                                                                                   |
|   File "//plex_meta_manager.py", line 595, in run_operations_and_overlays                                                                                           |
|     library_status[library.name]["Library Overlays"] = library.Overlays.run_overlays()                                                                              |
|                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                              |
|   File "/modules/overlays.py", line 62, in run_overlays                                                                                                             |
|     self.remove_overlay(item, item_title, "Overlay", [                                                                                                              |
|   File "/modules/overlays.py", line 511, in remove_overlay                                                                                                          |
|     self.library.upload_poster(item, poster_location, url=is_url)                                                                                                   |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 56, in wrapped_f                                                                                 |
|     return Retrying(*dargs, **dkw).call(f, *args, **kw)                                                                                                             |
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 257, in call                                                                                     |
|     return attempt.get(self._wrap_exception)                                                                                                                        |
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                        |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 301, in get                                                                                      |
|     six.reraise(self.value[0], self.value[1], self.value[2])                                                                                                        |
|   File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise                                                                                       |
|     raise value                                                                                                                                                     |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 251, in call                                                                                     |
|     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)                                                                                                   |
|                       ^^^^^^^^^^^^^^^^^^^                                                                                                                           |
|   File "/modules/plex.py", line 719, in upload_poster                                                                                                               |
|     item.uploadPoster(url=image)                                                                                                                                    |
|   File "/usr/local/lib/python3.11/site-packages/plexapi/mixins.py", line 455, in uploadPoster                                                                       |
|     self._server.query(key, method=self._server._session.post)                                                                                                      |
|   File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 755, in query                                                                              |
|     raise BadRequest(message)                                                                                                                                       |
| plexapi.exceptions.BadRequest: (406) not_acceptable; (redacted)/library/metadata/71799/posters?url=http%3A%2F%2F192.168.69.2%3A32402%2Flibrary%2Fmetadata%2F71799%2Ffile%3Furl%3Dmetadata%253A%252F%252Fposters%252Ftv%252Eplex%252Eagents%252Eseries_20aa3a9dc3affb73f9cbed662e2270a1be7e8045%26X-Plex-Token%3D(redacted) <html><head><title>Not Acceptable</title></head><body><h1>406 Not Acceptable</h1></body></html> |
|                                                                                                                                                                     |
| (406) not_acceptable; (redacted)/library/metadata/71799/posters?url=http%3A%2F%2F192.168.69.2%3A32402%2Flibrary%2Fmetadata%2F71799%2Ffile%3Furl%3Dmetadata%253A%252F%252Fposters%252Ftv%252Eplex%252Eagents%252Eseries_20aa3a9dc3affb73f9cbed662e2270a1be7e8045%26X-Plex-Token%3D(redacted) <html><head><title>Not Acceptable</title></head><body><h1>406 Not Acceptable</h1></body></html> |
|                                                                                                                                                                     |
``` 

### Relevant Collection/Overlay/Playlist Definition

```yml
config.yml
--------
libraries:
  TV:
    schedule: daily
    overlay_path:
    - remove_overlays: false
    - pmm: ribbon
    - pmm: ratings
      template_variables:
        rating1: critic
        rating1_image: rt_tomato
        rating2: user
        rating2_image: rt_popcorn
        rating3: audience
        rating3_image: imdb
    - pmm: commonsense
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
```
