### ISSUE TITLE
`actor` default collections: adding values with`include:` template variable results in ONLY those names getting collections

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#1625]
### Version Number

1.19.1-nightly1

### What branch are you on?

nightly

### Describe the Bug

This:
```
  Movies:
    metadata_path:
    - pmm: actor
      template_variables:
        data:
          depth: 5
          limit: 15
```
Creates 15 collections as expected.

This:
```
  Movies:
    metadata_path:
    - pmm: actor
      template_variables:
        data:
          depth: 5
          limit: 15
        include:
        - Roy Scheider
        - Mark Hamill
```
creates two.
