### ISSUE TITLE
Rating or Filter is not working for me

### ISSUE THREAD

**Issue by AwesomeAustn** [Kometa-Team/Kometa#163]
`rating.gte` or filter is not working for me.
```
Good Comedy:
  plex_search:
    genre: Comedy
  filters:
    rating.gte: 8
  sync_mode: sync
  collection_mode: default
  collection_order: alpha
  sort_title: '*201'
  summary: A collection of Comedy TV Shows with a rating of 8 and higher
```
```
|   File "/modules/config.py", line 462, in update_libraries
|     builder.run_methods(collection_obj, collection_name, rating_key_map, movie_map, show_map)
|   File "/modules/builder.py", line 876, in run_methods
|     if len(items) > 0:                                  rating_key_map = self.library.add_to_collection(collection_obj if collection_obj else collection_name, items, self.filters, self.details["show_filtered"], rating_key_map, movie_map, show_map)
|   File "/modules/plex.py", line 213, in add_to_collection
|     if (modifier == ".lte" and attr > filter_data) or (modifier == ".gte" and attr < filter_data):
| TypeError: '<' not supported between instances of 'NoneType' and 'float'
```
It processes 24 shows and then gives the error. For my Drama one, it only processes one show. It stops at the same point every time.

**Comment by meisnate12** [comment]
i think ive already fixed this in develop if you wanted to switch and see

**Comment by AwesomeAustn** [comment]
Thanks! I'll switch over.

**Comment by AwesomeAustn** [comment]
```
| Scanning Good Comedy Collection                                                                    |
| Collection Warning: rating.gte filter will run as critic_rating.gte                                |
|                                                                                                    |
| Sync Mode: sync                                                                                    |
|                                                                                                    |
| Collection Filter critic_rating.gte: 8.0                                                           |
|                                                                                                    |
| Processing Plex Search: genre(Comedy)                                                              |
| Unknown Error: 'Show' object has no attribute 'critic_rating'                                      |
```

**Comment by meisnate12** [comment]
fix is in develop. Also `plex_search` is much faster then using filters. i would suggest this:
```yaml
Good Comedy:
  plex_search:
    genre: Comedy
    critic_rating.greater: 8
  sync_mode: sync
  collection_mode: default
  collection_order: alpha
  sort_title: '*201'
  summary: A collection of Comedy TV Shows with a rating of 8 and higher
```

Also this search above currently only works in develop
