### ISSUE TITLE
Delete Unconfigured Collections behavior

### ISSUE THREAD

**Issue by benfishbus** [Kometa-Team/Kometa#1641]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

With this feature turned on like so:
Movies:
  operations:
    delete_collections:
      configured: false
...any existing collection I add a schedule to gets deleted on the next run.

If I disable (comment out) the feature, this does not happen - i.e., adding a schedule to an existing collection does not cause it to be deleted on the next run.

For these tests, I am executing my full config - "python plex_meta_manager.py --run"

The wiki says for the 'configured' attribute:
`true: Collection must be a Configured Collection to be deleted (collection is in the config file of the specific PMM run)
false: Collection must be an Unconfigured Collection to be deleted (collection is not in the config file of the specific PMM run).
The collection does not need to be scheduled to be considered configured and only needs to be in the config file.`

I understood this to mean that a collection is still considered 'configured' even if it's excluded from a run due to its schedule, and should thus be unaffected by a delete_collections operation targeting unconfigured collections. Am I reading it right?

**Comment by YozoraXCII** [comment]
i cannot reproduce this on 1.20

I have two collections: `Test 1` and `Test 2`:

```yml
collections:
  Test 1:
    plex_all: true

  Test 2:
    plex_all true
 ```
 
 I run and both collections are created.
 
 I now change Test 2:
 ```yml
collections:
  Test 1:
    plex_all: true

  Test 2:
    plex_all true
    schedule: weekly(sunday)     # added this
 ```
 and I amend my operations:
 ```yml
 libraries:
  Movies:
    collection_files:
      - config/test.yml
    operations:
      delete_collections:
        configured: false
```
 I run PMM and both collections still exist:
 
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/20eb0586-1873-48ac-b504-29691d3e53f5)

Log attached:
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/13890471/meta.log)
