### ISSUE TITLE
Duration filter not working?

### ISSUE THREAD

**Issue by chrisbenincasa** [Kometa-Team/Kometa#1666]
### Version Number

1.19.0

### What branch are you on?

master

### Describe the Bug

Filtering by runtime with seemingly simple template+collection not working as expected:

> `duration` Uses the duration attribute to match using minutes

**Example config:**

```yaml
templates:
  Radarr Only:
    build_collection: false
    schedule: daily
    radarr_add_missing: true
    filters:
      duration.gte: 60.0
    radarr_tag:
      - pmm
      - <<collection_name>>
collections:
  PTA:
    tmdb_director: 4762
    template: 
      name: Radarr Only
```

However, this adds releases such as: [`Ballchewer (2002) (TMDb: 704455)`](https://www.themoviedb.org/movie/704455-ballchewer?language=de) (runtime 1m) and [`Production Assistant (1992) (TMDb: 966259)`](https://www.themoviedb.org/movie/966259-paul-thomas-anderson-production-assistant?language=sr-RS)

<details>
<summary>TMDB responde for ID=704455 (note runtime=1)</summary>

```json
{
  "adult": false,
  "backdrop_path": null,
  "belongs_to_collection": null,
  "budget": 0,
  "genres": [],
  "homepage": "https://www.youtube.com/watch?v=vJ5Ooej_8EA",
  "id": 704455,
  "imdb_id": null,
  "original_language": "en",
  "original_title": "Ballchewer",
  "overview": "A short film directed by Paul Thomas Anderson.  Part of Adam Sandler's 'Meatball Series'.  Shot during the filming of  'Punch-Drunk Love'.",
  "popularity": 0.78,
  "poster_path": "/bsvYPrUscvLzDgojcljKv19ohIc.jpg",
  "production_companies": [],
  "production_countries": [],
  "release_date": "2002-11-01",
  "revenue": 0,
  "runtime": 1,
  "spoken_languages": [],
  "status": "Released",
  "tagline": "",
  "title": "Ballchewer",
  "video": false,
  "vote_average": 4.8,
  "vote_count": 5
}
```

</details>
