### ISSUE TITLE
audio_language exclude other not working

### ISSUE THREAD

**Issue by boexler** [Kometa-Team/Kometa#1683]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

I have excluded the `other`, but it's still beeing created

![grafik](https://github.com/meisnate12/Plex-Meta-Manager/assets/17551597/6deb3069-9753-4ca4-a24a-a7229ab6a5a1)

see: https://metamanager.wiki/en/latest/defaults/both/audio_language.html

### Relevant Collection/Overlay/Playlist Definition

```yml
- pmm: audio_language   # eng + french
      template_variables:
        style: color
        include:
        - en
        - fr
        exclude:
        - other
```
