### ISSUE TITLE
No matter what I do - (500) Internal Server Error

### ISSUE THREAD

**Issue by MikeFalcor** [Kometa-Team/Kometa#1690]
### Version Number

1.19.1

### What branch are you on?

nightly

### Describe the Bug

I have dumbed down my config so that it is running on a single library after multiple failed attempts to run against all libraries. I even removed the ribbon overlay to speed things up to see what the issue may be. Still...plagued by (500) errors and no overlay updates.

Entire config below. Everything but 'Anime' is commented out.

Plex Server version is 1.32.7.7621 (PlexPass)

Relevant errors:
```
|==================================================================================================== Number of Items Per Overlay =====================================================================================================|
|                                                                                                                                                                                                                                      |
|             Overlay              | Number |                                                                                                                                                                                          |
| ================================ | ====== |                                                                                                                                                                                          |
| Overlay File (0) airing_shows    |   11   |                                                                                                                                                                                          |
| Overlay File (0) returning_shows |   22   |                                                                                                                                                                                          |
| Overlay File (0) canceled_shows  |   0    |                                                                                                                                                                                          |
| Overlay File (0) ended_shows     |   80   |                                                                                                                                                                                          |
| Overlay File (1) Rating1Rotten   |   0    |                                                                                                                                                                                          |
| Overlay File (1) Rating1Fresh    |   13   |                                                                                                                                                                                          |
| Overlay File (1) Rating1Top      |   0    |                                                                                                                                                                                          |
| Overlay File (1) Rating2Rotten   |   5    |                                                                                                                                                                                          |
| Overlay File (1) Rating2Fresh    |   98   |                                                                                                                                                                                          |
| Overlay File (1) Rating2Top      |   18   |                                                                                                                                                                                          |
| Overlay File (1) Rating3Rotten   |   5    |                                                                                                                                                                                          |
| Overlay File (1) Rating3Fresh    |   98   |                                                                                                                                                                                          |
| Overlay File (2) runtime_info    |  7423  |                                                                                                                                                                                          |
|                                                                                                                                                                                                                                      |
| Traceback (most recent call last):                                                                                                                                                                                                   |
|   File "//plex_meta_manager.py", line 627, in run_libraries                                                                                                                                                                          |
|     run_operations_and_overlays()                                                                                                                                                                                                    |
|   File "//plex_meta_manager.py", line 575, in run_operations_and_overlays                                                                                                                                                            |
|     library_status[library.name]["Library Overlays"] = library.Overlays.run_overlays()                                                                                                                                               |
|                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                               |
|   File "/modules/overlays.py", line 50, in run_overlays                                                                                                                                                                              |
|     remove_overlays = self.get_overlay_items(ignore=ignore_list)                                                                                                                                                                     |
|                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                     |
|   File "/modules/overlays.py", line 500, in get_overlay_items                                                                                                                                                                        |
|     items = self.library.search(label=label, libtype=libtype)                                                                                                                                                                        |
|             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                        |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 56, in wrapped_f                                                                                                                                                  |
|     return Retrying(*dargs, **dkw).call(f, *args, **kw)                                                                                                                                                                              |
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                              |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 257, in call                                                                                                                                                      |
|     return attempt.get(self._wrap_exception)                                                                                                                                                                                         |
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                         |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 301, in get                                                                                                                                                       |
|     six.reraise(self.value[0], self.value[1], self.value[2])                                                                                                                                                                         |
|   File "/usr/local/lib/python3.11/site-packages/six.py", line 719, in reraise                                                                                                                                                        |
|     raise value                                                                                                                                                                                                                      |
|   File "/usr/local/lib/python3.11/site-packages/retrying.py", line 251, in call                                                                                                                                                      |
|     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)                                                                                                                                                                    |
|                       ^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                            |
|   File "/modules/plex.py", line 544, in search                                                                                                                                                                                       |
|     return self.Plex.search(title=title, sort=sort, maxresults=maxresults, libtype=libtype, **kwargs)                                                                                                                                |
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                |
|   File "/usr/local/lib/python3.11/site-packages/plexapi/library.py", line 1517, in search                                                                                                                                            |
|     return self.fetchItems(                                                                                                                                                                                                          |
|            ^^^^^^^^^^^^^^^^                                                                                                                                                                                                          |
|   File "/usr/local/lib/python3.11/site-packages/plexapi/base.py", line 255, in fetchItems                                                                                                                                            |
|     data = self._server.query(ekey, headers=headers)                                                                                                                                                                                 |
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                 |
|   File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 770, in query                                                                                                                                               |
|     raise BadRequest(message)                                                                                                                                                                                                        |
| plexapi.exceptions.BadRequest: (500) internal_server_error; (redacted)/library/sections/8/all?includeGuids=1&show.label=Overlay <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body>
|                                                                                                                                                                                                                                      |
| (500) internal_server_error; (redacted)/library/sections/8/all?includeGuids=1&show.label=Overlay <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>                       |
|                                                                                                                                                                                                                                      |
```

Final error:
```
|========================================================================================================== Critical Summary ==========================================================================================================|
|                                                                                                                                                                                                                                      |
| Count | Message                                                                                                                                                                                                                      |
|=======|==============================================================================================================================================================================================================================|
|     1 | (500) internal_server_error; (redacted)/library/sections/8/all?includeGuids=1&show.label=Overlay <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>               |
|                                                                                                                                                                                                                                      |
|======================================================================================================================================================================================================================================|
|                                                                                                             Finished Run                                                                                                             |
|                                                                                  Version: 1.19.1-nightly18        Newest Version: 1.19.1-nightly20                                                                                   |
|                                                                                           Finished: 16:19:44 2023-10-26 Run Time: 0:04:58                                                                                            |
|======================================================================================================================================================================================================================================|
```

I think I am losing my mind...LOL! Perhaps a rollback to previous Plex Server version is in order?

### Relevant Collection/Overlay/Playlist Definition

```yml
## This file is a template remove the .template to use the file

libraries:
  Anime:
    report_path: config/missing/Anime-report.yml
    template_variables:
      use_separator: false
    library_name: Anime
    overlay_path:
    - remove_overlays: false
    - reapply_overlay: true
    - pmm: status
      template_variables:
        vertical_offset: 15
    - pmm: ratings
      template_variables:
        rating1: user
        rating1_image: rt_tomato
        rating1_font: config/custom_fonts/Adlib.ttf
        rating1_font_size: 63

        rating2: critic
        rating2_image: imdb
        rating2_font: config/custom_fonts/Impact.ttf
        rating2_font_size: 70

        rating3: audience
        rating3_image: tmdb
        rating3_font: config/custom_fonts/Avenir_95_Black.ttf
        rating3_font_size: 70

        horizontal_position: left
        horizontal_offset: 15
#    - pmm: ribbon
#      template_variables:
#        style: black
    - pmm: runtimes
      template_variables:
        overlay_level: episode
    operations:
      mass_user_rating_update: mdb_tomatoes
      mass_critic_rating_update: imdb
      mass_audience_rating_update: tmdb
      mass_genre_update: tmdb
      mass_originally_available_update: tmdb

#  Comedy Specials:
#    report_path: config/missing/Comedy_Specials-report.yml
#    template_variables:
#      sep_style: gray
#      collection_mode: hide
#    overlay_path:
#      - remove_overlays: false
#      - reapply_overlay: true
#      - pmm: mediastinger
#        template_variables:
#          horizontal_offset: 15
#          horizontal_align: left
#          vertical_align: bottom
#      - pmm: ratings
#        template_variables:
#          rating1: user
#          rating1_image: rt_tomato
#          rating1_font: config/custom_fonts/Adlib.ttf
#          rating1_font_size: 63
#
#          rating2: critic
#          rating2_image: imdb
#          rating2_font: config/custom_fonts/Impact.ttf
#          rating2_font_size: 70
#
#          rating3: audience
#          rating3_image: tmdb
#          rating3_font: config/custom_fonts/Avenir_95_Black.ttf
#          rating3_font_size: 70
#
#          horizontal_position: left
#          horizontal_offset: 15
#      - pmm: ribbon
#        template_variables:
#          style: black
#    operations:
#      mass_user_rating_update: mdb_tomatoes
#      mass_critic_rating_update: imdb
#      mass_audience_rating_update: tmdb
#      mass_genre_update: tmdb
#      mass_originally_available_update: tmdb
#
#  Documentaries:
#    report_path: config/missing/Documentaries-report.yml
#    overlay_path:
#      - remove_overlays: false
#      - reapply_overlay: true
#      - pmm: mediastinger
#        template_variables:
#          horizontal_offset: 15
#          horizontal_align: left
#          vertical_align: bottom
#      - pmm: ratings
#        template_variables:
#          rating1: user
#          rating1_image: rt_tomato
#          rating1_font: config/custom_fonts/Adlib.ttf
#          rating1_font_size: 63
#
#          rating2: critic
#          rating2_image: imdb
#          rating2_font: config/custom_fonts/Impact.ttf
#          rating2_font_size: 70
#
#          rating3: audience
#          rating3_image: tmdb
#          rating3_font: config/custom_fonts/Avenir_95_Black.ttf
#          rating3_font_size: 70
#
#          horizontal_position: left
#          horizontal_offset: 15
#      - pmm: ribbon
#        template_variables:
#          style: black
#    operations:
#      mass_user_rating_update: mdb_tomatoes
#      mass_critic_rating_update: imdb
#      mass_audience_rating_update: tmdb
#      mass_genre_update: tmdb
#      mass_originally_available_update: tmdb
#
#  Movies:
#    report_path: config/missing/Movies-report.yml
#    overlay_path:
#      - remove_overlays: false
#      - reapply_overlay: true
#      - pmm: mediastinger
#        template_variables:
#          horizontal_offset: 15
#          horizontal_align: left
#          vertical_align: bottom
#      - pmm: ratings
#        template_variables:
#          rating1: user
#          rating1_image: rt_tomato
#          rating1_font: config/custom_fonts/Adlib.ttf
#          rating1_font_size: 63
#
#          rating2: critic
#          rating2_image: imdb
#          rating2_font: config/custom_fonts/Impact.ttf
#          rating2_font_size: 70
#
#          rating3: audience
#          rating3_image: tmdb
#          rating3_font: config/custom_fonts/Avenir_95_Black.ttf
#          rating3_font_size: 70
#
#          horizontal_position: left
#          horizontal_offset: 15
#      - pmm: ribbon
#        template_variables:
#          style: black
#    operations:
#      mass_collection_mode: hide_items
#      mass_user_rating_update: mdb_tomatoes
#      mass_critic_rating_update: imdb
#      mass_audience_rating_update: tmdb
#      mass_genre_update: tmdb
#      mass_originally_available_update: tmdb
#
#  Shorts:
#    report_path: config/missing/Shorts-report.yml
#    overlay_path:
#      - remove_overlays: false
#      - reapply_overlay: true
#      - pmm: mediastinger
#        template_variables:
#          horizontal_offset: 15
#          horizontal_align: left
#          vertical_align: bottom
#      - pmm: ratings
#        template_variables:
#          rating1: user
#          rating1_image: rt_tomato
#          rating1_font: config/custom_fonts/Adlib.ttf
#          rating1_font_size: 63
#
#          rating2: critic
#          rating2_image: imdb
#          rating2_font: config/custom_fonts/Impact.ttf
#          rating2_font_size: 70
#
#          rating3: audience
#          rating3_image: tmdb
#          rating3_font: config/custom_fonts/Avenir_95_Black.ttf
#          rating3_font_size: 70
#
#          horizontal_position: left
#          horizontal_offset: 15
#      - pmm: ribbon
#        template_variables:
#          style: black
#    operations:
#      mass_user_rating_update: mdb_tomatoes
#      mass_critic_rating_update: imdb
#      mass_audience_rating_update: tmdb
#      mass_genre_update: tmdb
#      mass_originally_available_update: tmdb
#
#  TV Shows:
#    report_path: config/missing/TV_Shows-report.yml
#    overlay_path:
#      - remove_overlays: false
#      - reapply_overlay: true
#      - pmm: status
#        template_variables:
#          vertical_offset: 15
#      - pmm: ratings
#        template_variables:
#          rating1: user
#          rating1_image: rt_tomato
#          rating1_font: config/custom_fonts/Adlib.ttf
#          rating1_font_size: 63
#
#          rating2: critic
#          rating2_image: imdb
#          rating2_font: config/custom_fonts/Impact.ttf
#          rating2_font_size: 70
#
#          rating3: audience
#          rating3_image: tmdb
#          rating3_font: config/custom_fonts/Avenir_95_Black.ttf
#          rating3_font_size: 70
#
#          horizontal_position: left
#          horizontal_offset: 15
#      - pmm: ribbon
#        template_variables:
#          style: black
#      - pmm: runtimes
#        template_variables:
#          overlay_level: episode
#    operations:
#      mass_user_rating_update: mdb_tomatoes
#      mass_critic_rating_update: imdb
#      mass_audience_rating_update: tmdb
#      mass_genre_update: tmdb
#      mass_originally_available_update: tmdb
#
#playlist_files:
#- pmm: playlist
#  template_variables:
#    libraries: Movies, TV Shows

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  missing_path: config/missing
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false
  sync_mode: append
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 1
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: true
  show_options: true
  show_missing: false
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: true
webhooks:
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:
  url: http://20.0.0.240:32400
  token: <redacted>
  timeout: 60
  db_cache: 20480
  clean_bundles: true
  empty_trash: true
  optimize: true
tmdb:
  apikey: <redacted>
  language: en
  cache_expiration: 60
  region:
tautulli:
  url: http://20.0.15.251:8181
  apikey: <redacted>
mdblist:
  apikey: <redacted>
  cache_expiration: 60
#radarr:
#  url: http://192.168.1.12:7878
#  token: ################################
#  add_missing: false
#  add_existing: false
#  root_folder_path: S:/Movies
#  monitor: true
#  availability: announced
#  quality_profile: HD-1080p
#  tag:
#  search: false
#  radarr_path:
#  plex_path:
#sonarr:
#  url: http://192.168.1.12:8989
#  token: ################################
#  add_missing: false
#  add_existing: false
#  root_folder_path: "S:/TV Shows"
#  monitor: all
#  quality_profile: HD-1080p
#  language_profile: English
#  series_type: standard
#  season_folder: true
#  tag:
#  search: false
#  cutoff_search: false
#  sonarr_path:
#  plex_path:
trakt:
  client_id: <redacted>
  client_secret: <redacted>
  pin:
  authorization:
    access_token: <redacted>
    token_type: Bearer
    expires_in: 7889237
    refresh_token: <redacted>
    scope: public
    created_at: 1698360462
```


### Logs

_No response_
