### ISSUE TITLE
Bug with creating Overlays

### ISSUE THREAD

**Issue by denozord** [Kometa-Team/Kometa#1705]
### Version Number

1.19

### What branch are you on?

nightly

### Describe the Bug

Hello
An error appears when creating overlays.
I have tried all possible versions, the error is the same.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Фильмы:
    metadata_path:
    - pmm: basic
    - pmm: tautulli
    overlay_path:
      - reset_overlays: plex
      - remove_overlays: true
      - reapply_overlay: true
      - pmm: resolution                                                    # 1, 4
      - pmm: audio_codec                                                   # 2
      - pmm: mediastinger                                                  # 3
      - pmm: ratings                                                       # 5, 6, 7
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: rus
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.50.1:32400
  token: ********************
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: ****************
  language: ru
  cache_expiration: 60
  region: RU
tautulli:                        # Can be individually specified per library as well
  url: http://192.168.50.1:8181
  apikey: ********************
```

### Logs

https://gist.github.com/denozord/31c5871ab07a654e46397ee2f2a23077

**Comment by YozoraXCII** [comment]
I'm guessing you're running Plex 1.32.7 - it has this known issue, it has been fixed in the 1.32.8 beta, so you need to either downgrade or wait for 1.32.8 to go public

**Comment by chazlarson** [comment]
This is a regression on the Plex side that was introduced in Plex 1.32.7.  Plex has fixed it in 1.32.8.

Your options are:
1. downgrade to Plex 1.32.6
2. upgrade to the beta 1.32.8
3. add an "Overlay" sharing label to any one thing in the library.

**Comment by denozord** [comment]
Thx.
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/13673973/01d1103e-ac75-4dab-b2f2-2992a0de0db1)
And how do I remove the word Movies from the genre name in collections? I've searched all over the wiki, but I can't find anything

**Comment by chazlarson** [comment]
I am assuming you are using the defaults and the config above is incomplete, since there's nothing in that config that would create these collections.

Use the "name_format" template variable:
<https://metamanager.wiki/en/latest/defaults/both/genre.html#template-variables>

```
libraries:
  Movies:
    metadata_path:
      - pmm: genre
        template_variables:
          name_format: <<key_name>>
```
If you want it to be just the genre.
