### ISSUE TITLE
Cache Anilist for faster runs

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#171]
Use the cache to speed up anilist_genre and anilist_tag

```yaml
collections:
  Animes Seinen:
    anilist_tag:
      tag: Seinen
    sync_mode: sync
    sort_title: "#101"
```
