### ISSUE TITLE
Wrong default for ratings overlay

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1717]
### What is the improvement or update to the Wiki you wish to see?

In the template variables for the ratings overlay, it shows:

<html><body>

Variable | Default
-- | --
horizontal_align | right
vertical_align | top

</body>
</html>

However, the default seems to be
<html><body>

Variable | Default
-- | --
horizontal_align | left
vertical_align | middle

</body>
</html>

```yaml
    - pmm: ratings
      template_variables:
        rating1: critic
        rating2: audience
        rating1_image: imdb
        rating2_image: mdb
```
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/67336980/b0e3bc37-e6ef-4cdd-9e06-1702a3b85ac1)

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/develop/defaults/overlays/ratings.html#template-variables
