### ISSUE TITLE
Defaults using IMDB search need to be updated to use the new imdb-search builder.

### ISSUE THREAD

**Issue by JDIacobbo** [Kometa-Team/Kometa#1768]
### Version Number

1.19.1-nightly46 (Python 3.12.0) (Git: nightly)

### What branch are you on?

nightly

### Describe the Bug

Per issue #1722 defaults using IMDB searches need to be updated to use the new imdb-search builder. In an attempt to manually update the default yaml to use the new builder I received the following error which leads me to believe that additional work needs to be done to support this. 

```[2023-12-11 22:17:24,882] [plex_meta_manager.py:817]  [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\plex_meta_manager.py", line 713, in run_collection |
                                                                 |     items_added, items_unchanged = builder.add_to_collection()                                     |
                                                                 |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                     |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\modules\builder.py", line 2665, in add_to_collection |
                                                                 |     self.library.alter_collection(items_added, name, smart_label_collection=self.smart_label_collection) |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\modules\plex.py", line 898, in alter_collection |
                                                                 |     self.query_data(getattr(self.Plex, f"{'add' if add else 'remove'}{'Label' if smart_label_collection else 'Collection'}"), collection) |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\retrying.py", line 56, in wrapped_f |
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)                                            |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                            |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\retrying.py", line 266, in call |
                                                                 |     raise attempt.get()                                                                            |
                                                                 |           ^^^^^^^^^^^^^                                                                            |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\retrying.py", line 301, in get |
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])                                       |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\six.py", line 719, in reraise |
                                                                 |     raise value                                                                                    |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\retrying.py", line 251, in call |
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)                                  |
                                                                 |                       ^^^^^^^^^^^^^^^^^^^                                                          |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\modules\plex.py", line 640, in query_data   |
                                                                 |     return method(data)                                                                            |
                                                                 |            ^^^^^^^^^^^^                                                                            |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\plexapi\mixins.py", line 817, in addCollection |
                                                                 |     return self.editTags('collection', collections, locked=locked)                                 |
                                                                 |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                 |
                                                                 |   File "C:\Users\jdiac\Downloads\PMM\Plex-Meta-Manager\pmm-venv\Lib\site-packages\plexapi\mixins.py", line 758, in editTags |
                                                                 |     items = tags + items                                                                           |
                                                                 |             ~~~~~^~~~~~~                                                                           |
                                                                 | TypeError: unsupported operand type(s) for +: 'method' and 'list'                                  |
                                                                 |                                                                                                    |
[2023-12-11 22:17:24,915] [plex_meta_manager.py:818]  [ERROR]    | Unknown Error: unsupported operand type(s) for +: 'method' and 'list'                              |
```

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
  Oscars Best Picture Winners:
    variables:
      key: best_picture
    template:
      - name: shared
        sort: Oscars !1
        allowed_libraries: movie
        image: award/oscars/best_picture_winner
        translation_key: oscars_picture
      - name: arr
      - name: custom
    imdb_search:
      type: movie
      sort_by: popularity.asc
      event.winning: oscar_picture
    collection_order: release
```

### Logs

https://gist.github.com/JDIacobbo/2b5fbd7948fe990f21ec0c57bae82999

**Comment by ghost** [comment]
This is due to using an old version of plexapi. Update your dependencies from requirements.txt.

**Comment by heylookltsme** [comment]
I've on the latest nightly and I've updated my dependencies, and the `oscars` default collection still isn't working for me: 

```
|========================================== Error Summary ===========================================|
|                                                                                                    |
| Count | Message                                                                                    |
|=======|============================================================================================|
|     2 | IMDb Error: https://www.imdb.com/search/title/?groups=best_picture_winner must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     2 | IMDb Error: https://www.imdb.com/search/title/?groups=best_director_winner must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?release_date=2016-01-01,2016-12-31&groups=oscar_winner&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?release_date=2017-01-01,2017-12-31&groups=oscar_winner&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?release_date=2018-01-01,2018-12-31&groups=oscar_winner&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?release_date=2019-01-01,2019-12-31&groups=oscar_winner&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?release_date=2020-01-01,2020-12-31&groups=oscar_winner&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?release_date=2021-01-01,2021-12-31&groups=oscar_winner&sort=moviemeter,asc must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?groups=golden_globe_winner must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?groups=emmy_winner must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | IMDb Error: https://www.imdb.com/search/title/?groups=razzie_winner must begin with either:https://www.imdb.com/list/ls (For Lists) |
|     1 | TMDb Error: No Movie found for TMDb ID 37452                                               |
|                                                                                                    |
|====================================================================================================|
|                                            Finished Run                                            |
|                                     Version: 1.19.1-nightly46                                      |
|                          Finished: 06:02:34 2023-12-12 Run Time: 0:03:29                           |
|====================================================================================================|
```

My config is simply: 
```
libraries:
  Movies:
    metadata_path: 
      - pmm: oscars
```

Many thanks for your help!

**Comment by ghost** [comment]
IMDB builder requires new configuration options than before: https://metamanager.wiki/en/nightly/builders/imdb/#imdb-search.

The following is my updated configuration that utilizes the new options, which may assist in updating to the new options.
```

## 4_awards.yml

templates:
  award_nominee:
    optional:
      - letterboxd_extra_1
      - letterboxd_extra_2
      - letterboxd_extra_3
      - letterboxd_extra_4
      - letterboxd_extra_5
    sort_title: "+4_<<num>>_<<collection_name>>"
    sync_mode: sync
    collection_order: release.desc
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 6
    imdb_search:
      type: <<type>>
      language: <<language>>
      event: <<event>>
      limit: 1000 

  award_winner:
    sort_title: "+4_<<num>>_<<collection_name>>"
    sync_mode: sync
    collection_order: release.desc
    collection_mode: hide
    visible_home: false
    visible_shared: false
    visible_library: false
    delete_not_scheduled: false
    cache_builders: 6
    imdb_search:
      type: <<type>>
      language: <<language>>
      event.winning: <<event.winning>>
      limit: 1000

collections:
  "Oscar Nominees":
    summary: "A collection of Oscar Nominees"
    url_poster: https://images2.imgbox.com/98/37/PigipQFj_o.png
    template: {
                    name: award_nominee,
                    num: "A",
                    type: "movie,tv_movie",
                    event: "oscar_picture,oscar_director",
                    language: "en"
                    }
    limit: 1000

  "Oscar Winners":
    summary: "A collection of Oscar Winners"
    url_poster: https://images2.imgbox.com/ad/c9/nfhQr1bK_o.png
    template: {
                    name: award_winner,
                    num: "B",
                    type: "movie,tv_movie",
                    event.winning: "oscar_picture,oscar_director",
                    language: "en"
                    }
    limit: 1000

    
  "Golden Globes Nominees":
    summary: "A collection of Golden Globes Nominees"
    url_poster: https://images2.imgbox.com/0a/a2/HH5uBXFt_o.png
    template: {
                    name: award_nominee,
                    num: "C",
                    type: "movie,tv_movie",
                    event: "golden",
                    language: "en"
                    }
    limit: 1000

  "Golden Globes Winners":
    summary: "A collection of Golden Globes Winners"
    url_poster: https://images2.imgbox.com/90/92/iw9mYXgG_o.png
    template: {
                    name: award_winner,
                    num: "D",
                    type: "movie,tv_movie",
                    event.winning: "golden",
                    language: "en"
                    }
    limit: 1000

  "BAFTA Winners":
    summary: "A collection of BAFTA Winners"
    url_poster: https://images2.imgbox.com/00/61/roVpyMsf_o.png
    template: {
                    name: award_winner,
                    num: "E",
                    type: "movie,tv_movie",
                    event.winning: "bafta",
                    language: "en"
                    }
    letterboxd_list:
      - https://letterboxd.com/abdullahaktan/list/bafta-winners-the-british-academy/
    limit: 1000

  "Berlinale Winners":
    summary: "A collection of Berlinale Winners"
    url_poster: https://images2.imgbox.com/91/9a/HV6PSMf9_o.png
    template: {
                    name: award_winner,
                    num: "F",
                    type: "movie,tv_movie",
                    event.winning: "ev0000091",
                    language: "en"
                    }
    letterboxd_list:
      - https://letterboxd.com/koyoti/list/berlinale-golden-bear-winners/
    limit: 1000

  "Cannes Film Festival Winners":
    summary: "A collection of Cannes Film Festival Winners"
    url_poster: https://images2.imgbox.com/f6/58/U3iST84u_o.png
    template: {
                    name: award_winner,
                    num: "G",
                    type: "movie,tv_movie",
                    event.winning: "cannes",
                    language: "en"
                    }
    letterboxd_list:
      - https://letterboxd.com/moviewithus/list/cannes-winners/
    limit: 1000

  "European Film Award Winners":
    summary: "A collection of European Film Award Winners"
    url_poster: https://images2.imgbox.com/c5/4d/I4jeTKM5_o.png
    template: {
                    name: award_winner,
                    num: "H",
                    type: "movie,tv_movie",
                    event.winning: "ev0000230",
                    language: "en"
                    }
    letterboxd_list:
      - https://letterboxd.com/ra_pha/list/european-film-awards/
    limit: 1000

  "Sundance Winners":
    summary: "A collection of Sundance Winners"
    url_poster: https://images2.imgbox.com/00/95/C6ghjx7k_o.png
    template: {
                    name: award_winner,
                    num: "I",
                    type: "movie,tv_movie",
                    event.winning: "sundance",
                    language: "en"
                    }
    letterboxd_list:
      - https://letterboxd.com/glicose/list/winners-of-sundance/
    limit: 1000

  "Venice Film Festival Winners":
    summary: "A collection of Venice Film Festival Winners"
    url_poster: https://images2.imgbox.com/0d/38/P2chh8O7_o.png
    template: {
                    name: award_winner,
                    num: "J",
                    type: "movie,tv_movie",
                    event.winning: "ev0000681",
                    language: "en"
                    }
    letterboxd_list:
      - https://letterboxd.com/moviewithus/list/biennale-winners/
    limit: 1000
    
  "Critic's Choice Winners":
    summary: "A collection of Critic's Choice Winners"
    url_poster: 
    template: {
                    name: award_winner,
                    num: "K",
                    type: "movie,tv_movie",
                    event.winning: "choice",
                    language: "en"
                    }
    limit: 1000
    
  "Spirit Awards Winners":
    summary: "A collection of Spirit Awards Winners"
    url_poster: 
    template: {
                    name: award_winner,
                    num: "L",
                    type: "movie,tv_movie",
                    event.winning: "spirit",
                    language: "en"
                    }
    limit: 1000
    
  "Razzie Winners":
    summary: "A collection of Razzie Winners"
    url_poster: 
    template: {
                    name: award_winner,
                    num: "M",
                    type: "movie,tv_movie",
                    event.winning: "razzie",
                    language: "en"
                    }
    limit: 1000
```

**Comment by heylookltsme** [comment]
Ah many thanks!

**Comment by heylookltsme** [comment]
Is there a plan to update the default `oscars` config in pmm?

**Comment by JDIacobbo** [comment]
> This is due to using an old version of plexapi. Update your dependencies from requirements.txt.

I swore I installed the requirements several times prior to running this but that did indeed fix the issue. Thanks!

**Comment by chazlarson** [comment]
> Is there a plan to update the default `oscars` config in pmm?

Of course; they won't just remain broken.

**Comment by heylookltsme** [comment]
Haha you never know 🙃 

Many thanks!!

**Comment by JDIacobbo** [comment]
So I have been able to get this to work by editing `oscars.yml` and `templates.yml`. I'm not sure if this is the "proper" way to do this but if this looks good I can fork and submit a PR.

Here's what I did.

For the Best Picture and Best Director I updated the `oscars.yml` to the following:

```
collections:
  Oscars Best Picture Winners:
    variables:
      key: best_picture
    template:
      - name: shared
        sort: Oscars !1
        allowed_libraries: movie
        image: award/oscars/best_picture_winner
        translation_key: oscars_picture
      - name: arr
      - name: custom
    imdb_search:
      type: movie
      limit: 100
      event.winning: oscar_picture
    collection_order: release
    sync_mode: sync

  Oscars Best Director Winners:
    variables:
      key: best_director
    template:
      - name: shared
        sort: Oscars !2
        allowed_libraries: movie
        image: award/oscars/best_director_winner
        translation_key: oscars_director
      - name: arr
      - name: custom
    imdb_search:
      type: movie
      limit: 100
      event.winning: oscar_director
    collection_order: release
    sync_mode: sync
```

For the Winners by Year I added the following to `templates.yml`:
```
  imdb_search: 
    optional:
      - imdb_search_limit
      - imdb_search_type
      - imdb_search_event_winning
      - imdb_search_relase_before
      - imdb_search_release_after
    imdb_search:
      limit: <<imdb_search_limit>>
      type: <<imdb_search_type>>
      event.winning: <<imdb_search_event_winning>>
      release.before: <<imdb_search_relase_before>>
      release.after: <<imdb_search_release_after>>
```

And updated the following in `oscars.yml`:
```
dynamic_collections:
  Oscars Winners Awards:
    type: number
    sync: true
    data:
      starting: current_year-6
      ending: current_year-1
    title_format: Oscars Winners <<key_name>>
    template:
      - use_year_collections
      - imdb_search
      - shared
      - arr
      - custom
    template_variables:
      imdb_sort:
        default: moviemeter,asc
      allowed_libraries:
        default: movie
      image:
        default: award/oscars/winner/<<key>>
      translation_key:
        default: oscars_year
      dynamic:
        default: true
      collection_order:
        default: release
      sync_mode:
        default: sync
      imdb_search_type: 
        default: movie
      imdb_search_limit: 
        default: 100
      imdb_search_event_winning: 
        default: oscar
      imdb_search_release_after: 
        default: <<key-1>>-01-01
      imdb_search_relase_before: 
        default: <<key-1>>-12-31
```

I'd need to add the rest of the `imdb_search` variables to `templates.yml` but as far as I can tell it looks like this should work. If anyone more knowledgeable with this project could let me know if this solutions works can submit it for merge.
