### ISSUE TITLE
Playlists: Playlist Poster does not sync to home users

### ISSUE THREAD

**Issue by RobLaw0304** [Kometa-Team/Kometa#1773]
### Version Number

4.15.2

### What branch are you on?

master

### Describe the Bug

I have added the following to my config.yml
`playlist_files:
  - file: config/metadata/tv_collections.yml
  - pmm: playlist
    template_variables:
      libraries: "Movies,TV"`
It syncs the playlist to all my users. When i view the playlist in my plex web, the poster shows.  If i change to another home user, the playlist appears but the poster is not there.  This is occurring with default playlists as well as custom playlists.

### Relevant Collection/Overlay/Playlist Definition

```yml
playlist_files:
  - file: config/metadata/tv_collections.yml
  - pmm: playlist
    template_variables:
      libraries: "Movies,TV"
```
