### ISSUE TITLE
Issue while trying to create Streaming Collections 

### ISSUE THREAD

**Issue by aay-kay** [Kometa-Team/Kometa#1786]
### Version Number

1.19.1

### What branch are you on?

master

### Describe the Bug

I am getting this error while trying to run the streaming command.

All I am using is pmm: streaming. The code I am using is from the seasonal wiki.

I am getting similar error for all the other streaming services.

### Relevant Collection/Overlay/Playlist Definition

```yml
metadata_path:
    - pmm: streaming
      template_variables:
        region: us
        use_separator: false
        sep_style: stb
        visible_library_disney: true
        visible_home_disney: true
        visible_shared_disney: true
        sonarr_add_missing_hulu: true
        radarr_add_missing_amazon: true
        sort_by: random
```

### Logs

https://gist.github.com/aay-kay/d3a5ec6e2c92e4314ef4a65b71af3ae4
