### ISSUE TITLE
PMM_RUN_FILE causes error if overlays not included

### ISSUE THREAD

**Issue by MrMeeb** [Kometa-Team/Kometa#1790]
### Version Number

1.19.1-nightly57

### What branch are you on?

nightly

### Describe the Bug

I have multiple collection yamls that I want to run at different intervals, since one takes a long time to complete and doesn't need to update daily. I used to use `PMM_RUN_METADATA_FILES` for this, but that appears to have been replaced with `PMM_RUN_FILE` instead. When using the new environment variable, if I only reference my collections file, I get an error related to overlays. To resolve this issue, I either need to remove the `overlay_files` attribute from my library's settings, or add the overlay file to the `PMM_RUN_FILE` list. 
- Not working: `PMM_RUN_FILE="collections.yml"`
- Working: `PMM_RUN_FILE="collections.yml|overlays.yml"`

While I have no real issue with having to include overlays, since mine are quite simple and take very little time, they are not related to anything the collections do, and this is not expected behaviour. I would expect that trying to run a collections file should have no bearing on whether overlays need to be included. This also seems to go against the warning in the docs stating to not include overlays in this command.

### Relevant Collection/Overlay/Playlist Definition

```yml
# config/movies/overlays.yml
overlays:
  4K:
    overlay:
      name: 4klabel
      file: config/overlays/4klabel.png
      horizontal_offset: 20
      horizontal_align: left
      vertical_offset: 10
      vertical_align: bottom
    plex_search:
      all:
        resolution: 4K
  leavingsoon:
    overlay:
      name: leavingSoonLabel
      file: config/overlays/leavingSoonLabel.png
      horizontal_offset: 20
      horizontal_align: left
      vertical_offset: 10
      vertical_align: top
    plex_search:
      all:
        collection: "Leaving Soon"

# config/movies/collections.yml
templates:
  Collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    url_poster: <<poster>>
    sync_mode: sync
    collection_order: release
  Trakt:
    trakt_list_details: <<list>>
    url_poster: <<poster>>
    sync_mode: sync
    collection_order: custom

collections:
  "The Star Wars Collection":
    template: {name: Collection, collection: 10, movie: "348350, 330459", poster: https://theposterdb.com/api/assets/4448} 
    sort_title: "02-Collection"
    summary: "A Long Time Ago in a Galaxy Far Far Away..."
    collection_mode: show_items
    show_missing: true
    collection_order: alpha
  "Marvel Cinematic Universe":
    template: {name: Trakt, list: "https://trakt.tv/users/tetharion/lists/marvel-cinematic-universe", poster: https://theposterdb.com/api/assets/345}
    sort_title: "01-Collection"
    summary: "Perfectly balanced, as all things should be."
    collection_mode: show_items
    show_missing: true
    collection_order: release
    radarr_add_missing: true
    radarr_search: true
  "The Studio Ghibli Collection":
    template: {name: Trakt, list: "https://trakt.tv/users/draackje/lists/studio-ghibli-feature-films", poster: https://theposterdb.com/api/assets/325047}
    sort_title: "04-Collection"
    summary: "A selection of charming Japanese animated films from Studio Ghibli."
    collection_mode: show_items
    show_missing: false
    collection_order: release
```

### Logs

https://gist.github.com/MrMeeb/f85b07b62a8d78f7b6a964ab22637211
