### ISSUE TITLE
File Error: Default does not exist seasonal.yml

### ISSUE THREAD

**Issue by bruvv** [Kometa-Team/Kometa#1827]
### Version Number

v1.20.0

### What branch are you on?

master

### Describe the Bug

According to the wiki, to enable season collections I do:

```yaml
libraries:
  Movies:
    collection_files:
      - pmm: seasonal
```

But when I do I get the error:
`File Error: Default does not exist seasonal.yml`

### Config
```yaml
libraries:
  Movies:
    collection_files:
      - pmm: basic
      - pmm: genre
      - pmm: universe
      - pmm: based
      - pmm: oscars
      # - pmm: streaming
      - pmm: seasonal
      - pmm: decade
      - pmm: imdb
        template_variables:
          use_lowest: false
    operations:
      delete_collections:
        configured: false
        managed: true
  TV Shows:
    collection_files:
    - pmm: basic
    - pmm: genre
    - pmm: universe
    - pmm: based
    - pmm: oscars
    # - pmm: streaming
    - pmm: seasonal
    - pmm: decade
    - pmm: imdb
      template_variables:
        use_lowest: false
```

### Logs
```
|====================================================================================================|
|                           Loading Collection File PMM Default: seasonal                            |
|====================================================================================================|
|                                                                                                    |
| File Error: Default does not exist seasonal.yml                                                    |
| Collection File Failed To Load                                                                     |
```

**Comment by YozoraXCII** [comment]
i cannot reproduce this on 1.20, can you ensure your requirements are installed?:

```yaml
libraries:
  Movies:
    collection_files:
      - pmm: seasonal
```
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/f7c442a8-0a54-4240-a9dd-4b1d86109d98)
