### ISSUE TITLE
Duplicate run_order item

### ISSUE THREAD

**Issue by Droppisalt** [Kometa-Team/Kometa#1829]
### What is the improvement or update to the Wiki you wish to see?

This has 2 "operations":
```yaml
settings:
  run_order: 
  - operations
  - metadata
  - collections
  - operations
```
Should be something like:
```yaml
settings:
  run_order: 
  - operations
  - metadata
  - collections
  - overlays
```

### Does the docs page already exist? Please link to it.

https://metamanager.wiki/en/nightly/config/settings/#example-library-level-settings
