### ISSUE TITLE
Something is not quite right with IMDB...

### ISSUE THREAD

**Issue by m33ts4k0z** [Kometa-Team/Kometa#1835]
### Version Number

1.20.0-nightly9

### What branch are you on?

nightly

### Describe the Bug

Hello and thanks for this great script.

I installed it yesterday on my Unraid server and I already love it but I need to fine-tune it a bit more 😁.

So my issue is that I have set up a collection called Romance and I use IMDB to search for movies containing all of these genres: romance, mystery, drama

However the search returns movies containing only 1 of these genres while I dont use the `genre.any` parameter.
The funny thing is that using the [IMDB search on the website](https://www.imdb.com/search) directly, it returns also the same (wrong) results 😁.

Maybe there is a way to do that anyway? I attach my config and my log file.

Thanks in advance for any help 😊

### Relevant Collection/Overlay/Playlist Definition

```yml
// config.yml
libraries:                       # This is called out once within the config.yml file
  Filmer:                        # These are names of libraries in your Plex
    collection_files:
      # see the wiki for how to use local files, folders, URLs, or files from git
      - file: config/romance.yml

// romance.yml
collections:
  Romance:
    radarr_add_missing: true
    sync_mode: sync
    collection_order: custom
    imdb_search:
      genre: romance, drama, mystery
      type: movie
      release.after: 2000-01-01
      rating.gte: 6
      limit: 20
```

### Logs

https://gist.github.com/m33ts4k0z/7848fc70f15f9198bdc0fb319b407226

**Comment by YozoraXCII** [comment]
Try this maybe?

```yml
collections:
  Romance:
    radarr_add_missing: true
    sync_mode: sync
    collection_order: custom
    imdb_search:
      genre.any: 
        - romance
        - drama
        - mystery
      type: movie
      release.after: 2000-01-01
      rating.gte: 6
      limit: 20
```     

Ultimately we rely on IMDb, if their data is "wrong" then there's no course-corrective action we can take.
