### ISSUE TITLE
Collection Error: radarr_taglist attribute is blank

### ISSUE THREAD

**Issue by dzirkler** [Kometa-Team/Kometa#1842]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

[Documentation ](https://metamanager.wiki/en/latest/files/builders/radarr/#radarr-taglist) shows that we should be able to do this:
```collections:
  Radarr Movies Without Tags:
    radarr_taglist:
```

However, it seems to not pass validation and therefore never works:
```Collection Error: radarr_taglist attribute is blank```

I'm trying to use PMM to set and clear a plex label from a radarr/sonarr tag without creating collections to do so. Since there's no collection created, I can't use `sync_mode: sync`, and was just going to run two entries:
1 - Clear label from all items without it in radarr/sonarr
2 - Apply label from all items with it in radarr/sonarr

Here's the relevant config:
```
    collections:
      "Clear Radarr Tag to Plex Label":
        build_collection: false
        sync_mode: append
        radarr_taglist: 
        item_label.remove:
          - My Plex Label
      "Set Radarr Tag to Plex Label":
        build_collection: false
        sync_mode: append
        radarr_taglist: my-radarr-tag
        item_label:
          - My Plex Label
```

I've also tried `radarr_taglist: ~` which has the same error. 

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
      "Clear Radarr Tag to Plex Label":
        build_collection: false
        sync_mode: append
        radarr_taglist: 
        item_label.remove:
          - My Plex Label
      "Set Radarr Tag to Plex Label":
        build_collection: false
        sync_mode: append
        radarr_taglist: my-radarr-tag
        item_label:
          - My Plex Label
```
