### ISSUE TITLE
metadata_backup is not backing up multiple Editions of movies

### ISSUE THREAD

**Issue by KellyNewman87** [Kometa-Team/Kometa#1856]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

The following will output only one Edition of a multi-Edition movie.

```
    operations:
      metadata_backup:
        path: config/Movie_Backup.yml
        sync_tags: true
```
For example "That Thing You Do!" has two Editions (of I have both in Plex): "Theatrical Cut" and "Extended Cut." In the outputted "Movie_Backup.yml" file I only see this ONE result for the movie, which is the "Extended Cut":

```
  That Thing You Do! (1996):
    title: That Thing You Do!
    year: 1996
    summary: THIS EXTENDED CUT IS FOR MORE MATURE AUDIENCES 18+ (THE THEATRICAL CUT IS 14+) - A local Pennsylvania band scores a one-hit wonder in 1964 and rides the star-making machinery as long as they can, with lots of help from their manager.
    label.sync: Age 18
```
