### ISSUE TITLE
Invalid link in PMM Unraid Template

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#1862]
### Version Number

1.20

### What branch are you on?

master

### Describe the Bug

Link in app description is pointing to old wiki thus giving users a 404 page not found.

### Relevant Collection/Overlay/Playlist Definition

```yml
Plex Meta Manager is an open source Python 3 project that has been designed to ease the creation and maintenance of metadata, collections, and playlists within a Plex Media Server. The script is designed to be run continuously and be able to update information based on sources outside your plex environment. Plex Meta Manager supports Movie/TV/Music libraries and Playlists.

Unraid Setup Guide: https://metamanager.wiki/en/latest/home/guides/unraid.html

Additional Requirements:
None Listed


Should be:
Plex Meta Manager is an open source Python 3 project that has been designed to ease the creation and maintenance of metadata, collections, and playlists within a Plex Media Server. The script is designed to be run continuously and be able to update information based on sources outside your plex environment. Plex Meta Manager supports Movie/TV/Music libraries and Playlists.

Unraid Setup Guide: 
https://metamanager.wiki/en/latest/pmm/install/unraid/

Additional Requirements:
None Listed
```
