### ISSUE TITLE
[Playlist] Plex Meta Manager cannot find Home Admin user in Plex

### ISSUE THREAD

**Issue by benbou8231** [Kometa-Team/Kometa#1877]
### Version Number

1.20.0-nightly29

### What branch are you on?

nightly

### Describe the Bug

**Description:**

When trying to sync playlists to a Home Admin user in Plex, Plex Meta Manager fails with the error message: "Playlist Error: User: [user name] not found in plex". This happens even though the user name is correct and the user is associated with some playlists in Plex.

**Steps to reproduce:**

1. Create a config file for Plex Meta Manager with the following settings:

```
playlist_files:
- pmm: playlist
  template_variables:
    libraries: [library name]
    sync_to_users: [user name]
```

2. Replace [library name] with the name of your Plex library and [user name] with the name of your Home Admin user in Plex.
3. Run Plex Meta Manager with the config file.
4. Observe the error message in the log.

**Expected behaviors:**

The end user should be able to explicitly user their admin user in sync_to_users and exclude_users.
