### ISSUE TITLE
[Playlist] Synced playlists missing original summary

### ISSUE THREAD

**Issue by benbou8231** [Kometa-Team/Kometa#1882]
### Version Number

1.20.0-nightly29

### What branch are you on?

nightly

### Describe the Bug

**Description:**

When using the `sync_to_users` template variable under `- pmm: playlist`, the playlists created and synced to the specified users lack the original playlist summary.

**Steps to Reproduce:**

1. Set the following configuration:

```
playlist_files:
- pmm: playlist
  template_variables:
    libraries: [library name]
    sync_to_users: Bob, Ben
```

2. Run the program.
3. Check the synced playlists for the non-admin users listed in `sync_to_users`.

**Expected Behavior:**

The synced playlists should retain the original playlist summary.

**Actual Behavior:**

The synced playlists have an empty summary.
