### ISSUE TITLE
Dynamic collection type: actor is passing name as all variables

### ISSUE THREAD

**Issue by pterisaur** [Kometa-Team/Kometa#1887]
### Version Number

1.20.0 (Docker)

### What branch are you on?

master

### Describe the Bug

If I build dynamic collections using `type: actor` with a template that includes `tmdb_actor_details: <<value>>`...

I can see also that `<<value>>`, `<<key>>`, and `<<key_name>>` are all the name in the log:
```
[{'value': ['Dan Aykroyd'], 'actor': ['Dan Aykroyd'], 'key_name': 'Dan Aykroyd', 'key': 'Dan Aykroyd', 'name': 'dynamic_actor'}] 
```

I get a Regex error for each actor collection: 
```
Regex Error: Failed to parse TMDb Person ID from Dan Aykroyd
```

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  dynamic_actor:
    collection_mode: hide
    cache_builders: 1
    tmdb_actor_details: <<value>>
    plex_search:
      all:
        genre.not: Guest Stars
        actor: <<collection_name>>
    smart_label: release.desc
    sort_title: 09 <<collection_name>>
    url_poster: https://raw.githubusercontent.com/pterisaur/Plex-Meta-Manager-Images/main/Collections/People/<<collection_name_encoded>>%20(Acting).png

dynamic_collections:

  Top Actors:
    template: dynamic_actor
    type: actor
    data:
      depth: 10
      minimum: 3
      limit: 50
```

### Logs

https://gist.github.com/pterisaur/8a92b05f6841b7c756626ab01da80bca

**Comment by YozoraXCII** [comment]
So this is expected behaviour.

The default template on the wiki searches Plex for "Actor is Dan Aykroyd"

```
default_template:
  plex_search:
    any:
      actor: <<value>>
```

You are instead using `tmdb_actor_details: Dan Aykroyd` which is not valid - `tmdb_actor_details` expects the TMDb ID of the person, not the name.
