### ISSUE TITLE
[Nightly] `mass_genre_update` passes anidb.weights as strings

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#1902]
### Version Number

1.20-nightly30

### What branch are you on?

nightly

### Describe the Bug

This bug was introduced in nightly20

the anidb.weights is passed as a string and applied to all items in the library:

```yaml
libraries:
  Movies:
    operations:
      mass_genre_update:
        - anidb_1_0
```

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/a7fdcd28-3d8c-4e9b-80c4-fa1c698035a5)

Discord report: https://discord.com/channels/822460010649878528/1203436991845244928
