### ISSUE TITLE
[Nightly] `mass_episode_***_rating_update` operations do not work

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#1903]
### Version Number

nightly34

### What branch are you on?

nightly

### Describe the Bug

This bug was introduced in nightly 20

all `mass_episode_***_rating_update` operations are no longer functional and return a `No xxx Rating Found`, even when using `remove` and `reset` or manually setting a fallback rating.

Code and `-lr` log attached - no IMDb or TMDb traffic appears to be happening.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  TV:
    operations:
      mass_episode_audience_rating_update: imdb
      mass_episode_critic_rating_update: tmdb
      mass_episode_user_rating_update:
        - "9"
```

### Logs

https://gist.github.com/YozoraXCII/084dfe327c1d232e5092764cfefa745d
