### ISSUE TITLE
Defaults Collections with `<<` `>>` variables not picked up by `delete_collections` operation

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#1904]
### Version Number

nightly34

### What branch are you on?

nightly

### Describe the Bug

There is an issue with the `delete_collections` operation where collections which contain `<<``>>` variables are not being seen as configured.

In this example, PMM has the collection as `"Netflix Top <<limit>>` and the final name of the built collection is `Netflix Top 10`. 
When I then try to run a `delete_collections` operation the name is not matching because it is searching for `Netflix Top <<limit>>` as a string, which is not matched, so my actual `Netflix Top 10` appears to be unconfigured.

This is repeatable across most (but not all) collections with variables in the name.

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/11d991ed-39c2-4e30-bf46-c73de8c40f29)

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/1df318fb-dd42-4f79-b134-142b02b95073)

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/008d0c89-d04b-428d-8c63-3aefc898d599)

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Movies:
    collection_files:
      - pmm: streaming
      - pmm: content_rating_us
    operations:
      delete_collections:
        managed: true
        configured: true
        less: 99999
```
