### ISSUE TITLE
Playlists cannot add items to both Radarr and Sonarr in the same run

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#1910]
### Version Number

1.20.0

### What branch are you on?

nightly

### Describe the Bug

There is an issue with playlists whereby only one of Sonarr or Radarr will add existing/missing items, depending if you specify a Movie or TV Show library first or second within the `libraries` attribute.

In this example, the second library type is a show so `sonarr_add_missing` does not run.

Trace logs and Playlist definition included.

### Relevant Collection/Overlay/Playlist Definition

```yml
playlists:
  MCU Movies:
    sync_mode: sync
    libraries: Movies, TV Shows
    trakt_list: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe?sort=rank,asc
    summary: Marvel Cinematic Universe Movies In Chronological Order
    radarr_add_missing: true
    sonarr_add_missing: true
```

### Logs

https://gist.github.com/YozoraXCII/e72c7889b196f89324017d08c0fb1acf
