### ISSUE TITLE
metadata_backup.add_blank_entries doesn't use new matching strategy

### ISSUE THREAD

**Issue by ImDevinC** [Kometa-Team/Kometa#1911]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

For movies that have the same name, but different year, IE: Mean Girls (2004) and Mean Girls (2024), if you use the `operations.metadata_backup.add_blank_entries: true` option, the movies are stored in the backup file without the proper match details.

Using this config:
```yaml
settings:
  download_url_assets: true
plex:
  url: http://plex.mediaserver:32400
  token: <<PLEX_SECRET_TOKEN>>
tmdb:
  apikey: <<TMDB_TOKEN>>
  language: en
libraries:
  Movies:
    metadata_files:
      - file: /config/movies.yml
    operations:
      metadata_backup:
        path: /assets/movies-backup.yml
        add_blank_entries: true
```

When you run PMM you get the following backup file
```yaml
metadata:
  Mean Girls (2004):
    title: Mean Girls
    year: 2004
  Mean Girls (2024):
    title: Mean Girls
    year: 2024
```

I would expect this backup file to be in the new match format of
```yaml
metadata:
  Mean Girls (2004):
    match:
      title: Mean Girls
      year: 2004
  Mean Girls (2024):
    match:
      title: Mean Girls
      year: 2024
```
