### ISSUE TITLE
<<key>>.png linking to key # instead of key name when updating from latest (stable) to nightly

### ISSUE THREAD

**Issue by SpartacusIam** [Kometa-Team/Kometa#1946]
### Version Number

1.20.0-nightly44

### What branch are you on?

develop

### Describe the Bug

When updating from latest branch to nightly, my custom streaming overlays break.  Log shows it's mapping <<key>>.png to the key number instead of the key name.  I've tried changing <<key>>.png to <<key_name>>.png to no availe.

`Overlay Error: Overlay Image not found at: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/streaming-top-left/1759.png`

## Relevant Collection/Overlay/Playlist Definition

```yml
overlay_files:
    - pmm: streaming
      template_variables:
        horizontal_align: left
        horizontal_offset: 0
        vertical_offset: 0
        vertical_align: top
        back_width: 1000
        back_height: 1500
        url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/streaming-top-left/<<key>>.png
        back_color: 00
```

### Logs

https://gist.github.com/SpartacusIam/546e6a42963a4f368612c721ba569c84
