### ISSUE TITLE
PMM Commonsense - all movies and shows rated to default NR

### ISSUE THREAD

**Issue by friimaind** [Kometa-Team/Kometa#1958]
### Version Number

1.20.0

### What branch are you on?

master

### Describe the Bug

From a certain moment on I realized that all films and TV series are labeled NR classification.

I tried, with no luck, setting mass_content_rating_update to "reset" and restoring ti to mdb_commonsense.

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/16322003/e81882f4-27ad-4477-9b85-4ac4da76810b)
![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/16322003/1d3f4a72-5e39-4040-b5a5-bd1e4d91a0d0)

### Relevant Collection/Overlay/Playlist Definition

```yml
## This file is a template remove the .template to use the file

libraries:                       # This is called out once within the config.yml file
  Film:                        # These are names of libraries in your Plex
    overlay_files:
      - pmm: runtimes    
        template_variables:
          final_name: text(Durata <<runtimeH>>h <<runtimeM>>m)
      - pmm: resolution
      - pmm: commonsense
      - pmm: ratings
        template_variables:
          rating1: critic
          rating2: audience
          rating3: user
          rating1_image: imdb
          rating2_image: rt_popcorn
          rating3_image: tmdb
    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      mass_content_rating_update: mdb_commonsense
  Programmi TV:
    overlay_files:
      - pmm: runtimes
        template_variables:
          final_name: text(Durata <<runtimeH>>h <<runtimeM>>m)
      - pmm: runtimes
        template_variables:
          builder_level: episode
          final_name: text(Durata <<runtimeH>>h <<runtimeM>>m)
      - pmm: resolution
      - pmm: resolution
        template_variables:
          builder_level: season
      - pmm: resolution
        template_variables:
          builder_level: episode
      - pmm: episode_info
      - pmm: commonsense
      - pmm: commonsense
        template_variables:
          builder_level: season
      - pmm: commonsense
        template_variables:
          builder_level: episode
      - pmm: ratings
        template_variables:
          rating1: critic
          rating2: audience
          rating3: user
          rating1_image: imdb
          rating2_image: rt_popcorn
          rating3_image: tmdb
      - pmm: ratings
        template_variables:
          builder_level: episode
          rating1: critic
          rating2: audience
          rating1_image: imdb
          rating2_image: tmdb
    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb
      mass_content_rating_update: mdb_commonsense
playlist_files:
- pmm: playlist                  # This is a file within PMM's defaults folder
  template_variables:
    libraries: Film, Programmi TV     # list of libraries that you want the PMM Defaults playlists to look at
  # see the wiki for how to use local files, folders, URLs, or files from git
settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: it
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
webhooks:                        # Can be individually specified per library as well
  error:
  version:
  run_start:
  run_end:
  changes:
  delete:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://xxx:32400
  token: xxx
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:                            # REQUIRED for the script to run
  apikey: xxx
  language: it
  cache_expiration: 60
  region:
```
