### ISSUE TITLE
Backdrop overlay does not respect vertical_position.

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#1960]
### Version Number

1.20.0-nightly54

### What branch are you on?

nightly

### Describe the Bug

wiki contains this example:
```yaml
overlays:
  backdrop:
    overlay:
      name: backdrop
      back_color: "#00000099"
      back_height: 100
      vertical_position: top
    plex_all: true
```
which implies that `vertical_position` can be used.  It's not documented, but is in the example.

However, this:
```yaml
overlays:
  backdrop:
    overlay:
      name: backdrop
      back_color: "#00000099"
      back_height: 100
      vertical_position: bottom
    plex_all: true
```
still puts the overlay at the top of the image:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/07813686-3241-497d-9643-349466965489)

[My test run had the height set to 400, not 100]

### Relevant Collection/Overlay/Playlist Definition

```yml
overlays:
  backdrop:
    overlay:
      name: backdrop
      back_color: "#00000099"
      back_height: 100
      vertical_position: bottom
    plex_all: true
```

### Logs

https://gist.github.com/chazlarson/0d4c9898256a06f524e3c8fa983e4036
