### ISSUE TITLE
`download_url_assets` causes `url_background` to upload as poster in Plex

### ISSUE THREAD

**Issue by YozoraXCII** [Kometa-Team/Kometa#1965]
### Version Number

1.21

### What branch are you on?

nightly

### Describe the Bug

When `download_url_assets` is set to true, `url_background` is downloaded as `background.ext` but when it uploads to Plex it is uploading as a poster not a background.

I have been able to reproduce this consistently.

This behaviour does not appear when `download_url_assets` is set to false and the local assets already exist.

`-lr` log attached which shows it being uploaded as a poster.

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/96ccfd73-63b6-47b1-903f-74e0d526d33f)

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/ce7adc41-5d95-4b2a-aa95-775f8246fbc9)

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/96386153/2bffa916-110f-4c16-9252-da0f3ca2affd)

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
  IMDb Top 250 With URL Assets:
    imdb_chart: top_movies
    url_background: https://i.imgur.com/juAQnOG.jpg
    sync_mode: sync
    collection_mode: default
    collection_order: custom
```

### Logs

https://gist.github.com/YozoraXCII/ddedf5cba8f2c0eaf99bdbdaea85e5a3
