### ISSUE TITLE
pmm: streaming not recognizing Prime when region set to CA

### ISSUE THREAD

**Issue by vincentleclerc** [Kometa-Team/Kometa#1977]
### Version Number

1.21.0

### What branch are you on?

master

### Describe the Bug

**config.yml**

```
libraries:                       
  '[EN/FR] Movies':              
    overlay_files:
      - pmm: streaming
        template_variables:
          region: CA
          vertical_offset: 10%
          vertical_align: bottom
```

PMM won't find any media to label as "Prime". Prime Video is available in Canada and shouldn't be ignored. `use_prime: true` doesn't have any effect either. Setting the region to US mitigate the problem as my medias will be labeled with "Prime" but "Crave" will be ignored.. forcing crave with `use_crave: true` with `region: US` doesn't work either. Any viable solution for canadians that wants crave AND prime labeled correctly?
