### ISSUE TITLE
Does PMM really not support Season/Episode numbers with more than two digits?

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#1981]
### Discussed in https://github.com/meisnate12/Plex-Meta-Manager/discussions/1975

<div type='discussions-op-text'>

<sup>Originally posted by **OttoWerse** April  9, 2024</sup>
I am trying to apply episode Artwort using PMM, but no matter what I do, it just seems to be unable to do so. 
First I enabled "create_asset_folders" to know exactly where to put my images. 
I named my image "S2024E099.png" and put it in the PMM created folder "config\assets\Doug DeMuro - Other" 
Now I want it to be applied to the corresponding episode "Doug DeMuro - Other - S2024E099.mp4" in my Plex folder structure under "Plex\YouTube\Doug DeMuro - Other\Season 2024" 
However, running PMM I only get a message "No Item Edits". 

Then I shortened the Season and Episode bit in all file names to "S24E99" (and let Plex re-scan the file, of course). 
Now PMM was immediately able to apply my asset to the episode. 
However, this is a non-solution to my original problem, as I do actually need the extra digits, I cannot just shorten all my filenames. 

So, what else do I need to set or consider before updating episode assets for 4-digit seasons and/or 3-digit episodes can work? 
Or is this just really not supported by PMM at all? If so, why? 

My Config looks like this: 
```
libraries:
  YouTube:
    operations:
      assets_for_all: true
    settings:
      show_missing_assets: false
    collection_files:
    - file: config/youtube.yml
    reapply_overlays: false

settings:
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  cache: true
  cache_expiration: 60
  asset_directory: 
  - config/assets
  create_asset_folders: true
  asset_folders: true
  asset_depth: 0
  prioritize_assets: true
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: true
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users:
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
```</div>

**Comment by chazlarson** [comment]
PMM Is basing the asset search on the season and episode numbers reported by Plex, nothing to do with the file name.

Given this episode:

![Screenshot 2024-04-15 at 8 47 33 AM](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/89ae0992-9c2f-4a07-91b7-20d046765d21)

found at filename:
```
/mnt/local/Testing/Some-Shows/EastEnders (1985) {tvdb-71753}/Season 39/EastEnders (1985) - 2023-12-28 - 28+12+2023 - [ WEBDL-1080p h264 AAC 2.0 ]-iPLAYER.mp4
```
Note that filename contains no season or episode info at all.

I created this asset in `config/assets`:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/8f92a0bf-52c3-4c3d-a08c-15d473be8e4d)

Note it has a three-digit episode number.

Then ran this config:
```
libraries:
  Some-Shows:
    operations:
      assets_for_all: true

settings:
  asset_directory: config/assets
  asset_folders: true
  prioritize_assets: true
  create_asset_folders: true
  asset_depth: 0
  dimensional_asset_rename: true
  download_url_assets: true
  show_missing_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: false

```

With this result:

![image](https://github.com/meisnate12/Plex-Meta-Manager/assets/3865541/60d537ca-f5a4-4f09-aaee-d8394aa604d3)
