### ISSUE TITLE
Plex Artwork Language

### ISSUE THREAD

**Issue by to4ko** [Kometa-Team/Kometa#2013]
### Version Number

2.0.0

### What branch are you on?

master

### Describe the Bug

All Plex artworks get redownloaded with EN language. 

![image](https://github.com/Kometa-Team/Kometa/assets/45161980/095a8e83-40c6-4e4e-91db-f7e22526ca34)

While in Plex its selected to prefer language selected for library
![image](https://github.com/Kometa-Team/Kometa/assets/45161980/00cc9201-dcab-4134-9eb8-dbc32e2599cc)

While i was using pmm it was ok - artwork were downloaded in local language. 

Is it possible to specify required langusge in Kometa config?

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Кино:
    remove_overlays: true
    reapply_overlay: true
    overlay_files:
      - default: resolution                                                    # 1, 4
      - default: audio_codec                                                   # 2
      - default: mediastinger                                                  # 3
      - default: ratings                                                       # 5, 6, 7
        template_variables:
          rating1: user                                                    # 5 as this is user and mass_user_rating_update: mdb_tomatoes
          rating1_image: rt_tomato                                         # 5 as this is user and mass_user_rating_update: mdb_tomatoes
          rating1_font: config/custom_fonts/Adlib.ttf                      # 5 local font accessible to Kometa
          rating1_font_size: 63                                            # 5 adjusted font size to fit rating

          rating2: critic                                                  # 6 as this is critic and mass_critic_rating_update: imdb
          rating2_image: imdb                                              # 6 as this is critic and mass_critic_rating_update: imdb
          rating2_font: config/custom_fonts/Impact.ttf                     # 6 local font accessible to Kometa
          rating2_font_size: 70                                            # 6 adjusted font size to fit rating

          rating3: audience                                                # 7 as this is audience and mass_audience_rating_update: tmdb
          rating3_image: tmdb                                              # 7 as this is audience and mass_audience_rating_update: tmdb
          rating3_font: config/custom_fonts/Avenir_95_Black.ttf            # 7 local font accessible to Kometa
          rating3_font_size: 70                                            # 7 adjusted font size to fit rating

          horizontal_position: right                                       # the set of ratings is on the right of the poster
      - default: streaming                                                     # 8
      - default: video_format                                                  # 9
      - default: language_count                                                # 10
      - default: ribbon                                                        # 11, 12 Bottom right sash is used by more than one overlay so a weight for priority can be applied 
    operations:
      mass_user_rating_update: mdb_tomatoes                              # 5 This operation will update the user rating in plex with Rotten Tomatoes ratings information gathered through mdblist.com (mdblist config required)
      mass_critic_rating_update: imdb                                    # 6 This operation will update the critic rating in plex with IMDb ratings information
      mass_audience_rating_update: tmdb                                  # 7 This operation will update the audience rating in plex with TMDb ratings information
      delete_collections:
        configured: false
        managed: true
      mass_genre_update: tmdb                       # Update all genres from tmdb
      mass_content_rating_update: mdb_commonsense   # Changes Content Rating to "1", "2" etc. to specify appropriate age
      mass_originally_available_update: tmdb        # Update all original available date from tmdb
      mass_imdb_parental_labels: none               # Apply all Parental Labels with a value of None, Mild, Moderate, or Severe to match IMDb parental guide
      # mass_poster_update: tmdb                      # Resets posters to tmdb, plex, locked, unlock which is useful to remove all overlays when running with -r -op
```
