### ISSUE TITLE
Collection file fail to load

### ISSUE THREAD

**Issue by ayostepht** [Kometa-Team/Kometa#2029]
### Version Number

2.0.1

### What branch are you on?

master

### Describe the Bug

Been running PMM/Kometa for a while with no issues. Upgraded to 2.0 and manually ran it via "python kometa.py -r" in CLI of Unraid and after a few tweaks to transition to new updates (pmm--> default) it executed flawlessly. However, since then, on the automatic nightly run, and if I manually trigger it now as well, I get an error that my collection files cannot be found. I have verified that collection files are located correctly at /Kometa/config/movies/ and /Kometa/config/tv, and /mnt/user/appdata/Kometa/config is mapped to /config in Unraid container setup.

<img width="245" alt="Screen Shot 2024-05-05 at 12 29 02 PM" src="https://github.com/Kometa-Team/Kometa/assets/122751714/ce7753b3-77c9-48e1-8091-5cd3faf715b2">

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Movies:
    collection_files:
    - file: config/movies/00_seasonal.yml
    - file: config/movies/01_awards.yml
    - file: config/movies/02_charts.yml
    - file: config/movies/03_Categories.yml
    - file: config/movies/04_Genres.yml

  TV Shows:
    collection_files:
    - default: network
    - file: config/TV/01_awards.yml
```

### Logs

https://gist.github.com/ayostepht/33031292b96355ddd67bed0a30731bda
