### ISSUE TITLE
default: actor taking a long time to load every run even with schedule: monthy(1) is set

### ISSUE THREAD

**Issue by nairbd** [Kometa-Team/Kometa#2036]
### Version Number

2.0.1 and 2.0.1-nightly5

### What branch are you on?

master

### Describe the Bug

I understand depth is an expensive operation, so to combat this I tried to schedule it for once a month. What I'm finding is that every run it's taking 20 mins just to go through all of the actors, even with the schedule set. I've tried on 2.0.1 and 2.0.1-nightly5

### Relevant Collection/Overlay/Playlist Definition

```yml
`    - default: actor
      template_variables:
        collection_section: '001'
        use_separator: false
        style: signature
        name_format: 🎂 <<key_name>>'s Birthday
        translation_key: birthday
        sort_by: audience_rating.desc
        title_format: <<key_name>>'s Birthday
        data:
          depth: 20
          limit: 100
        tmdb_birthday:
          this_month: true
        schedule: monthly(1)
`
```

### Logs

https://gist.github.com/nairbd/92056ec8cafa3512eecbffd69e2aeb7a

**Comment by YozoraXCII** [comment]
Your log file is incomplete and doesn't show this, can you upload a full log file @nairbd

**Comment by nairbd** [comment]
> Your log file is incomplete and doesn't show this, can you upload a full log file @nairbd

I updated the gist. Full log file is too big to upload so I have through the top actors section.

**Comment by meisnate12** [comment]
the gist doesnt have the actors default load section it stops during `cesar`

we need the section titled `Loading Collection File Default: actor`

and the section actually building one of the collections in that file

**Comment by nairbd** [comment]
@meisnate12 That section is in the gist, but is cutoff in the preview. You need to view the raw to see it, but it's the last section of the log. I specifically cut it after that section completed when I posted it/

**Comment by meisnate12** [comment]
@nairbd this does have where the collection are loaded but i still need the section where the actual collection is created

**Comment by nairbd** [comment]
Here's the full file: 
https://www.dropbox.com/scl/fi/4wj87frbn0fm4gqhs3nq6/meta.log.10?rlkey=lezgn74ikqsu9vw53rbs869bq&dl=0

**Comment by meisnate12** [comment]
try doing this it may do the same thing but i cant remember
```yaml
    - default: actor
      schedule: monthly(1)
      template_variables:
        collection_section: '001'
        use_separator: false
        style: signature
        name_format: 🎂 <<key_name>>'s Birthday
        translation_key: birthday
        sort_by: audience_rating.desc
        title_format: <<key_name>>'s Birthday
        data:
          depth: 20
          limit: 100
        tmdb_birthday:
          this_month: true
```
