### ISSUE TITLE
Failure creating certified fresh overlay

### ISSUE THREAD

**Issue by hcgatewood** [Kometa-Team/Kometa#2055]
### Version Number

2.0.1

### What branch are you on?

master

### Describe the Bug

All my rotten tomato overlays are now just "fresh" or "rotten" -- no more "certified fresh".

I believe this is the source of the issue in the logs:

```
|============================== Gathering Items for Rating1Top Overlay ==============================|
|                                                                                                    |
| Builder: mdblist_list: {'url': 'https://mdblist.com/lists/k0meta/certifiedfreshmovies', 'limit': 0, 'sort_by': 'rank.asc'} |
|                                                                                                    |
| Processing MDBList.com List: https://mdblist.com/lists/k0meta/certifiedfreshmovies                 |
| Sort By: rank.asc                                                                                  |
|                                                                                                    |
| 5302 IDs Found                                                                                     |
|                                                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "/app/kometa/modules/overlays.py", line 573, in compile_overlays                            |
|     builder.filter_and_save_items(builder.gather_ids(method, value))                               |
|   File "/app/kometa/modules/builder.py", line 2306, in filter_and_save_items                       |
|     input_id = int(input_id)                                                                       |
|                ^^^^^^^^^^^^^                                                                       |
| TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'   |
|                                                                                                    |
| Unknown Error: int() argument must be a string, a bytes-like object or a real number, not 'NoneType' |
```

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Movies:
    # NOTE: set to true to force-reapply overlays
    reapply_overlay: false
    remove_overlays: false
    collection_files:
      - file: /config/movies.yml
    overlay_files:
      - default: ratings
        template_variables:
          rating1: critic
          rating1_image: rt_tomato
          rating1_font_size: 65
          rating2: audience
          rating2_image: rt_popcorn
          rating2_font_size: 65
          vertical_position: bottom
          horizontal_position: right
      - default: streaming
        template_variables:
          vertical_position: bottom
          horizontal_position: left
          vertical_offset: 50
    operations:
      mass_critic_rating_update: mdb_tomatoes
      mass_audience_rating_update: mdb_tomatoesaudience
      delete_collections:
        managed: false
        configured: false
        less: 1000
settings:
  run_order:
    - operations
    - metadata
    - collections
    - overlays
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_assets: true
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  default_collection_order:
  minimum_items: 1
  item_refresh_delay: 0
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  save_report: false
  tvdb_language: default
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: false
webhooks:
  error: notifiarr
  run_start:
  run_end:
  version:
  delete:
plex:
  url: https://plex.{{ DOMAIN }}
  token: {{ PLEX_TOKEN }}
  timeout: 60
  db_cache:
  clean_bundles: true
  empty_trash: true
  optimize: false
  verify_ssl: true
tmdb:
  apikey: {{ TMDB_API_KEY }}
  language: en
  cache_expiration: 60
  region:
mdblist:
  apikey: {{ MDBLIST_API_KEY }}
  cache_expiration: 60
radarr:
  url: https://radarr.{{ DOMAIN }}
  token: {{ RADARR_API_KEY }}
  add_missing: true
  add_existing: false
  upgrade_existing: false
  monitor_existing: false
  root_folder_path: /data/media/movies
  monitor: true
  availability: released
  quality_profile: HD-1080p
  tag: kometa
  search: true
  ignore_cache: false
  radarr_path:
  plex_path:
tautulli:
  url: https://tautulli.{{ DOMAIN }}
  apikey: {{ TAUTULLI_API_KEY }}
notifiarr:
  apikey: {{ NOTIFIARR_API_KEY }}
```

### Logs

https://gist.github.com/hcgatewood23/997c2067a23eb2152c2300671b180a1b
