### ISSUE TITLE
Unknown Error: 'CommentedSeq' object has no attribute 'strip'

### ISSUE THREAD

**Issue by qazero** [Kometa-Team/Kometa#2095]
### Version Number

2.0.1-nightly24

### What branch are you on?

nightly

### Describe the Bug

Fails to build collection. According Mr. Carrot on Discord, issue is also present on 2.0.2 and it happens with a list, but not with a single URL. 

### Relevant Collection/Overlay/Playlist Definition

```yml
Hallmark - Movies:
    summary: A collection of heartwarming movies brimming with love, laughter, and the promise of second chances. Each story is a testament to the enduring magic of heartfelt romance, the joy of true love, and the enchantment of the holiday season.
    mdblist_list:
      url:
        - https://mdblist.com/lists/SynAcksHM/hallmark
        - https://mdblist.com/lists/marko8426/hallmarkallmovies
        - https://mdblist.com/lists/larryconlin/gentle-hallmark-romantic-comedies
        - https://mdblist.com/lists/chrisdmartinez/hallmark-ovlcerrd46
        - https://mdblist.com/lists/womblechutney/hallmark-3k21cd0jzu
        - https://mdblist.com/lists/womblechutney/hallmark-movies
    sync_mode: sync
    smart_label: release.desc
    collection_mode: hide
    visible_library: false
    visible_home: false
    visible_shared: false
    schedule: monthly(1)
```

### Logs

https://gist.github.com/qazero/a7290d11f98c4c6b8e7350f938ff3d76
