### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED even when verify_ssl:false

### ISSUE THREAD

**Issue by Minituff** [Kometa-Team/Kometa#2100]
### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

Hello, I am trying to get Kometa up and running but I am hitting SSL validation errors even though I disabled the validation requirement.

```yml
plex:                                # Can be individually specified per library as well; REQUIRED for the script to run
  url: https://192.168.1.50:32400
  token: FAKE_KEY
  timeout: 60
  db_cache:
  clean_bundles: false
  empty_trash: false
  optimize: false
  verify_ssl: false
```

Logs are in the gist link.

### Logs

https://gist.github.com/Minituff/824be2436b2be59568ce22398e400356
