### ISSUE TITLE
Library Asset Directory silently falls back to global value if path does not exist

### ISSUE THREAD

**Issue by undaunt** [Kometa-Team/Kometa#2107]
### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

When setting a global value for asset directory and then a subfolder of that path as a library specific asset directory within the settings section, if the subfolder for the library specific asset path does not exist, it will not throw an error or mkdir the folder - it will silently fall back to the global asset directory as the parent folder.

My expectation would be that the subfolder declared as the library specific asset path would be mkdir created, similar to all of the subfolders for library assets such as each movie's specific folder when asset_folder is true.

I could not find documentation on this issue or that this would be the expected behavior. I discussed the issue with a few people on discord here - https://discord.com/channels/822460010649878528/1248792070970282106

If this is expected behavior, I'm not sure if it would warrant a note in the wiki. Thanks!

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  kids:
    library_name: Kids' Shows
    metadata_files:
      - file: config/metadata/mediux-kids.yml  
    overlay_files:
      - file: config/overlays/media_info.yml
      - file: config/overlays/audience_rating.yml
    settings:
      asset_directory: config/assets/kids

# Settings  
settings:
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  download_url_assets: true
```
