### ISSUE TITLE
Edition overlay background overlaps resolution when back_color template variable is used

### ISSUE THREAD

**Issue by Hydroptix** [Kometa-Team/Kometa#2108]
### Version Number

2.0.1-nightly1 (Docker)

### What branch are you on?

nightly

### Describe the Bug

When the `back_color` argument is specified, the background for the edition draws over the resolution section of the overlay.  
![image](https://github.com/Kometa-Team/Kometa/assets/8387968/5d2e6bac-1bea-4634-9317-b71bca480126)

Removing the `back_color` variable causes the overlay to render as expected.  
![image](https://github.com/Kometa-Team/Kometa/assets/8387968/e60e877f-7fa4-45f1-abef-37cdcd02b6ac)

### Relevant Collection/Overlay/Playlist Definition

```yml
- pmm: resolution
      template_variables:
        back_color: '#202020ff'
        horizontal_align: left
        horizontal_offset: 0
        vertical_align: top
        vertical_offset: 0
        use_dvhdr: false
        use_1080p_dvhdr: false
        use_4k_dvhdr: false
        use_edition: true
```

**Comment by bambanah** [comment]
I'm actually experiencing a very similar thing, except without `back_color` set.

![image](https://github.com/user-attachments/assets/82e22ad2-dc61-4a12-9f39-4a4b4833417f)

```yaml
overlay_files:
  - default: resolution
    template_variables:
      use_1080p: false
      use_720p: false
      use_576p: false
      use_480p: false
  - default: mediastinger
    template_variables:
      horizontal_align: left
      vertical_align: bottom
```
