### ISSUE TITLE
Overlay my YAML file "Newly Released" not show

### ISSUE THREAD

**Issue by gianfelicevincenzo** [Kometa-Team/Kometa#2118]
### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

**config/config.yml**:
```
libraries:                          
  Film:                             
    remove_overlays: false       
    collection_files:
      - default: basic
        template_variables:
          in_the_last_episodes: 7
          visible_library_released: true
          visible_home_released: true
          visible_shared_released: true
      - default: resolution
        template_variables:
          style: standards
      - default: studio
      - default: streaming
      - default: oscars
      - default: trakt                 # This is a file within Kometa's defaults folder
      - default: imdb                  # This is a file within Kometa's defaults folder
      - default: tmdb                  # This is a file within Kometa's defaults folder
      - default: letterboxd
      # see the wiki for how to use local files, folders, URLs, or files from git
      - file: config/jake.yml
    overlay_files:
      - default: ribbon
        template_variables:
      - default: resolution
      - default: streaming
        template_variables:
        #  horizontal_align: left
        #vertical_align: bottom 
        #vertical_offset: 200
          back_padding: 45
      - default: ratings                                           
        template_variables:
          rating1: audience                         
          rating1_image: imdb                                     
          rating1_font: config/fonts/impact.ttf           
          rating1_font_size:  65                                         
          rating2: audience                          
          rating2_image: tmdb        
          rating2_font: config/fonts/impact.ttf               
          rating2_font_size:  65                        
          horizontal_position: right 
      - file: config/leavingsoon.yml
      - file: config/newlyreleased.yml
```

**config/newlyreleased.yml**:
```
overlays: 
  newly-released:
    overlay:
      name: text(Ultra HD)
      horizontal_align: center 
      vertical_align: bottom
      horizontal_offset: 0
      vertical_offset: 128
      font: config/fonts/Bebas_Neue/BebasNeue-Regular.ttf
      font_size: 110
      font_color: '#FFFFFF'
      back_color: '#FF0000'
      back_radius: 0
      back_padding: 45
    plex_search:
      all:
        collection: 'Newly Released'
```

during execution it should insert the word "recently added" into the "**newly released**" collection created by the script. The problem is that the message "**Collection not found**" then appears.
