### ISSUE TITLE
Overlay Error: sonarr_taglist is not a valid filter attribute

### ISSUE THREAD

**Issue by Dragonsys** [Kometa-Team/Kometa#2162]
### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

When using sonarr_taglist as filter for overlays, I get an error that it is not a valid filter attribute

[2024-07-15 07:16:49,411] [overlays.py:598]           [ERROR]    | Overlay Error: sonarr_taglist is not a valid filter attribute

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  # TEXT CENTER
  TV_Top_TextCenter:
    sync_mode: sync
    builder_level: show
    overlay:
      name: text(<<text>>)
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
      font: config/files/fonts/Juventus-Fans-Bold.ttf
      font_size: 70
      font_color: <<color>>
      group: TV_Top_TextCenter
      weight: <<weight>>
      back_color: <<back_color>>
      back_width: 1920
      back_height: 90


overlays:
  complete_canceled:
    template:
    - name: TV_Top_TextCenter
      weight: 20
      text: "C O M P L E T E"
      color: "#FFFFFF"
      back_color: "#CF142B"
      horizontal_align: center
      vertical_align: bottom
      horizontal_offset: 0
      vertical_offset: 0
    plex_all: true
    filters:
      tmdb_status:
      - canceled
      sonarr_taglist: complete
  complete_ended:
    template:
    - name: TV_Top_TextCenter
      weight: 20
      text: "C O M P L E T E"
      color: "#FFFFFF"
      back_color: "#000000"
      horizontal_align: center
      vertical_align: bottom
      horizontal_offset: 0
      vertical_offset: 0
    plex_all: true
    filters:
      tmdb_status:
      - ended
      sonarr_taglist: complete
```

### Logs

https://gist.github.com/Dragonsys/ba7dc6be78d3849abba100431838721e
