### ISSUE TITLE
Empty trash doesn't seem to work

### ISSUE THREAD

**Issue by Skaronator** [Kometa-Team/Kometa#2176]
### Version Number

v2.0.2

### What branch are you on?

master

### Describe the Bug

I've enabled `plex.empty_trash: true` yet Kometa doesn't seem to empty the trash for my libraries.

This is my configuration:

```yaml
    plex:
      url: https://plex:32400
      token: <<SECRET_PLEX_TOKEN>>
      clean_bundles: true
      optimize: true
      empty_trash: true
```

But after running Kometa it doesn't clean the trash of my movies and TV series. As you can see, I have items that look like this:
![image](https://github.com/user-attachments/assets/af4ea003-7f27-4315-a24c-ba8715e318d6)

I checked the code and noticed that I've to define each library explicitly, so I had added my tv show library, but both movies and tv show libraries doesn't empty the trash.

Here is my full, currently deployed, configuration: https://github.com/Skaronator/homelab/blob/main/kubernetes/media/kometa/values.yaml#L28

### Logs

https://gist.github.com/Skaronator/08cdba1e39b26f6b09e3544a752d66f6
