### ISSUE TITLE
"Duration" filter might not be working as intended

### ISSUE THREAD

**Issue by Darkridge** [Kometa-Team/Kometa#2192]
### Version Number

2.0.2-build28 (Docker: nightly)

### What branch are you on?

nightly

### Describe the Bug

The `duration` filter seems to return single episode runtimes even if used explicitly with `build_level: show`. Not sure if this is intended or if it should instead return the show runtime (similar to the `<<total_runtime>>` overlay).

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  show_duration:
    default:
      horizontal_offset: 10
      horizontal_align: left
      vertical_offset: 20
      vertical_align: bottom
    conditionals:
      files:
        conditions:
          - key: runtime_5_shadow
            value: config/tc_overlays/runtime/runtime_tv_5_shadow.png
          - key: runtime_4_shadow
            value: config/tc_overlays/runtime/runtime_tv_4_shadow.png
          - key: runtime_3_shadow
            value: config/tc_overlays/runtime/runtime_tv_3_shadow.png
          - key: runtime_2_shadow
            value: config/tc_overlays/runtime/runtime_tv_2_shadow.png
          - key: runtime_1_shadow
            value: config/tc_overlays/runtime/runtime_tv_1_shadow.png
      duration.gte:
        conditions:
          - key: [runtime_5, runtime_5_shadow]
            value: 10000
          - key: [runtime_4, runtime_4_shadow]
            value: 1000
          - key: [runtime_3, runtime_3_shadow]
            value: 100
          - key: [runtime_2, runtime_2_shadow]
            value: 10
          - key: [runtime_1, runtime_1_shadow]
            value: 0
      names:
        default: <<overlay_name>>
        conditions:
          - key: [runtime_5, runtime_4, runtime_3, runtime_2, runtime_1]
            value: text(<<total_runtime>>m)
    optional:
      - file
    plex_all: true
    filters:
      duration.gte: <<duration.gte>>
    builder_level: show
    overlay:
      name: <<names>>
      group: <<group>>
      weight: <<weight>>
      file: <<files>>
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
      back_width: 248
      back_height: 182
      back_align: left
      font_color: "#FFFFFF"
      font_size: 55
      stroke_width: 7
      stroke_color: "#000000CC"

overlays:
  runtime_5_shadow:
    variables: { key: runtime_5_shadow, weight: 500, group: backdrop }
    template: [ name: show_duration ]
  runtime_4_shadow:
    variables: { key: runtime_4_shadow, weight: 400, group: backdrop }
    template: [ name: show_duration ]
  runtime_3_shadow:
    variables: { key: runtime_3_shadow, weight: 300, group: backdrop }
    template: [ name: show_duration ]
  runtime_2_shadow:
    variables: { key: runtime_2_shadow, weight: 200, group: backdrop }
    template: [ name: show_duration ]
  runtime_1_shadow:
    variables: { key: runtime_1_shadow, weight: 100, group: backdrop }
    template: [ name: show_duration ]
  runtime_5:
    variables: { key: runtime_5, weight: 500, group: showlength }
    template: [ name: show_duration ]
  runtime_4:
    variables: { key: runtime_4, weight: 400, group: showlength }
    template: [ name: show_duration ]
  runtime_3:
    variables: { key: runtime_3, weight: 300, group: showlength }
    template: [ name: show_duration ]
  runtime_2:
    variables: { key: runtime_2, weight: 200, group: showlength }
    template: [ name: show_duration ]
  runtime_1:
    variables: { key: runtime_1, weight: 100, group: showlength }
    template: [ name: show_duration ]
```
