### ISSUE TITLE
`audio_track_title` filter is not collecting all shows with audio tracks with collections

### ISSUE THREAD

**Issue by HStep20** [Kometa-Team/Kometa#2204]
### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

I use the `audio_track_title` filter in order to collect all shows that have episodes with commentary tracks. For some reason, this filter is not grabbing all of the shows that have tracks. I know of at least 4 in my library that are not being pulled into the collection. 

After some testing, Ive found that the `audio_track_title` filter works when used in a playlist to grab all episodes of a show with commentary audio tracks  - even shows missing from the collection. 

I initially posted this in the discord support area, thinking it was a misconfiguration, but after my findings with the playlists, I think it may be a bug. The support thread can be found here: https://discord.com/channels/822460010649878528/1274191204086579300

The logs dont state any errors or warnings, so it seems like these shows are just being passed over when the collection is run. You can find 

Picture of Collection:

<img width="1285" alt="Screenshot 2024-08-22 at 8 20 55 AM" src="https://github.com/user-attachments/assets/87e65531-c200-4c2c-ac4c-fa1740528d8a">

Picture of playlists created by the template provided:

<img width="1132" alt="Screenshot 2024-08-22 at 8 21 39 AM" src="https://github.com/user-attachments/assets/8f0ba168-4fe1-4242-93c1-0dcf57bf6115">

You can see at least 4 shows (that I knew about for testing) which arent included in the collection, even though they have episodes with commentary in them which are collected into the playlists

### Relevant Collection/Overlay/Playlist Definition

```yml
Initial Config: 


  Shows with Commentary:
    plex_all: true
    filters:
      audio_track_title: Commentary
    sort_title: +++++++++_Shows with Commentary
    sync_mode: sync
    collection_order: release
    summary: Shows with commentary audio tracks from the creators.


Playlist Config:

```yaml
  Commentary Episodes:
    libraries: "All TV Shows"
    sync_mode: sync
    builder_level: episode
    summary: All of the <<show_title>> episodes that have commentary
    plex_search:
      type: episode
      all:
        title: <<show_title>>
        # episode_unplayed: true
      sort_by: episode_release.asc
    filters:
      audio_track_title: Commentary
```

Updated Collection Config to try and mimic the playlist config:

```yaml
  Shows with Commentary:
    plex_search:
      type: episode
      all:
        year.gte: 1900
    filters:
      audio_track_title: Commentary
    default_percent: 1
    sort_title: +++++++++_Shows with Commentary
    sync_mode: sync
    collection_order: alpha
    summary: Shows with commentary audio tracks from the creators.
```
```


### Logs

https://pastebin.com/raw/38sUMrez

**Comment by badja-dev** [comment]
@HStep20 - This is "by design"

When filters like `audio_track_title` or `subtitle_language` are used on a show-level collection, Kometa checks at the episode level and applies a 50% threshold by default. This was a deliberate decision - without it, a show with 100 episodes where only 1 had a commentary track (or Dolby Vision, Spanish subs, etc.) would be included, which most users wouldn't want.

The reason it behaves differently in playlists is that playlists operate at the episode level directly, so there's no threshold to apply - each episode either matches or it doesn't.

If you'd like to change the threshold you have two options:

**Adjust the percentage** - use `default_percent` to lower (or raise) the required match rate:
```yaml
  My Commentary Collection:
    default_percent: 10   # include shows where at least 10% of episodes match
    plex_all: true
    filters:
      audio_track_title: Commentary
```

**Use an explicit count** - use the `episodes` special filter directly if you want an exact minimum number of matching episodes:
```yaml
  My Commentary Collection:
    plex_all: true
    filters:
      episodes:
        audio_track_title: Commentary
        count: 1   # any show with at least 1 matching episode
```

Hope that clears things up!
