### ISSUE TITLE
[Defaults]: X-Men Timeline List 404

### ISSUE THREAD

**Issue by benblustey** [Kometa-Team/Kometa#2227]
### Link to File

/master/defaults/playlist.yml

### Version Number

2.0.2

### What branch are you on?

master

### Describe the Bug

The X-Men timeline Trakt playlist by `heyitsbea` does not exist anymore. This causes an error and was difficult to locate since it did not reference that it was from the default playlist.

**Comment by chazlarson** [comment]
This has been fixed in nightly; you can also use a template_variable to set a different list of your choice.

```
playlist_files:
  - default: playlist
    template_variables:
      trakt_list_xmen: TRAKT_LIST_URL_OF_YOUR_CHOICE
```

The error in the log should show up in context in the default playlist processing section; the error summary at the end won't identify the specific source, but if you search for the error in the log it should be apparent precisely where it's coming from.  This is common to all errors in the summary.
