### ISSUE TITLE
Smart Collections

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#226]
Add smart collections functionality 

(Done) Add `smart_label` which can be given one of the sort options below. Using the smart label will create a special smart collection where the smart collection just searches for a label which is added to all the movies the collection builders find

Sort Options
`title.asc`, `title.desc`, `year.asc`, `year.desc`, `originally_available.asc`, `originally_available.desc`, `critic_rating.asc`, `critic_rating.desc`, `audience_rating.asc`, `audience_rating.desc`, `user_rating.asc`, `user_rating.desc`, `content_rating.asc`, `content_rating.desc`, `duration.asc`, `duration.desc`, `plays.asc`, `plays.desc`, `added.asc`, `added.desc`, `random`

(Done)  Add another option to build some smart collection similarily to how `plex_search` is formatted

**Comment by danhew** [comment]
Thanks for adding this. 

Will it be able to add a label/smart collection without making a non-smart collection?

**Comment by meisnate12** [comment]
Yes if you use either attributes above the smart collection will be created automatically and if it's already a normal collection it will be converted to a smart collection

**Comment by miguelamaral** [comment]
Would it be possible for the script to ignore any values not found in the collection? At the moment it throws an error and skips the collection altogether, as seen here:
```yaml
Baltic:
  smart_filter:
    any:
      country: Estonia, Latvia, Lithuania
    sort_by: year.asc
```
```
Scanning Baltic Collection
Smart Movie Filter
Sort By: year.asc
Plex Error: country: Latvia not found
```
I've also noticed the collection's thumbnail label doesn't always match the actual number of films. I figure it's probably got nothing to do with script, as it's been brought up [here](https://forums.plex.tv/t/smart-collection-shows-wrong-numbers-of-items-in-label-when-limit-to-is-used/711870)?

Thanks!

**Comment by meisnate12** [comment]
yea the number of items has nothing to do with PMM.

It would be possible to have it function that way but to me, it makes more sense to have it fail if the item isn't found that way you know a mistake has been made and it emulates how the advance filter works in plex. You cant select an option that isn't already in your library. I would either remove the option that isn't found or add a movie to your library that will have that tag there

**Comment by meisnate12** [comment]
PS nice job figuring out how to use `smart_filter` without me detailing it anywhere

**Comment by miguelamaral** [comment]
Yeah, I understand this would be a very specific use case. I was just hoping to transform a bunch of regular collections into smart collections, but it wouldn't work without those changes. Basically, grouping a predefined set of countries/regions would be unfeasible, as the script would likely fail unless you manually checked the Plex countries list before every run:
```yaml
# Eastern Europe
country: Belarus, Bulgaria, Czech Republic, Hungary, Poland, Republic of Moldova, Romania, Russian Federation, Slovakia, Ukraine
# Latin America
country: Anguilla, Antigua and Barbuda, Argentina, Aruba, Bahamas, Barbados, Belize, Bolivarian Republic of Venezuela, "Bonaire, Sint Eustatius and Saba", Bouvet Island, Brazil, Cayman Islands, Chile, Colombia, Costa Rica, Cuba, Curaçao, Dominica, Dominican Republic, Ecuador, El Salvador, Falkland Islands (Malvinas), French Guiana, Grenada, Guadeloupe, Guatemala, Guyana, Haiti, Honduras, Jamaica, Martinique, Mexico, Montserrat, Nicaragua, Panama, Paraguay, Peru, Plurinational State of Bolivia, Puerto Rico, Saint Barthélemy, Saint Kitts and Nevis, Saint Lucia, Saint Martin (French part), Saint Vincent and the Grenadines, Sint Maarten (Dutch part), South Georgia and the South Sandwich Islands, Suriname, Trinidad and Tobago, Turks and Caicos Islands, Uruguay, Virgin Islands (British), Virgin Islands (U.S.)
```
I agree the default behaviour should be for it to fail, so something like a --ignore-invalid-options flag could work? Thanks again!
