### ISSUE TITLE
Playlist move item doesn't seem to work

### ISSUE THREAD

**Issue by ronniehicks** [Kometa-Team/Kometa#2265]
### Version Number

2.0.2 (Docker: master)

### What branch are you on?

master

### Describe the Bug

After the first creation of the playlist, any attempt to reprocess and move items into the correct placement results in the following error, regardless of playlist:

```shell
[2024-10-10 15:07:13,844] [plex.py:645]               [ERROR]    | (404) not_found; (redacted)/playlists/23193/items/None/move <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html> |
[2024-10-10 15:07:13,844] [builder.py:3505]           [ERROR]    | Failed to Move Constantine S01E01: Season 1: Episode 1                                             |
```

### Relevant Collection/Overlay/Playlist Definition

```yml
playlist_files:
- file: config/playlists.yml
- default: playlist
  template_variables:
    libraries: Movies, TV Shows
    radarr_add_missing: true
    sonarr_add_missing: true
```

```yml
playlists: 
  One Chicago (Timeline Order):
    sync_mode: sync
    libraries: TV Shows
    trakt_list: https://trakt.tv/lists/5415197
    summary: One Chicago
    radarr_add_missing: true
    sonarr_add_missing: true
  The Walking Dead (Timeline Order):
    sync_mode: sync
    libraries: TV Shows
    trakt_list: https://trakt.tv/lists/25146121
    summary: The Walking Dead
    radarr_add_missing: true
    sonarr_add_missing: true
```
```


### Logs

_No response_
