### ISSUE TITLE
playlist doesn't seem to respect builder_level on music library

### ISSUE THREAD

**Issue by paulo-erichsen** [Kometa-Team/Kometa#2267]
### Version Number

2.1.0 (docker)

### What branch are you on?

master

### Describe the Bug

I've tried adding a **playlist** with specific tracks, but what ends happening is that it seems to ignore the `builder_level: track` setting causing matches to add ALL tracks from matched artists instead of only the matched tracks.

Note that when using collections the issue doesn't reproduce there. When a collection is made, the builder_level is respected and only the selected tracks gets added to the collection. But I wanted to use a playlist since I don't want it visible to everyone.

### Relevant Collection/Overlay/Playlist Definition

```yml
playlists:
  sesh:
    sync_mode: sync
    sync_to_users: ''
    libraries: music
    collection_order: custom
    builder_level: track
    plex_search:
      any:
        all:
          - album_title.is: BUSH
            track_title.is: California Roll
          - album_title.is: Caress your Soul
            track_title.is: Australia Street
```

Result: the playlist contains hundreds of tracks instead of just 2 :x: 

### For comparison the following collection works and respects builder_level

```yml
collections:
  sesh:
    builder_level: track
    plex_search:
      any:
        all:
          - album_title.is: BUSH
            track_title.is: California Roll
          - album_title.is: Caress your Soul
            track_title.is: Australia Street
```
Result: the collection contains exactly 2 tracks :heavy_check_mark: 

### Logs

Looking at the logs, it clearly shows that kometa processes the playlist as `Plex Artist Search` instead of `Plex Track Search`. The logs also show an exception that's thrown which may be related or may be a separate issue (perhaps #2265?).

https://gist.github.com/paulo-erichsen/e0e7a87579573bd2dcf47f8b5f4819de
