### ISSUE TITLE
Default "Trakt Anticipated" collection does not exist.

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#2324]
### Version Number

2.1.0 any

### What branch are you on?

nightly

### Describe the Bug

The wiki describes a "Trakt Anticipated" collection as part of the Trakt defaults; this collection is not found in the Trakt default yaml.

This produces no collections and no mention of the collection in the log:
```yaml
libraries:
  Kometa-Demo-Movies:
    collection_files:
      - default: trakt
        template_variables:
          use_all: false
          use_anticipated: true
```
