### ISSUE TITLE
Issue with persons when their name start with a number

### ISSUE THREAD

**Issue by CpHeat** [Kometa-Team/Kometa#2385]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Plex search for actors using tmdb faisl when the actor's name starts with a number, because the search get the tmdb page corresponding to that number instead of the page for that person

e.g. : 50 Cent will get Catherine Deneuve because her id on tmdb is 50. 2 Chainz will get Mark Hamill. This causes the collections to not be created because the script then compare the person with the array of actors actually present in the library and do not find him/her into it

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:  
  Actor:
    plex_search:
      all:
        actor: tmdb
    tmdb_person: "<<value>>"
    sort_title: "!_<<value>>"
    sync_mode: sync
    collection_order: title.asc  
dynamic_collections:
  Actors:
    type: actor
    data:
      depth: 10
      minimum: 1
    template: 
      - Actor
```

### Logs

https://gist.github.com/CpHeat/873dd0222e9cbc5d24d427272504c3a8
