### ISSUE TITLE
Notification every day of collection creation around the Oscars

### ISSUE THREAD

**Issue by Derekcde** [Kometa-Team/Kometa#2415]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Good morning, 

I have had this non-blocking but disturbing problem for a long time now. Every day I have notifications of collection creation for "Oscars Winners XXXX" even though I have neither added nor deleted films in my Plex, in the Kometa log, it adds the films every day that it added the day before, and I don't know why, whereas for the Golden Globes I have no problem.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  Films:
    collection_files:
      - default: seasonal
        template_variables:
          language: fr
          minimum_items: 3
          visible_home: true
          visible_shared: true
          sync_mode: sync
          use_independence: false 
          sort_by: random 
          imdb_list_christmas: https://www.imdb.com/list/ls027353066/
          mdblist_list_christmas: 
            - https://mdblist.com/lists/bluejack92/christmas-by-antares/
            - https://mdblist.com/lists/scottgigawatt/every-christmas-movie-ever-made/
          mdblist_list_halloween: https://mdblist.com/lists/linvo/halloween-popular-movies/
          mdblist_list_valentine: https://mdblist.com/lists/linvo/valentines-day-popular-movies/
          emoji: "" #PLEX BUG EMOJI
      - default: based
        template_variables:
          language: fr
          minimum_items: 3
          use_separator: false
          exclude:
            - comics
            - video_games
      - default: decade
        template_variables:
          use_separator: false   
          language: fr
          minimum_items: 3
      - default: golden                                   # Golden Globes Awards
        template_variables:                           # Show collections from latest-10 onwards.
          language: fr
          minimum_items: 3
          use_separator: false
          data:
            starting: latest-2
            ending: latest
      - default: oscars                                   # The Oscars
        template_variables:
          language: fr                           # Show collections from latest-10 onwards.
          minimum_items: 3
          use_separator: false
          data:
            starting: latest-2
            ending: latest
    overlay_files:
    - remove_overlays: false
      #- reapply_overlay: true
    - default: resolution
    operations:
      mass_content_rating_update: 
        - mdb_commonsense
        - mdb_age_rating
      #delete_collections:
      #  configured: false
      #  managed: true

  Séries TV:
    overlay_files:
    - remove_overlays: false   # Set to true if you want to remove overlays
    #- reapply_overlay: true  # If you are doing a lot of testing and changes like me, keep this to true to always reapply overlays - can cause image bloat
    #- reset_overlays: tmdb # if you want to reset the poster to default poster from tmdb - can cause image bloat
    - default: streaming
      template_variables:
        vertical_offset: 15
    - default: resolution
      template_variables:
        overlay_level: episode
        vertical_align: bottom
        horizontal_align: left
    - default: runtimes
      template_variables:
        overlay_level: episode
        vertical_align: bottom
        horizontal_align: right
        text: ''
        back_width: 254

settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: true
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: append
  minimum_items: 2
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: false
  show_missing_assets: true
  save_report: false
  tvdb_language: fra
  ignore_ids: None
  ignore_imdb_ids: None
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_exclude_users: None
  playlist_report: false
  verify_ssl: true
  custom_repo: None
  check_nightly: false
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
plex:                            # Can be individually specified per library as well; REQUIRED for the script to run
  url: http://192.168.1.14:32400
  token: XXXXxxxxXXXX
  timeout: 60
  clean_bundles: true
  empty_trash: true
  optimize: true
  verify_ssl: false
  db_cache: 40
tmdb:                            # REQUIRED for the script to run
  apikey: XXXXXxxxXXXX
  language: fr
  cache_expiration: 60
  region: FR
mdblist:
  apikey: XXXXxxxxXXX
  cache_expiration: 60
gotify:
  url: https://XxxxxXxXx
  token: xXXXXxxXxx
webhooks: 
  error: gotify
  run_start: gotify
  run_end: gotify
  changes: gotify
  delete: gotify
  version: gotify
```

### Logs

https://gist.github.com/Derekcde/f041700a40e31fe2da8e1a016f2df635
