### ISSUE TITLE
Split Duplicates operation on TV Show is splitting when there is no duplicate

### ISSUE THREAD

**Issue by pzabel** [Kometa-Team/Kometa#2455]
### Version Number

2.1.0

### What branch are you on?

develop

### Describe the Bug

On my test server, I went to run a clean-up operation and had _split duplicates_ as **true**.   When the Series library runs the split operation, it is splitting the two TV Shows "Arrow" (tmdb -1412) and "Marvel's Agents of S.H.I.E.L.D." (tmdb-1403).  This then causes the script to crash with several plex 404 API calls.  It may be happening with more shows, but these two I have loaded into this library.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  SeriesTest:
    operations:
      split_duplicates: true  #When this is present, it splits the two shows above and gets 404 errors 
                              #when running futher operations.  When commented out, it the script completes.
```

### Logs

https://gist.github.com/pzabel/9b8b9481aeaf14d08cd89be1dfa0ae54
