### ISSUE TITLE
urllib3.exceptions.SSLError: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by keliansb** [Kometa-Team/Kometa#2461]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Everytime Kometa is launched I'm facing the same issue you can find on the Gist.
It seems to happen on a specific TV Show, Shameless, for which I have posters in the image assets directory.
I tried to launch Kometa with `--debug` option but I don't have more details.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  [...]
  Séries:
    operations:
      assets_for_all: true
    collection_files:
      - pmm: basic
      - pmm: imdb
      - pmm: streaming
        template_variables:
          use_separator: false
      - pmm: tautulli
      - pmm: tmdb
    overlay_files:
      - pmm: audio_codec
        template_variables:
          use_ma: false
          use_flac: false
          use_pcm: false
          use_hra: false
          use_plus: false
          use_dtses: false
          use_dts: false
          use_aac: false
          use_mp3: false
          use_opus: false
      - pmm: audio_codec
        template_variables:
          overlay_level: season
          use_ma: false
          use_flac: false
          use_pcm: false
          use_hra: false
          use_plus: false
          use_dtses: false
          use_dts: false
          use_aac: false
          use_mp3: false
          use_opus: false
      - pmm: audio_codec
        template_variables:
          overlay_level: episode
          use_ma: false
          use_flac: false
          use_pcm: false
          use_hra: false
          use_plus: false
          use_dtses: false
          use_dts: false
          use_aac: false
          use_mp3: false
          use_opus: false
      - pmm: resolution
        template_variables:
          use_1080p: false
          use_720p: false
          use_576p: false
          use_480p: false
      - pmm: resolution
        template_variables:
          overlay_level: season
          use_1080p: false
          use_720p: false
          use_576p: false
          use_480p: false
      - pmm: resolution
        template_variables:
          overlay_level: episode
          use_1080p: false
          use_720p: false
          use_576p: false
          use_480p: false
      - pmm: versions
    settings:
      asset_directory: config/assets/Series
  [...]
plex:
  clean_bundles: false
  empty_trash: false
  optimize: false
  timeout: 60
  token: xyz
  url: https://<plex_url>
  verify_ssl:
  db_cache:
settings:
  cache: true
  cache_expiration: 60
  asset_directory:
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  default_collection_order:
  minimum_items: 1
  item_refresh_delay: 0
  delete_below_minimum: false
  delete_not_scheduled: false
  run_again_delay: 0
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_unconfigured: true
  show_filtered: false
  show_options: false
  show_missing: true
  save_report: false
  tvdb_language: fr
  ignore_ids:
  ignore_imdb_ids:
  playlist_sync_to_users: all
  playlist_exclude_users:
  playlist_report: true
  verify_ssl: true
  custom_repo:
  check_nightly: false
  run_order:
    - operations
    - metadata
    - collections
    - overlays
  overlay_artwork_filetype: jpg
  overlay_artwork_quality:
tautulli:
  apikey: xyz
  url: https://<tautulli_url>
tmdb:
  apikey: xyz
  cache_expiration: 60
  language: fr
  region: FR
```

### Logs

https://gist.github.com/keliansb/384198ab1102c922038c6f2d251a46ba
