### ISSUE TITLE
Award collection keeping old items, even after collection manually deleted from Plex

### ISSUE THREAD

**Issue by ctejada10** [Kometa-Team/Kometa#2500]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

I have a collection for all the Oscar nominees for the current year. While the collection adds new items well, it also keeps old items from previous runs. This is the first year it has updated--I only installed Kometa last Oscar season--and I can still see the nominees from 2023. I have also tested it with a random year (2020) and it now has nominees from 2020, 2024 and 2025.

### Relevant Collection/Overlay/Playlist Definition

```yml
"🎖️This Year's Oscar Nominees":
    summary: "Who will take home the trophy?"
    template: { name: Award,
                level: "+++" }
    imdb_award:
      event_id: ev0000003
      event_year: %current_year%
      winning: false
    schedule: # Usually late February to mid-March, has been as late as April (one-day)
      - yearly(02/01)
      - all[weekly(monday),range(02/01-04/05)]
      - yearly(04/01)
      # You have to schedule it to run before and after visibility timeframe for visibility to switch
    name_mapping: current_year_academy_award_nominees
    collection_order: random
    radarr_add_missing: true
    visible_home: range(02/01-03/31)
    visible_shared: range(02/01-03/31)
    visible_library: range(02/01-03/31)
```
