### ISSUE TITLE
sync_to_trakt_list only allowed on episodes, should be both shows and episodes

### ISSUE THREAD

**Issue by tecnobrat** [Kometa-Team/Kometa#2501]
### Version Number

2.1.0-build70 (Docker: nightly)

### What branch are you on?

nightly

### Describe the Bug

`sync_to_trakt_list` now only is allowed where the builder level is episode.

I believe this was not intentional.

Prior to using nightly, the attached code worked perfectly.

The commit that introduced this change is: https://github.com/Kometa-Team/Kometa/commit/52a6e54b2665f4743ed7003566579539c039acad

The PR was: https://github.com/Kometa-Team/Kometa/pull/2359, which also indicated that it didn't contain any breaking changes.

The changelog note is "Allow `sync_to_trakt_list` on episode-level collections"

I believe the intent here was to allow this option to *also work* on episodes.

I don't believe the intent was to *only* work on episodes. The docs were also not updated to indicate this, if it was intentional.

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:                                                                   
  Brian and Melanie:
    name_mapping: brian-and-melanie
    sort_title: "!+01-Brian and Melanie"
    sync_missing_to_trakt_list: true
    sync_to_trakt_list: brian-and-melanie
    trakt_list: https://trakt.tv/users/tecnobrat/lists/brian-and-melanie
    sync_mode: append
```

### Logs

https://gist.github.com/tecnobrat/3c5efbac623f74cde94994bc74a74eb8
