### ISSUE TITLE
Playlist added to Radarr but not Sonarr

### ISSUE THREAD

**Issue by suineg** [Kometa-Team/Kometa#2538]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

Recently added kometa into the way I do things. I am a manual run kind of guy for right now. I've been configuring it slowly over the last couple of weeks. I recently added a playlist into the setup and it did not add any of the TV shows that are missing. I manually added a few and it detected those and added it to the playlist when it saw that they were there. Still hasn't added the missing ones after a few runs. 

I couldn't find a problem in the log files and went over it in Discord with Mr. Carrot. He remembers there might be an issue that it does just one of the two add to options. This could be that or I might have done something wrong so I'm wide open to change or test anything. 

I have snipped out user names for the playlist sync but other than that the log file is untouched. This is a trace log so should have all you need?

Command I use to run manually is: `docker run --rm -it -v "/opt/kometa:/config:rw" --user 1000:1000 kometateam/kometa --run --trace` this is done in /opt/kometa where config.yml is and all subfolders.

The only playlist still missing shows is the MCU one, I finished up the Star Wars one manually. The TV shows that I can see missing from both Plex and Sonarr are Stark Expo 2010, I Am Groot, Your Friendly Neighborhood Spider Man, WHIH Newsfront, and What If.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  TV Shows:
    report_path: config/reports/tvshows.yml
    metadata_files:
    - file: config/metadata/mediux.yml
    collection_files:
    - file: config/tv/series-refresh.yml
    - file: config/tv/mycollections.yml
  Movies:
    report_path: config/reports/movies.yml
    collection_files:
    - default: universe
      template_variables:
        use_separator: false
        collection_order: release
        exclude:
        - mummy
        - askew
        - marvel
        - dca
        - arrow
    - file: config/movies/mycollections.yml
    metadata_files:
    - file: config/metadata/mediux.yml
playlist_files:
- default: playlist
  template_variables:
    use_arrow: false
    use_dcau: false
    use_dragonball: false
    use_pokemon: false
    use_startrek: false
    use_clonewars: false
    use_xmen: false
    use_mcu: true
    radarr_add_missing_mcu: true
    sonarr_add_missing_mcu: true
    use_starwars: true
    radarr_add_missing_starwars: true
    sonarr_add_missing_starwars: true
```

### Logs

https://gist.github.com/suineg/31559fa5bb3a7629c7615ed0afc7937c
