### ISSUE TITLE
Collections Not Deleting When Below Minimum

### ISSUE THREAD

**Issue by dweagle** [Kometa-Team/Kometa#2566]
### Version Number

2.1.0-build83

### What branch are you on?

nightly

### Describe the Bug

I have Kometa create collections using a trakt list for streaming services top 10 items.  When the collection gets down to 0 items the collection isn't deleted.

Trying to troubleshoot, I noticed that when the collection gets down to 1 item and that item is no longer on the top 10 trakt list, it doesn't remove that last item from the collection either.  The collection tag is still there in Plex as well, but the Kometa log shows that there are no items found for the collection. I can go in Plex and manually remove the item's tag and remove it from the collection.  This puts the collection at 0 items, but then Kometa doesn't delete the collection at that point either.

I asked for support on Discord and Mr. Carrot recommended to start a github issue.  See the following discord chat:
https://discord.com/channels/822460010649878528/1355557587927568484

### Relevant Collection/Overlay/Playlist Definition

```yml

```

### Logs

https://gist.github.com/dweagle/e7040358bac827077fc16cdb96018df8

**Comment by YozoraXCII** [comment]
Just to clarify on one thing:

"This puts the collection at 0 items, but then Kometa doesn't delete the collection at that point either."

I have tested this and cannot reproduce it:
- Added a movie to a collection called "0 items"
- Verify the collection exists
- Go into the movie and remove the "0 items" collection tag
- Veryify the collection exists with 0 items
- Run the following YAML:
```
libraries:
  Movies:
    operations:
      delete_collections:
        less: 1
        managed: false             # i did not create it using Kometa
        configured: false          # the collection is not mentioned in my config file
```
- My "0 items" collection gets deleted as part of the run
