### ISSUE TITLE
Anilist Adult Tag does not resolve shows.

### ISSUE THREAD

**Issue by mon5termatt** [Kometa-Team/Kometa#2572]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

See https://discord.com/channels/822460010649878528/1351431575589355541 for history.

anonfawkes — 3/18/2025 4:58 AM
so this might be a @ Sohjiro issue. It seems the xml files dont include adult titles so they are failing to convert
actually
they do
they just dont have anilist ids attached
```
  "15918": {
    "tvdb_id": 393301,
    "tvdb_season": 1,
    "tvdb_epoffset": 0,
    "mal_id": 44524,
    "imdb_id": "tt13628870",
    "tmdb_show_id": 114477
  },
```
is for https://anilist.co/anime/127090/Harem-in-the-Labyrinth-of-Another-World/
yep. Can confirm after grabbing about 10 random anidb IDs from https://anilist.co/search/anime?sort=POPULARITY_DESC&adult=true and checking it against our anime list xml, they do not have anilist ID's. This would be something that soh would have to fix

### Relevant Collection/Overlay/Playlist Definition

```yml
  R18 Anime:
    anilist_search:
      adult: true
      sort_by: popular
    collection_order: custom
    sync_mode: sync
    sort_title: "!020-R18"
    collection_mode: hide
    visible_library: false
```
