### ISSUE TITLE
Languages default not working with position variable

### ISSUE THREAD

**Issue by antwanchild** [Kometa-Team/Kometa#2604]
### Version Number

2.2.0nightly

### What branch are you on?

nightly

### Describe the Bug

the position variable was created so that one could have 2 or 3 flags in one column, then another column with 2 or 3; was created as a queue.  
my code has always worked, because apparently that's the default, but when i try to change from top to bottom the variables are not pulled in.  It doesn't seem to matter if i use `vertical_position: bottom` or `vertical_align: bottom` within the position variable.  It seems as if the position queue either doesn't exist, or is broken.

### Relevant Collection/Overlay/Playlist Definition

```yml
    - default: languages        #spoken languages
      template_variables:
        position:         
        - vertical_position: top    
          horizontal_position: left
          vertical_offset: 223
          horizontal_offset: 15
        - vertical_offset: 284
        - vertical_offset: 345
    - default: languages      #subtitle languages
      template_variables:
        position:        
        - vertical_position: top
          horizontal_position: right
          vertical_offset: 223
          horizontal_offset: 15           #use 206 if doing as a 2nd column on left
        - vertical_offset: 284
        - vertical_offset: 345
        use_subtitles: true
```

**Comment by antwanchild** [comment]
https://discord.com/channels/822460010649878528/1037341842225762334/1038071948212699218 This is link to an older post where Bull, myself, and a couple others were talking about this and it did work at that time

**Comment by chazlarson** [comment]
default:
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
```
![Image](https://github.com/user-attachments/assets/67901f9e-ec51-49da-be1c-40b46a302ac3)
Make them horizontal:
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
```
![Image](https://github.com/user-attachments/assets/cb5011f9-3e49-49ae-b04b-1abc14c5b8e2)
Move them to the bottom:
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
        vertical_align: bottom
```
![Image](https://github.com/user-attachments/assets/fe8ed728-702f-4469-95e4-416392dbb73d)
That works, but it uses `vertical align`, which is shown in the default variables.  The table shows `vertical_position`.  Let's try that:
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
        vertical_position: bottom
```
![Image](https://github.com/user-attachments/assets/38e9edf2-b8b1-4916-aeec-587c9f953825)
On the bottom ignoring the default offset.  Maybe I need to add an offset?
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
        vertical_position: bottom
        vertical_offset: 105
        horizontal_offset: 10
```
![Image](https://github.com/user-attachments/assets/1108f570-e599-42b3-9cc8-4bdf893fb1c8)
Well that's not what we want.
Is it maybe these `initial_*` variables?
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
        vertical_position: bottom
        initial_vertical_offset: 105
        initial_horizontal_offset: 10
```
![Image](https://github.com/user-attachments/assets/e20750c3-0bed-4cf0-b4a2-a4c6c0bfbe2f)
If I now want to put a gap between them, seems like `horizontal_spacing` would do the trick:
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
        vertical_position: bottom
        initial_vertical_offset: 105
        initial_horizontal_offset: 10
        horizontal_spacing: 10
```
![Image](https://github.com/user-attachments/assets/8c3090d2-5929-463d-a2d2-ba2bfc10b84e)
Oh there's ten pixels of the US flag visible on the left, seems like "Controls the ... spacing from one overlay in the queue to the next" is relative to the left edge.
```yaml
libraries:
  One-Movie:
    reapply_overlays: true
    overlay_files:
    - default: languages
      template_variables:
        group_alignment: horizontal
        vertical_position: bottom
        initial_vertical_offset: 105
        initial_horizontal_offset: 10
        horizontal_spacing: 200 # 190 + 10 pixel gap
```
![Image](https://github.com/user-attachments/assets/7f8acee7-6186-405f-b2c8-5ce79d5dfb87)

Perhaps just a documentation issue, as none of this is particularly clear in the wiki.

Haven't tried `position` since that's undocumented.

What's the difference between `vertical_position` and `vertical _align`?  They seem to do mostly the same thing but one ignores the default offset.
