### ISSUE TITLE
[Docs]: Can't visualize the move_prefix example correctly

### ISSUE THREAD

**Issue by andrewter1** [Kometa-Team/Kometa#2642]
### What is the improvement or update to the Wiki you wish to see?

The example for the move_prefix attribute under Template Definitions is not showing the yaml example correctly. It should display like this:

```yaml
templates:
  Movies:
    move_prefix: The, A, An
    tmdb_collection: <<tmdb_id>>
    sort_title: <<collection_sort>>
    collection_order: release
collections:
  The Avengers:
    template:
      name: Movies
      tmdb_id: 86311
  Iron Man:
      template:
      name: Movies
      tmdb_id: 131292
```

### Does the docs page already exist? Please link to it.

https://kometa.wiki/en/latest/files/templates/
