### ISSUE TITLE
Hungarian Language not detected/processed in Language Flag Overlay

### ISSUE THREAD

**Issue by kriziw** [Kometa-Team/Kometa#2648]
### Version Number

2.1.0

### What branch are you on?

master

### Describe the Bug

When running the scheduled Kometa config it is not detecting/picking up the flag for the Hungian language, despite having the correct Language Tag in Plex.

### Relevant Collection/Overlay/Playlist Definition

```yml
Films:
    template_variables:
      use_separator: false
    operations:
      mass_audience_rating_update:
      - mdb_tomatoesaudience
      mass_critic_rating_update:
      - mdb_tomatoes
      mass_user_rating_update:
      - imdb
      mass_poster_update:
        seasons: true
        source: tmdb
      mass_background_update:
        seasons: true
        source: tmdb
    collection_files:
    - default: universe
    overlay_files:
    - default: commonsense
    - default: languages
    - default: resolution
    - default: runtimes
    - default: ratings
      template_variables:
        rating1: critic
        rating1_image: rt_tomato
        rating2: audience
        rating2_image: rt_popcorn
        rating3: user
        rating3_image: imdb
```

### Logs

https://gist.github.com/kriziw/0b44eebcb96883f739fd833eaa242d1a

**Comment by kriziw** [comment]
Example Movie:

![Image](https://github.com/user-attachments/assets/ef19b2cf-b140-44a8-9ed3-55c53b6752a1)

**Comment by muffn** [comment]
The default languages do not work as I expected, to solve this you can manually specify which languages you want flags to be included for.

Hungarian, among other languages such as Korean and Russian never get overlayed by default for me.

So you add something like this:

```yaml
    overlay_files:
      - default: languages
        template_variables:
          languages:
            - hu  # Hungarian
            - en  # English
            - fr  # French
            ...
```

All languages can be found here: https://kometa.wiki/en/latest/defaults/overlays/languages/#requirements-recommendations

That should fix it for you
