### ISSUE TITLE
Converting IMDB id is slow

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#267]
I have this template
```
IMDb Genre:
    default:
      title: feature
      limit: 100
    imdb_list:
    - url: https://www.imdb.com/search/title/?title_type=<<title>>&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>
      limit: <<limit>>
    - url: https://www.imdb.com/search/title/?title_type=<<title>>&user_rating=5.0,10.0&num_votes=100000,&genres=<<genre>>&sort=user_rating,desc
      limit: <<limit>>
    sort_title: ΩΩ1 <<collection_name>>
    sync_mode: sync
    collection_order: alpha
    name_mapping: "- Genres/<<collection_name>>"
```
and it is insanely slow compared to all my other collections. It takes about 15-20 minutes for one of these to run, and from looking at the output it looks like the IMDB id conversion is what takes time. Is there some way to speed this up? It takes more time for me to run the rest of my collections then it takes to run one IMDB collection, so it's kind of annoying having to literally spend hours for one refresh of my collection setup
