### ISSUE TITLE
[Docs]: The example for the ratings configuration is wrong/misleading.

### ISSUE THREAD

**Issue by romaswe** [Kometa-Team/Kometa#2677]
### What is the improvement or update to the Wiki you wish to see?

The example for the ratings configuration is wrong/misleading.

Now it states 
```
libraries:
  Movies:
    overlay_files:
      - default: network
        template_variables:
          rating1: critic
          rating2: audience
          rating3: user
          rating1_image: imdb
          rating2_image: rt_popcorn
          rating3_image: tmdb
    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
  TV Shows:
    overlay_files:
      - default: network
        template_variables:
          rating1: critic
          rating2: audience
          rating3: user
          rating1_image: imdb
          rating2_image: rt_popcorn
          rating3_image: tmdb
      - default: network
        template_variables:
          builder_level: episode
          rating1: critic
          rating2: audience
          rating1_image: imdb
          rating2_image: tmdb
    operations:
      mass_critic_rating_update: imdb
      mass_audience_rating_update: mdb_tomatoesaudience
      mass_user_rating_update: tmdb
      mass_episode_critic_rating_update: imdb
      mass_episode_audience_rating_update: tmdb
```

But this is configuration for rating,  so the field `- default: network` should be `- default: ratings`

### Does the docs page already exist? Please link to it.

https://kometa.wiki/en/latest/defaults/overlays/ratings/
