### ISSUE TITLE
AniList Error: Unknown argument "startDate_in" on field "media" of type "Page".

### ISSUE THREAD

**Issue by duncanlang** [Kometa-Team/Kometa#2702]
### Version Number

2.2.0

### What branch are you on?

master

### Describe the Bug

Getting this error when trying to use `anilist_search` with `start` and `end`

`AniList Error: Unknown argument "startDate_in" on field "media" of type "Page". Did you mean "startDate", "startDate_like", "status_in", "startDate_lesser", or "format_in"? |`

### Relevant Collection/Overlay/Playlist Definition

```yml
"'80s OVAs":
    anilist_search:
      format: ova
      start.after: 12/31/1979
      end.before: 01/01/1990
    sync_mode: sync
    collection_order: release
```

### Logs

https://gist.github.com/duncanlang/bbbbcc216630f069842e9d5ea6c53aa3
