### ISSUE TITLE
Grabbing incorrect poster

### ISSUE THREAD

**Issue by omerher** [Kometa-Team/Kometa#291]
I've been using the script for a while and it's been worked very well. Yesterday I tried moving over to docker, and ran it for the first time on docker (v1.10.0). It changed the posters to the collection poster instead of the movie poster. I tried running it on my regular install (v1.9.3) and it did the same thing.

Log file: https://pastebin.com/yYt7BntF

config.yml settings: 
```
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  sync_mode: append
  show_unmanaged: true
  show_filtered: false
  show_missing: false
  save_missing: true
  run_again_delay: 0
  assets_for_all: false
```
