### ISSUE TITLE
Feature Request: Automatically update metadata for shows/movies missing metadata.

### ISSUE THREAD

**Issue by efaden** [Kometa-Team/Kometa#294]
Would be nice to be able to search through movies with no summary, and tv shows with seasons named "Season #", episodes named "Episode #", or missing a summary and automatically refresh that meta data.  Also if this could be limited by age (episode age maybe for shows?).  The reason for this is that sometimes the metadata at tvdb/imdb/tmdb lags behind a show being added.  And since that data is blank, but it did match properly it won't automatically grab new meta data.

**Comment by snickers2k** [comment]
for now this is your best bet i guess: 
https://github.com/blacktwin/JBOPS/blob/master/utility/refresh_next_episode.py

**Comment by meisnate12** [comment]
so alot of people make a collection like this 

```yaml
collections:
  Refresh Recent Additions:
    build_collection: false
    item_refresh: true
    plex_search:
      all:
        added: 30
```
this will get every item added in the last 30 days and refresh it in plex

**Comment by meisnate12** [comment]
and for episodes if you grab the latest develop you can do this
```yaml
collections:
  Refresh Latest Episodes:
    collection_level: episode
    build_collection: false
    item_refresh: true
    plex_search:
      all:
        episode_added: 30
```
this will get every episode added in the last 30 days and refresh it in plex
