### ISSUE TITLE
Can't set Original Title on Show item

### ISSUE THREAD

**Issue by Soitora** [Kometa-Team/Kometa#3]
I followed the example, and the docs say it can (even though I know Agents can't normally)

```py
|====================================================================================================|
|                                      Series Library Metadata                                       |
|====================================================================================================|
|                                                                                                    |
|                                                                                                    |
|====================================================================================================|
|                                                                                                    |
| Updating Show: Avatar: The Last Airbender...                                                       |
| 'Show' object has no attribute 'originalTitle'                                                     |
|                                                                                                    |
|====================================================================================================|
```

`Series.yml`
```yml
metadata:
  "Avatar: The Last Airbender":
    sort_title: Avatar 01
    alt_title: The Last Airbender
    original_title: The Last Airbender
    seasons:
      1:
        title: "Book One: Water"
      2:
        title: "Book Two: Earth"
      3:
        title: "Book Three: Fire"
  "Avatar: The Legend of Korra":
    sort_title: Avatar 02
    alt_title: The Legend of Korra
    original_title: The Legend of Korra
    seasons:
      1:
        title: "Book One: Air"
      2:
        title: "Book Two: Spirits"
      3:
        title: "Book Three: Change"
      4:
        title: "Book Four: Balance"
```
