### ISSUE TITLE
No poster/background collection detail or asset folder found

### ISSUE THREAD

**Issue by JourneyOver** [Kometa-Team/Kometa#314]
Running the dev branch and it seems to no longer pick up any assets from the config/assets folder. Every collection just returns the message

```
No poster collection detail or asset folder found
No background collection detail or asset folder found
```

Nothing has changed between the last time I ran it (sometimes between release 1.9.1 and 1.9.2 (and it worked with the assets folder correctly)) and now other than me updating to the dev branch, and updating config stuff where needed.

my assets folder is setup as nested like example:

```
config
├── config.yml
├── Movies.yml
├── assets
│   ├── 47 Meters Down
│       ├── poster.png
│       ├── background.png
│       ├── 47 Meters Down - Uncaged (2019)
│           ├── poster.png
│           ├── background.png
│       ├── 47 Meters Down (2017)
│           ├── poster.png
│           ├── background.png
```

Here is the full log:
https://paste.ee/p/31dPQ

and here is my config

<details>
<summary>Details</summary>

```yml
libraries:
    Movies:
        metadata_path:
          - file: config/Movies.yml
settings:
    cache: true
    cache_expiration: 60
    asset_directory: config/assets
    asset_folders: true
    assets_for_all: false
    sync_mode: sync
    show_unmanaged: true
    show_filtered: false
    show_missing: true
    save_missing: true
    run_again_delay: 2
plex:
    url: http://127.0.0.1:32400
    token: {Redacted}
    timeout: 60
    clean_bundles: false
    empty_trash: false
    optimize: false
tmdb:
    apikey: {Redacted}
    language: en
omdb:
    apikey: {Redacted}
trakt:
    client_id: {Redacted}
    client_secret: {Redacted}
    authorization:
    # everything below is autofilled by the script
        access_token: {Redacted}
        token_type: Bearer
        expires_in: 7889237
        refresh_token: {Redacted}
        scope: public
        created_at: 1621883621
```

</details>

and Movies.yml

<details>
<summary>Details</summary>

```yml
  ###########################
  #        Templates        #
  ###########################

templates:
  Movie:
    optional:
      - collection
      - collection_trakt
      - extra_movie
      - summary
      - poster
      - background
    tmdb_collection: <<collection>>
    tmdb_summary: <<summary>>
    tmdb_movie: <<extra_movie>>
    trakt_list: <<collection_trakt>>
    url_poster: <<poster>>
    url_background: <<background>>
    sort_title: <<collection_name>>
    collection_order: release


  ###########################
  #        Collections      #
  ###########################

collections:
  ######################################################
  #                TMDB Collections                    #
  ######################################################

  47 Meters Down:
    template: {name: Movie, collection: 635922, summary: 635922}

  Alice in Wonderland:
    template: {name: Movie, collection: 261307, summary: 261307}

  Back to the Future:
    template: {name: Movie, collection: 264, summary: 264}

  Before:
    template: {name: Movie, collection: 123800, summary: 123800}

  Child's Play:
    template: {name: Movie, collection: 10455, extra_movie: 533642, summary: 10455}

  Deadpool:
    template: {name: Movie, collection: 448150, extra_movie: 567604, summary: 448150}

  Fantastic Beasts:
    template: {name: Movie, collection: 435259, summary: 435259}

  Final Destination:
    template: {name: Movie, collection: 8864, summary: 8864}

  Frozen:
    template: {name: Movie, collection: 386382, summary: 386382}

  Goosebumps:
    template: {name: Movie, collection: 508783, summary: 508783}

  Happy Death Day:
    template: {name: Movie, collection: 526380, summary: 526380}

  Harry Potter:
    template: {name: Movie, collection: 1241, summary: 1241}

  How to Train Your Dragon:
    template: {name: Movie, collection: 89137, summary: 89137}

  Independence Day:
    template: {name: Movie, collection: 304378, summary: 304378}

  It:
    template: {name: Movie, collection: 477962, summary: 477962}

  Jumanji:
    template: {name: Movie, collection: 495527, summary: 495527}

  Jurassic Park:
    template: {name: Movie, collection: 328, summary: 328}

  Maze Runner:
    template: {name: Movie, collection: 295130, summary: 295130}

  Men In Black:
    template: {name: Movie, collection: 86055}
    summary: Men in Black is a series of American science fiction action comedy films directed by Barry Sonnenfeld, and based on Malibu / Marvel comic book series The Men in Black by Lowell Cunningham.

  Pacific Rim:
    template: {name: Movie, collection: 363369, summary: 363369}

  Peter Rabbit:
    template: {name: Movie, collection: 595693, summary: 595693}

  Resident Evil:
    template: {name: Movie, collection: 17255, summary: 17255}

  Super Troopers:
    template: {name: Movie, collection: 449462, summary: 449462}

  The Secret Life of Pets:
    template: {name: Movie, collection: 427084, summary: 427084}

  Toy Story:
    template: {name: Movie, collection: 10194, summary: 10194}

  Transformers:
    template: {name: Movie, collection: 8650}
    summary: The Transformers series follows the continuing battle between the Autobots and the Decepticons and ultimately, the triumph of good over evil.

  Tremors:
    template: {name: Movie, collection: 91799, summary: 91799}

  Wreck-It Ralph:
    template: {name: Movie, collection: 404825, summary: 404825}

  Zombieland:
    template: {name: Movie, collection: 537982, summary: 537982}

  ######################################################
  #                Trakt Collections                    #
  ######################################################

  A Dog's Purpose:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/journey-over/lists/a-dog-s-purpose, summary: 591028}

  DC Extended Universe:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/tetharion/lists/worlds-of-dc}
    summary: The DC Extended Universe (DCEU) is a series of superhero films, distributed by Warner Bros. Pictures and based on characters that appear in American comic books by DC Comics. The shared universe, much like the original DC Universe in comic books and the television programs, was established by crossing over common plot elements, settings, cast, and characters.

  Marvel Cinematic Universe:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe}
    summary: The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films, independently produced by Marvel Studios and based on characters that appear in American comic books published by Marvel Comics. The franchise includes comic books, short films, television series, and digital series. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters. The first MCU film is Iron Man (2008), which began the films of Phase One culminating in the crossover film The Avengers (2012). Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015). Phase Three began with Captain America Civil War (2016) and concluded with Spider-Man Far From Home (2019). The first three phases in the franchise are collectively known as "The Infinity Saga". The films of Phase Four will begin with Black Widow (2021) and are set to conclude with Guardians of the Galaxy Vol. 3 (2023).

  The Conjuring Universe:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/zviznemte/lists/the-conjuring-universe-timeline}
    summary: The films present a dramatization of the real-life cases of Ed and Lorraine Warren, paranormal investigators and authors associated with prominent yet controversial cases of haunting. The main series follows their attempts to assist people who find themselves possessed by demonic spirits, while the spin-off films focus on the origins of some of the entities the Warrens have encountered.

  The MonsterVerse:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/journey-over/lists/monsterverse}
    summary: The Monsterverse is an American media franchise and shared fictional universe that is centered on a series of monster films featuring Godzilla and King Kong, distributed by Warner Bros. and produced by Legendary Entertainment in partnership with Toho.

```

</details>

**Comment by JourneyOver** [comment]
Well I've gotten it somewhat to work now, upon seeing `#307 to update item assets in a collection you now must use item_assets: true in the collection config`, it's updating the individual items in a collection, but it's still not updating the actual collections poster/background still with it just throwing the same message as above.

New Log:
https://paste.ee/p/18zmR

new Movies.yml:

<details>
<summary>Details</summary>

```yml
  ###########################
  #        Templates        #
  ###########################

templates:
  Movie:
    optional:
      - collection
      - collection_trakt
      - extra_movie
      - summary
      - poster
      - background
    tmdb_collection: <<collection>>
    tmdb_summary: <<summary>>
    tmdb_movie: <<extra_movie>>
    trakt_list: <<collection_trakt>>
    url_poster: <<poster>>
    url_background: <<background>>
    sort_title: <<collection_name>>
    collection_order: release
    item_assets: true


  ###########################
  #        Collections      #
  ###########################

collections:
  ######################################################
  #                TMDB Collections                    #
  ######################################################

  47 Meters Down:
    template: {name: Movie, collection: 635922, summary: 635922}

  Alice in Wonderland:
    template: {name: Movie, collection: 261307, summary: 261307}

  Back to the Future:
    template: {name: Movie, collection: 264, summary: 264}

  Before:
    template: {name: Movie, collection: 123800, summary: 123800}

  Child's Play:
    template: {name: Movie, collection: 10455, extra_movie: 533642, summary: 10455}

  Deadpool:
    template: {name: Movie, collection: 448150, extra_movie: 567604, summary: 448150}

  Fantastic Beasts:
    template: {name: Movie, collection: 435259, summary: 435259}

  Final Destination:
    template: {name: Movie, collection: 8864, summary: 8864}

  Frozen:
    template: {name: Movie, collection: 386382, summary: 386382}

  Goosebumps:
    template: {name: Movie, collection: 508783, summary: 508783}

  Happy Death Day:
    template: {name: Movie, collection: 526380, summary: 526380}

  Harry Potter:
    template: {name: Movie, collection: 1241, summary: 1241}

  How to Train Your Dragon:
    template: {name: Movie, collection: 89137, summary: 89137}

  Independence Day:
    template: {name: Movie, collection: 304378, summary: 304378}

  It:
    template: {name: Movie, collection: 477962, summary: 477962}

  Jumanji:
    template: {name: Movie, collection: 495527, summary: 495527}

  Jurassic Park:
    template: {name: Movie, collection: 328, summary: 328}

  Maze Runner:
    template: {name: Movie, collection: 295130, summary: 295130}

  Men In Black:
    template: {name: Movie, collection: 86055}
    summary: Men in Black is a series of American science fiction action comedy films directed by Barry Sonnenfeld, and based on Malibu / Marvel comic book series The Men in Black by Lowell Cunningham.

  Pacific Rim:
    template: {name: Movie, collection: 363369, summary: 363369}

  Peter Rabbit:
    template: {name: Movie, collection: 595693, summary: 595693}

  Resident Evil:
    template: {name: Movie, collection: 17255, summary: 17255}

  Super Troopers:
    template: {name: Movie, collection: 449462, summary: 449462}

  The Secret Life of Pets:
    template: {name: Movie, collection: 427084, summary: 427084}

  Toy Story:
    template: {name: Movie, collection: 10194, summary: 10194}

  Transformers:
    template: {name: Movie, collection: 8650}
    summary: The Transformers series follows the continuing battle between the Autobots and the Decepticons and ultimately, the triumph of good over evil.

  Tremors:
    template: {name: Movie, collection: 91799, summary: 91799}

  Wreck-It Ralph:
    template: {name: Movie, collection: 404825, summary: 404825}

  Zombieland:
    template: {name: Movie, collection: 537982, summary: 537982}

  ######################################################
  #                Trakt Collections                    #
  ######################################################

  A Dog's Purpose:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/journey-over/lists/a-dog-s-purpose, summary: 591028}

  DC Extended Universe:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/tetharion/lists/worlds-of-dc}
    summary: The DC Extended Universe (DCEU) is a series of superhero films, distributed by Warner Bros. Pictures and based on characters that appear in American comic books by DC Comics. The shared universe, much like the original DC Universe in comic books and the television programs, was established by crossing over common plot elements, settings, cast, and characters.

  Marvel Cinematic Universe:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe}
    summary: The Marvel Cinematic Universe (MCU) is an American media franchise and shared universe centered on a series of superhero films, independently produced by Marvel Studios and based on characters that appear in American comic books published by Marvel Comics. The franchise includes comic books, short films, television series, and digital series. The shared universe, much like the original Marvel Universe in comic books, was established by crossing over common plot elements, settings, cast, and characters. The first MCU film is Iron Man (2008), which began the films of Phase One culminating in the crossover film The Avengers (2012). Phase Two began with Iron Man 3 (2013) and concluded with Ant-Man (2015). Phase Three began with Captain America Civil War (2016) and concluded with Spider-Man Far From Home (2019). The first three phases in the franchise are collectively known as "The Infinity Saga". The films of Phase Four will begin with Black Widow (2021) and are set to conclude with Guardians of the Galaxy Vol. 3 (2023).

  The Conjuring Universe:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/zviznemte/lists/the-conjuring-universe-timeline}
    summary: The films present a dramatization of the real-life cases of Ed and Lorraine Warren, paranormal investigators and authors associated with prominent yet controversial cases of haunting. The main series follows their attempts to assist people who find themselves possessed by demonic spirits, while the spin-off films focus on the origins of some of the entities the Warrens have encountered.

  The MonsterVerse:
    template: {name: Movie, collection_trakt: https://trakt.tv/users/journey-over/lists/monsterverse}
    summary: The Monsterverse is an American media franchise and shared fictional universe that is centered on a series of monster films featuring Godzilla and King Kong, distributed by Warner Bros. and produced by Legendary Entertainment in partnership with Toho.
```

</details>
