### ISSUE TITLE
Feature Request: Metadata\Collection presets

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#359]
I have a lot of simple one-off metadata changes and duplicate collection entries.

A good example for the metadata would be **episode_ordering: tvdb_aired**. My YML ends up looking like this:
```
metadata:
  "show1":
    episode_ordering: tvdb_aired
  "show2":
    episode_ordering: tvdb_aired
  "show3":
    episode_ordering: tvdb_aired
  "show4":
    episode_ordering: tvdb_aired
  ...
```

Specifically for the metadata issue, it would be nice to do something like this instead:
```
presets(or whatever):
  "preset_name":
    episode_ordering: tvdb_aired
    apply_to:
      - show1
      - show2
      - show3
      - show4
```
**edit:** The apply_to might also need to mention shows/collections to differentiate between which one it should apply to in the case where you have a show and collection with the same name

 ̶A̶n̶d̶ ̶s̶o̶m̶e̶t̶h̶i̶n̶g̶ ̶l̶i̶k̶e̶ ̶t̶h̶i̶s̶ ̶f̶o̶r̶ ̶t̶h̶e̶ ̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶s̶ ̶(̶o̶r̶ ̶m̶e̶t̶a̶d̶a̶t̶a̶,̶ ̶a̶l̶t̶h̶o̶u̶g̶h̶ ̶I̶D̶K̶ ̶w̶h̶a̶t̶ ̶t̶h̶a̶t̶ ̶e̶x̶a̶m̶p̶l̶e̶ ̶w̶o̶u̶l̶d̶ ̶b̶e̶)̶.̶.̶.̶
 ```
 ̶p̶r̶e̶s̶e̶t̶s̶(̶o̶r̶ ̶w̶h̶a̶t̶e̶v̶e̶r̶)̶:̶
̶ ̶ ̶"̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶_̶d̶e̶f̶a̶u̶l̶t̶"̶:̶
̶ ̶ ̶ ̶ ̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶_̶m̶o̶d̶e̶:̶ ̶h̶i̶d̶e̶_̶i̶t̶e̶m̶s̶
̶ ̶ ̶"̶l̶a̶b̶e̶l̶1̶-̶2̶_̶s̶y̶n̶c̶"̶:̶
̶ ̶ ̶ ̶ ̶l̶a̶b̶e̶l̶:̶
̶ ̶ ̶ ̶ ̶ ̶ ̶-̶ ̶L̶a̶b̶e̶l̶1̶
̶ ̶ ̶ ̶ ̶ ̶ ̶-̶ ̶L̶a̶b̶e̶l̶2̶
̶ ̶ ̶ ̶ ̶i̶t̶e̶m̶_̶l̶a̶b̶e̶l̶.̶s̶y̶n̶c̶:̶
̶ ̶ ̶ ̶ ̶ ̶ ̶-̶ ̶L̶a̶b̶e̶l̶1̶
̶ ̶ ̶ ̶ ̶ ̶ ̶-̶ ̶L̶a̶b̶e̶l̶2̶
̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶s̶:̶
̶ ̶ ̶"̶C̶o̶l̶l̶e̶c̶t̶i̶o̶n̶1̶"̶:̶
̶ ̶ ̶ ̶ ̶e̶x̶t̶e̶n̶d̶s̶:̶
̶ ̶ ̶ ̶ ̶ ̶ ̶-̶ ̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶_̶d̶e̶f̶a̶u̶l̶t̶
̶ ̶ ̶ ̶ ̶ ̶ ̶-̶ ̶"̶l̶a̶b̶e̶l̶1̶-̶2̶_̶s̶y̶n̶c̶"̶
̶ ̶ ̶ ̶ ̶.̶.̶.̶
```

 ̶T̶h̶i̶s̶ ̶w̶o̶u̶l̶d̶ ̶c̶u̶t̶ ̶d̶o̶w̶n̶ ̶a̶ ̶l̶o̶t̶ ̶o̶f̶ ̶t̶h̶e̶ ̶d̶u̶p̶l̶i̶c̶a̶t̶e̶ ̶e̶n̶t̶r̶i̶e̶s̶,̶ ̶a̶n̶d̶ ̶w̶i̶t̶h̶ ̶s̶o̶m̶e̶t̶h̶i̶n̶g̶ ̶l̶i̶k̶e̶ ̶t̶h̶e̶ ̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶_̶d̶e̶f̶a̶u̶l̶t̶ ̶y̶o̶u̶ ̶c̶o̶u̶l̶d̶ ̶e̶a̶s̶i̶l̶y̶ ̶u̶p̶d̶a̶t̶e̶ ̶a̶l̶l̶ ̶y̶o̶u̶r̶ ̶c̶o̶l̶l̶e̶c̶t̶i̶o̶n̶s̶ ̶w̶i̶t̶h̶ ̶a̶ ̶1̶ ̶l̶i̶n̶e̶ ̶e̶d̶i̶t̶.̶

**Comment by meisnate12** [comment]
i mean for collections what your asking for is [templates](https://github.com/meisnate12/Plex-Meta-Manager/wiki/Template-Attributes) right?

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Yeah, maybe... Can you use multiple templates with a single collection? The examples I'm seeing don't show that

If so I'll have to dig in to that, and the folder import stuff later this weekend

**Comment by meisnate12** [comment]
yes you can use multiple templates for a collection

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Alright, well then the second half of this request shouldn't be relevant.

That would just be like:
```
collections:
  Action:
    template:
      - {name: template1 }
      - {name: template2 }
```

**Comment by meisnate12** [comment]
yup exactly

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
If we took a similar approach with templates for metadata, it wouldn't really be making anything easier or cleaner in my example.

replacing
```
episode_ordering: tvdb_aired
```
with
```
template: {name: tvdb_aired}
```
it's pretty much saying the same thing. I'd still have the duplicated template attributes

**Comment by zpz5HAU-tgc3fgw2xwr** [comment]
Ideally how I see myself using this would be creating a separate YML file TVDB_Aired.yml, and just throwing the shows that need this particular fix in the list

**Comment by meisnate12** [comment]
is there a way you could do it dynamically? I can think of one way off bat. 

Use a plex search that will pull in the movies you want and edit the items that way.
```yaml
collections:
  TVDB Aired:
    plex_search:
      any:
        title:
          - Item Name 1
          - Item Name 2
    item_episode_ordering: tvdb_aired
    build_collection: false
```
