### ISSUE TITLE
Bug: config.yml removing (some) commented out settings

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#373]
Probably related to #363 

**Describe the Bug**
If I want to run things quickly for a test, I'll do something like this to my config.yml
```
libraries:
  Shows:
    metadata_path:
      # - folder: config/shows/quickfixes
      # - folder: config/shows/series
      # - folder: config/shows/collections
      - folder: config/shows
  # Movies:
  #   metadata_path:
  #     - folder: config/movies/quickfixes
  #     - folder: config/movies/collections
  #     - folder: config/movies
  # Music Videos:
  #   metadata_path:
  #     - folder: config/music-videos/artists
  #     - folder: config/music-videos
settings:
```

after being run, it deleted my movies and music videos sections, but left the commented out sections under the shows library
```
libraries:
  Shows:
    metadata_path:
      # - folder: config/shows/quickfixes
      # - folder: config/shows/series
      # - folder: config/shows/collections
      - folder: config/shows
settings:
```

**Plex Meta Manager Info**
Version: 1.12.1
