### ISSUE TITLE
Am I doing Genre's right?

### ISSUE THREAD

**Issue by Tharic99** [Kometa-Team/Kometa#38]
So I'm following your setup for Genre's, but I tweaked it some. I'm just wondering if I'm doing something wrong or not

When I look at my Plex and change my view to filter by a Genre of "Thriller", I have 461 movies. 

However, my Thriller genre collection only has 62 movies in it.

Here's the settings I'm using for Thriller
```
  Thriller:
    imdb_list:
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=thriller
      limit: 100
    - url: https://www.imdb.com/search/title/?title_type=feature&release_date=1990-01-01,&user_rating=5.0,10.0&num_votes=100000,&genres=thriller&sort=user_rating,desc
      limit: 100
    sort_title: ++_Thriller
    sync_mode: append
    summary: Thriller Film is a genre that revolves around anticipation and suspense. The aim for Thrillers is to keep the audience alert and on the edge of their seats. The protagonist in these films is set against a problem an escape, a mission, or a mystery. No matter what sub-genre a Thriller film falls into, it will emphasize the danger that the protagonist faces. The tension with the main problem is built on throughout the film and leads to a highly stressful climax.
    collection_order: alpha
    plex_search:
      genre: Thriller 
```

I added the plex_search genre Thriller as well, thinking that it would just be easier to pull everything from the Thriller genre of Plex into the Thriller collection, but that's not what I'm seeing happen for some reason.
