### ISSUE TITLE
Bug: IndexError: list index out of range

### ISSUE THREAD

**Issue by Fribb** [Kometa-Team/Kometa#381]
**Describe the Bug**
I wanted to create a collection in my Anime Library with a plex_search for titles.
That collection is not being created because of an error in the `conver.py` file, `IndexError: list index out of range` (see log below).

**Relevant Collection Config**
the config for the collection that should be created.
```
collections:
  Accel_World_Collection:
   plex_search:
     title: Accel World
   build_collection: true
```

**Plex Meta Manager Info**
- Version: 1.12.1

**Link to logs (required)**
https://gist.github.com/Fribb/2efaac0556aa664374abfbbabc672494

As a further note, I think the creation of the mapping is only necessary when integrations for MyAnimeList, AniDB etc are actually used and that maybe those mappings should only be run if the configuration actually contains those configurations.

Additionally, it would be good if critical errors or errors in general, would be "posted" while running `python plex_meta_manager.py -r` so that errors like this are noticed sooner.
