### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by Shayne55434** [Kometa-Team/Kometa#387]
**Describe the Bug**
The series "24" is not recognized by PMM. I am curious if it's because PMM sees it as an int and not a string. The command I am using is:
`sudo docker exec -it pmm python plex_meta_manager.py --library "TV Shows" --collections "24"`

**Relevant Collection Config**
```
collections:
  24:
    tmdb_show: 1973
    item_assets: true
    build_collection: false
```

**Plex Meta Manager Info**
Version: 1.12.0 

**Link to logs (required)**
Collection log for "24" is not generated at all. Meta log shows nothing.

https://gist.github.com/Shayne55434/85e62d32ecf69f4ea05b10367707f3ce
