### ISSUE TITLE
Feature Request: expose "total_plays" and "users_watched" filters to Tautulli builders

### ISSUE THREAD

**Issue by burkasaurusrex** [Kometa-Team/Kometa#441]
Been a while man, great work on the rewrite. Just ported all my config over. Freaking slaps.

**Is your feature request related to a problem? Please describe.**
If you request a list large enough from Tautulli, it will return media that is technically "popular" but only has one play or one user watched.

**Describe the solution you'd like**
It would be cool if you could cut off the lists on some set "total_plays" (for "tautulli_watched" builders) or "users_watched" (for "tautulli_popular" builder). It looks like both attributes are included in the Tautulli API call.

Maybe something like:
```yaml
collections:
  Most Popular Movies (30 Days):
    sync_mode: sync
    tautulli_popular:
      list_days: 30
      list_size: 10
      users_watched.gte: 2
```

**Describe alternatives you've considered**
I was hoping there would be an attribute for this on the Tautulli API, but it looks like it would have to be build to screen after the call
