### ISSUE TITLE
Bug: Invalid library section ID %d passed to Plex

### ISSUE THREAD

**Issue by MartinCa** [Kometa-Team/Kometa#449]
**Describe the Bug**
When adding the collection to Plex, Plex Meta Manager fails with the following in the log:
`plexapi.exceptions.BadRequest: (500) internal_server_error; http://192.168.1.10:32400/library/sections/None/all?collection%5B0%5D.tag.tag=The+Bourne&collection.locked=1&id=799&type=1 <html><head><title>Internal Server Error</title></head><body><h1>500 Internal Server Error</h1></body></html>`

In Plex logs I can see the following:
```
Nov 23, 2021 18:10:08.169 [0x1481c0bb6b38] DEBUG - Request: [192.168.1.10:35910 (Allowed Network (Subnet))] PUT /library/sections/None/all?collection%5B0%5D.tag.tag=The+Bourne&collection.locked=1&id=799&type=1 (6 live) GZIP Signed-in Token ()
Nov 23, 2021 18:10:08.170 [0x1481c0bb6b38] ERROR - FATAL ERROR: Log: Error handling format string 'Invalid library section ID %d passed.': invalid type specifier
Nov 23, 2021 18:10:08.170 [0x1481c0bb6b38] ERROR - Exception handled: Log: Error handling format string 'Invalid library section ID %d passed.': invalid type specifier
Nov 23, 2021 18:10:08.170 [0x1481c2f40b38] DEBUG - Completed: [192.168.1.10:35910] 500 PUT /library/sections/None/all?collection%5B0%5D.tag.tag=The+Bourne&collection.locked=1&id=799&type=1 (6 live) GZIP 0ms 405 bytes (pipelined: 437)
```

**Relevant Collection Config**
```
templates:
  Collection:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
    smart_label: random
  Best of:
    trakt_list: https://trakt.tv/users/lish408/lists/rotten-tomatoes-best-of-<<year>>
    sort_title: +1_Best of <<year>>
    sync_mode: sync
    summary: Rotten Tomatoes Best Movies of <<year>>
    smart_label: audience_rating.desc
collections:
(...)
  The Bourne:
    template: {name: Collection, collection: 31562}
```

**Plex Meta Manager Info**
- Version: 1.12.2-develop1115

**Link to logs (required)**
- https://gist.github.com/MartinCa/4a42df6e60bda336a90c36900023196d
