### ISSUE TITLE
Feature Request: Nested collections

### ISSUE THREAD

**Issue by CherryKitten** [Kometa-Team/Kometa#467]
**Is your feature request related to a problem? Please describe.**
I have some collections that basically are collections of collections. At the moment, I create the meta collection by doing a plex_searrch for the other collections.

**Describe the solution you'd like**
A way to nest collections, so that the collections on the lower level will be created as usual, and then every release in those collections will automatically be added to the upper level collection.

**Additional context**

Little example of a set of collections I have right now:

```
collections:
  Godzilla (Showa):
    tmdb_collection_details: 374509
  Godzilla (Heisei):
    tmdb_collection_details: 374511
  Godzilla (Millenium):
    tmdb_collection_details: 374512
  Godzilla (Reiwa):
    tmdb_collection_details: 
      - 691555
      - 535790
  Godzilla (Anime):
    tmdb_collection_details: 535790
  Godzilla (US Versions):
    tmdb_collection_details: 813157
  Godzilla: 
    plex_search:
      any:
        title: "Godzilla"
        collection: 
          - Godzilla (Showa)
          - Godzilla (Heisei)
          - Godzilla (Millenium)
          - Godzilla (Reiwa)
          - Godzilla (Anime)
          - Godzilla (US Versions)
```

With this feature request implemented, it would be possible to do it in a (in my opinion) cleaner way:

```
collections:
  Godzilla:
    plex_search:
      any:
        title: "Godzilla"
    collections:
      Godzilla (Showa):
        tmdb_collection_details: 374509
      Godzilla (Heisei):
        tmdb_collection_details: 374511
      Godzilla (Millenium):
        tmdb_collection_details: 374512
      Godzilla (Reiwa):
        tmdb_collection_details: 
          - 691555
          - 535790
      Godzilla (Anime):
        tmdb_collection_details: 535790
      Godzilla (US Versions):
        tmdb_collection_details: 813157
```
