### ISSUE TITLE
Unknown Error: 'CommentedMap' object has no attribute 'decode'

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#473]
```
|================================= Validating True-Crime Attributes =================================|
| Unknown Error: 'CommentedMap' object has no attribute 'decode' 
```

------
config:
```
  True-Crime:
    template: {name: Genre}
    imdb_list: https://www.imdb.com/search/title/?title_type=tv_special,documentary,video&genres=documentary&keywords=true-crime
    url_poster: https://github.com/snickers2k/public/blob/main/23423153454352435423535.png
    trakt_list:
      - url: https://trakt.tv/users/bagpussthe2nd/lists/true-crime-documentaries
      - url: https://trakt.tv/users/willowwwendy/lists/true-crime
      - url: https://trakt.tv/users/lish408/lists/true-crime-documentary-series-film
      - url: https://trakt.tv/users/tkreimark91/lists/true-crime
      - url: https://trakt.tv/users/kaybadkins/lists/true-crime
```
template:
```
    Genre:
        plex_search:
          genre: <<genre>>
        url_poster: <<poster>>
        sort_title: +++++++_<<collection_name>>
        collection_order: alpha
```

**Comment by meisnate12** [comment]
Can you post you meta.log for this or hop on discord and privately send it to me there if it being public worries you

**Comment by snickers2k** [comment]
of course, sorry.
from the other issue: ----

**Comment by meisnate12** [comment]
ok we will just chat here.

1. `'CommentedMap' object has no attribute 'decode'` is happening because trak_list doesn't use the `url:` style I'm going to add a message in saying as much 
2. `int() argument must be a string, a bytes-like object or a number, not 'tuple'` is happening because you updated PMM and didn't reinstall the requirements and update them 
3. You're not really using templates rights. You have url_poster in both the template and the collection you should just pass it in like so 
```yaml
  True-Crime:
    template:
      name: Genre
      poster: https://github.com/snickers2k/public/blob/main/23423153454352435423535.png
    imdb_list: https://www.imdb.com/search/title/?title_type=tv_special,documentary,video&genres=documentary&keywords=true-crime
    trakt_list:
      - https://trakt.tv/users/bagpussthe2nd/lists/true-crime-documentaries
      - https://trakt.tv/users/willowwwendy/lists/true-crime
      - https://trakt.tv/users/lish408/lists/true-crime-documentary-series-film
      - https://trakt.tv/users/tkreimark91/lists/true-crime
      - https://trakt.tv/users/kaybadkins/lists/true-crime
```
The `poster` attribute under template replaces `<<poster>>` in the template 

4. I noticed you have a lot of `Plex Error: genre: Gangster not found` in your logs basically `Gangster` isn't a Genre in plex so the plex_search is failing you might consider removing `plex_search:  genre: <<genre>>` from the template or if your not really sure how the templates work i would just make each collection. 
Going further i can see you have many many collections with lots of errors i would consider looking through and seeing if its doing what you want it to
