### ISSUE TITLE
Feature Request:  Plex-Automatic-Preroll

### ISSUE THREAD

**Issue by almulder** [Kometa-Team/Kometa#486]
I would love to see if you could incorporate Plex-Automatic-Preroll into your setup. 

https://github.com/TheHumanRobot/Plex-Automatic-Preroll

as for the life of me it keeps failing on unraid and unable to get it to run.  I even tried to add it to your setup in the docker yet it keeps erroring out with one thing after another.

Hoped you could make it work so it could just be included so its all running togethere.

**Comment by meisnate12** [comment]
I added `server_preroll` as a collection detail so you can schedule whatever string you want to be sent to the `Movie pre-roll video` Text box in Plex under Settings -> Extras. You can create a collection to change it like this:

```yaml
collections:
  dec change preroll:
    build_collection: false
    server_preroll: //path/to/video.mp4;//second/path/video.mp4
    schedule: range(12/01-12/31) # will run for all of december
```
