### ISSUE TITLE
Add label attributes to collections

### ISSUE THREAD

**Issue by PleaseStopAsking** [Kometa-Team/Kometa#49]
From reviewing the documentation, there is not currently a way to set labels at the collection level, only at the item level (show or movie). When using managed users and labels to control what users can access, they are not able to see collections by default unless their accounts are added as a label to each collection.

It would be nice to be able to add the labels as a collection details attribute so we could recreate their access programatically.

**Example:**

```
collections:
  3 Ninjas:
    collection_order: release
    label: 
      - user01
      - user02
    label_sync_mode: sync
    tmdb_collection_details: 71458
    url_background: null
    url_poster: https://www.themoviedb.org/t/p/original/kTRDNxSlNSE7n9cF9W2xx9frs3d.jpg
```
