### ISSUE TITLE
Bug: KeyError: 'collectionSort' -- Error: 1 not found in ['collectionMode']

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#496]
```
[2021-12-10 00:30:19,463] [util.py:206]               [INFO]     |============================= Updating Details of Trending Collection ==============================|
[2021-12-10 00:30:19,463] [builder.py:2030]           [INFO]     |                                                                                                    |
[2021-12-10 00:30:19,463] [builder.py:2037]           [INFO]     | Detail: summary updated Collection Summary                                                         |
[2021-12-10 00:30:19,463] [builder.py:2070]           [INFO]     | Detail: sort_title updated Collection Sort Title to ++++++++++++++++1_1_Trending                   |
[2021-12-10 00:30:19,516] [util.py:152]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/plexapi/mixins.py", line 38, in editAdvanced
                                                                 |     pref = preferences[settingID]
                                                                 | KeyError: 'collectionSort'
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "./plex_meta_manager.py", line 713, in run_collection
                                                                 |     builder.update_details()
                                                                 |   File "/opt/Plex-Meta-Manager/modules/builder.py", line 2087, in update_details
                                                                 |     self.library.collection_order_query(self.obj, self.details["collection_order"])
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/retrying.py", line 206, in call
                                                                 |     return attempt.get(self._wrap_exception)
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/usr/lib/python3/dist-packages/six.py", line 703, in reraise
                                                                 |     raise value
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "/opt/Plex-Meta-Manager/modules/plex.py", line 332, in collection_order_query
                                                                 |     collection.sortUpdate(sort=data)
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/plexapi/collection.py", line 237, in sortUpdate
                                                                 |     self.editAdvanced(collectionSort=key)
                                                                 |   File "/home/snikay/.local/lib/python3.8/site-packages/plexapi/mixins.py", line 40, in editAdvanced
                                                                 |     raise NotFound('%s not found in %s' % (value, list(preferences.keys())))
                                                                 | plexapi.exceptions.NotFound: 1 not found in ['collectionMode']
                                                                 | 
[2021-12-10 00:30:19,517] [plex_meta_manager.py:750]  [ERROR]    | Unknown Error: 1 not found in ['collectionMode']
```

```
templates:
    Top:
        sync_mode: sync  
        smart_label: critic_rating.desc
        url_poster: <<poster>>
        collection_order: custom
        radarr_add: true
```

```
  Trending:
    template: {name: Top, poster: https://theposterdb.com/api/assets/169001}
    smart_label: year.desc
    trakt_trending: 50
    tmdb_trending_daily: 20
    tmdb_trending_weekly: 50
    summary: Top Trending Movies across the internet
    sort_title: ++++++++++++++++1_1_Trending 
    url_background: https://i.imgur.com/SOVfrIq.png
    radarr_tag: pmm, trending
```

using latest developing
