### ISSUE TITLE
Feature Request: Episode collections from IMDB

### ISSUE THREAD

**Issue by iamwoz** [Kometa-Team/Kometa#515]
**Is your feature request related to a problem? Please describe.**
Episode collections are supports on Trakt but not IMDB. Thanks so much for all the work on this tool, its the one thing keeping me on Plex :-)

**Describe the solution you'd like**
Please enable episode collection support on IMDB

**Describe alternatives you've considered**
N/A

**Additional context**
Here is the collection config I'm trying to use:
```yaml
The Simpsons Top 100 Episodes:
    collection_order: custom
    collection_level: episode
    sync_mode: sync
    imdb_list:
      url: https://www.imdb.com/search/title/?series=tt0096697&sort=user_rating,desc&count=100&view=advanced
      limit: 100
    summary: The top 100 Simpsons episodes by IMDB user rating
    sonarr_add: false
    radarr_add: false
    sonarr_search: false
    sonarr_monitor: all
```
