### ISSUE TITLE
Feature Request: I'd like to see a way to publish various collections on the home screen for a set number of days.

### ISSUE THREAD

**Issue by gstevenking** [Kometa-Team/Kometa#520]
**Is your feature request related to a problem? Please describe.**
Similar to how Netflix has lists you can scroll through, I'd like to do this with Plex so users might be presented with an option they hadn't considered before.

**Describe the solution you'd like**
I'd like to be able to either have a random collection assigned to the screen for a set period of time, or a list of collections that could change on a rotating basis

**Describe alternatives you've considered**
I can make it work on a limited basis using a method similar to the holiday collections that are able to be pinned to the home screen. I have a list of collections and gave them all a date range. My biggest issues are how they are ordered since you can only use custom sorting on one collection, and how to have them change out. Currently I have dates ranges attached to each one.

**Comment by snickers2k** [comment]
isn't this already possible?

```
  some-template-name:
    smart_label: title.asc
    sort_title: ++0_<<collection_name>>
    schedule: range(<<start_date>>-<<end_date>>)
    delete_not_scheduled: true
    visible_home: true
    visible_shared: true
    visible_library: true
```
