### ISSUE TITLE
Bug: if Notifiarr is down then the entire run dies / fails

### ISSUE THREAD

**Issue by bakerboy448** [Kometa-Team/Kometa#529]
**Describe the Bug**
If Notifiarr (or any webhook???) is down or fails then the whole run fails;  trimmed out some spew

```
```
     Version: 1.13.3-develop1217                                                                    |
|====================================================================================================|
|                                            Starting Run                                            |
|==============================================================================================[...]
| Connecting to Notifiarr...                                                                         |
| Expecting value: line 1 column 1 (char 0)                                                          |
                                Finished Run                                            |
|                                         Run Time: 0:00:00                                    
```
```

**Relevant Collection Config**
N/A

**Plex Meta Manager Info**
1.13.3-develop1217

**Link to logs (required)**
https://gist.github.com/bakerboy448/278f0819abc1111d36fdb8d46bac48fb

**Comment by bakerboy448** [comment]
pulled the fix; not quite there

https://gist.github.com/bakerboy448/b08d93605cddbd1587a9edd171d52789

```yml
webhooks:
  collection_changes: notifiarr
  error: notifiarr
  run_end: notifiarr
  run_start: notifiarr
notifiarr:
  apikey: (removed)
  develop: true
```

bug note: notifiarr is currently down
