### ISSUE TITLE
Bug: filter tag ignored by radarr_add

### ISSUE THREAD

**Issue by palla89** [Kometa-Team/Kometa#531]
**Describe the Bug**
Filter tag is matched but ignored from radarr_add option.
I add a filter for genre as you can see in the config below, so that I can get only the 'animation' movies in the collection, but it still adds every movie to radarr, ignoring the genre tag even if no error is found.
you can see in the playlist that some of the other movies are already in radarr, this is because they were already present from other libraries. Otherwise, PMM would have sent all the movies to Radarr.

Am I using it in a bad way? 

I'd just want that the collection get filtered and only the Animation movies will be added to playlist. 

**Relevant Collection Config**
```
Top Animation Pirated Weekly:
    template: {name: Chart Alpha, num: 1}
    trakt_list:
      - https://trakt.tv/users/linaspurinis/lists/top-10-pirated-movies-of-the-week?sort=rank,asc
    summary: These are the top  most pirated animated movies in the last week
    radarr_add: true
    radarr_search: true
    schedule: daily
    filters:
      genre: Animazione
```

**Plex Meta Manager Info**
Version: 1.13.3-develop1217

**Link to logs (required)**
https://gist.github.com/palla89/ba22a3edc41d10d695945575b3c70e30
