### ISSUE TITLE
Feature Request: tmdb_XY_details should not crawl movies?

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#543]
I thought tmdb_XY_details is just for using  the details 
instead it is even crawling the movies aswell

So my example is that i want to create a few Standup Collections; with the tmdb-details for poster/background/summery (excluding movies), but the items/movies specified in tmdb_discover to avoid feature-films. 

poster/background/summery ---> details only (requested)
vs
poster/background/summery/movies ---> details + movies + everything (right now)

If this is absolutely intended, my other request for "global filters" could fix this behavior aswell, i guess.

thx

**Comment by meisnate12** [comment]
so im not gonna add an attribute for this but you can just do 

```yaml
collections:
  TMDB COllection:
    tmdb_discover:
      discover stuff
    tmdb_poster: <ID_OF_MOVIE_OR_COLLECTION>
    tmdb_background: <ID_OF_MOVIE_OR_COLLECTION>
    tmdb_summary: <ID_OF_MOVIE_OR_COLLECTION>
```

my bigger question is why you want some tmdb collection summary, poster, and background for your standup collection
