### ISSUE TITLE
Bug: dictionary_variables not working

### ISSUE THREAD

**Issue by benfishbus** [Kometa-Team/Kometa#558]
**Describe the Bug**
TMDb Collections are not updated with posters specified in the dictionary_variables of a custom template.

**Relevant Collection Config**
```
libraries:                                      # Library mappings must have a colon (:) placed after them
  Movies Main:
    metadata_path:
      - file: config/labelMovies.yml
      - file: config/Movies.yml
      - file: config/complexDocumentary.yml
    operations:
      tmdb_collections:
        dictionary_variables:
          poster:
            my_collection_poster:
              920666: https://theposterdb.com/api/assets/30438
              687929: https://www.themoviedb.org/t/p/original/pxaOzqzfZfDQRGIif7OfZkhayye.jpg
              33938: https://theposterdb.com/api/assets/25081
        template:
          optional:
            - poster
          tmdb_collection_details: <<collection_id>>
          collection_order: release
          url_poster: <<my_collection_poster>>
```

**Plex Meta Manager Info**
Version: 1.14.1

**Link to logs (required)**
https://gist.github.com/benfishbus/153873872bf832d275342d6ab0002739

**Comment by meisnate12** [comment]
this ones my bad i messed up when writing the wiki that's not how it should look 

```yaml
library:
  Movies:
    operations:
      tmdb_collections:
        exclude_ids:
          - 10
        remove_suffix: Collection
        dictionary_variables:
          my_collection_poster:
            119: https://www.themoviedb.org/t/p/original/oENY593nKRVL2PnxXsMtlh8izb4.jpg
            531241: https://www.themoviedb.org/t/p/original/nogV4th2P5QWYvQIMiWHj4CFLU9.jpg
        template:
          optional:
            - my_collection_poster
          tmdb_collection_details: <<collection_id>>
          collection_order: release
          url_poster: <<my_collection_poster>>
```
