### ISSUE TITLE
Bug:  Pre-Rolls no longer updating in v1.14.x (Works in v1.13.3)

### ISSUE THREAD

**Issue by almulder** [Kometa-Team/Kometa#562]
**Describe the Bug**
The prerolls have been updating correctly, however sometime between 12/24 and now they have stopped updating, seems like something in the new builds have broken this feature. (or plex update broke this)

**Relevant Collection Config**
my movies.yml file has not been changed, the only thing that has changed is the docker had been updated

**Plex Meta Manager Info**
Version: 1.14.1 

**Link to logs (required)**
log shows it should have been added but did not.
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/7809394/meta.log)

**Comment by almulder** [comment]
Can confirm that in 1.14.0 and 1.14.1 this feature is broken, I have downgraded docker to 1.13.3 and it works again. Upgraded and it no longer works, downgraded again and it works. 

v1.13.3 Log
[meta.log](https://github.com/meisnate12/Plex-Meta-Manager/files/7809476/meta.log)

**Comment by meisnate12** [comment]
should be fixed in develop

**Comment by pcmv-dev** [comment]
It is working in develop1522 but it does not respect templates

**Comment by meisnate12** [comment]
can you elaborate what you mean?

**Comment by pcmv-dev** [comment]
It will ignore the schedule when done this way
```
templates:
  Prerolls:
    build_collection: false
    server_preroll: <<videos>>
collections:
  Spring:
    template:
      name: Prerolls
      schedule: range(03/01-05/31)
      videos: "/preroll/spring.mp4"
  Summer:
    template:
      name: Prerolls
      schedule: range(06/01-08/31)
      videos: "/preroll/summer.mp4"
```

**Comment by meisnate12** [comment]
thats because thats not how it works you're trying to add a template variable called schedule and then you don't use it. 
```yaml
templates:
  Prerolls:
    build_collection: false
    server_preroll: <<videos>>
collections:
  Spring:
    schedule: range(03/01-05/31)
    template:
      name: Prerolls
      videos: "/preroll/spring.mp4"
  Summer:
    schedule: range(06/01-08/31)
    template:
      name: Prerolls
      videos: "/preroll/summer.mp4"
```

or

```yaml
templates:
  Prerolls:
    build_collection: false
    schedule: <<schedule>>
    server_preroll: <<videos>>
collections:
  Spring:
    template:
      name: Prerolls
      schedule: range(03/01-05/31)
      videos: "/preroll/spring.mp4"
  Summer:
    template:
      name: Prerolls
      schedule: range(06/01-08/31)
      videos: "/preroll/summer.mp4"
```

or for even smaller

```yaml
templates:
  Prerolls:
    build_collection: false
collections:
  Spring:
    template: { name: Prerolls }
    schedule: range(03/01-05/31)
    server_preroll: "/preroll/spring.mp4"
  Summer:
    template: { name: Prerolls }
    schedule: range(06/01-08/31)
    server_preroll: "/preroll/summer.mp4"
```

tbh not sure why you're bothering to create a template variable for videos when you could just do `server_preroll`
