### ISSUE TITLE
Feature Request: trakt_people + lists

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#581]
tmdb functionality for people is awesome. but would cool if this works for trakt aswell
(taking picture, summery and movies from that person)

now the main thing here is that trakt supports Actors-Lists. 
So instead of searching on tmdb and writing down every Single Actor, Actress, Writer and Director in PMM directly, 

it would be huge if PMM could work with the "trakt-person-lists" and search for every person on that list (with specified filters for what kind of Person (Actor/Writer) this list is.

maybe like

```
trakt_person_list:
  url: trakt.tv/lists/SomePeopleInThisList
  person_type: 
    - Actor
    - Writer
```

https://trakt.docs.apiary.io/#reference/people/movies/get-movie-credits
https://api.trakt.tv/people/id/movies

https://trakt.docs.apiary.io/#reference/search/id-lookup/get-id-lookup-results
/search/trakt/:id?type=person
