### ISSUE TITLE
Feature Request: Add support for configuring delay between each Plex item

### ISSUE THREAD

**Issue by axsuul** [Kometa-Team/Kometa#596]
I have a task that refreshes metadata for movies added in the last 30 days

```yaml
collections:
  'Newly Released Movies':
    # Never run during normally scheduled runs since it will be run via cron instead
    schedule: never

    # Ensure poster and other metadata is locked because refreshing metadata can change things
    item_lock_background: true
    item_lock_poster: true
    item_lock_title: true

    item_refresh: true

    plex_search:
      release: 30
```

The issue with this is it can often cause Plex to crash with the database being too busy due to how many are being refreshed at the same time. The solution around this problem would be adding a delay between refreshes/acting on each Plex item (e.g. `each_item_interval: 10s`). 

Thanks!
