### ISSUE TITLE
Movie Metadata Feature Request: Match Movie to tmdb_id

### ISSUE THREAD

**Issue by xstasy** [Kometa-Team/Kometa#601]
```
metadata:
  "A Nightmare on Elm Street (1984)":
    title: A Nightmare on Elm Street
    year: 1984
  "A Nightmare on Elm Street (2010)":
    title: A Nightmare on Elm Street
    year: 2010
```

Could we add numeric key searches to metadata?
For example:
```
metadata:
  1234:
    url_poster: https://...

```
Will save lots of matching headaches and titles with same name is resolved elegantly.
Then if in additions templates were introduced something like this would be possible:

```
templates:
  set:
    tmdb_id: <<key>>
    url_poster: https://theposterdb.com/api/assets/<<img>>

metadata:
  377: template { name: set, img: 27007 } # Nightmare on Elm Street (1984)
```
