### ISSUE TITLE
Feature Request: Ability auto update/sync labels from IMDb list without building a collection

### ISSUE THREAD

**Issue by qazero** [Kometa-Team/Kometa#609]
**Is your feature request related to a problem? Please describe.**
Currently Plex does not have a way to make private collections that are only visible to select users. Playlists can accomplish something similar but don't work well for TV Shows since it lists each individual episode instead of the TV Show. Labels seem to offer decent middle ground. While labels are still visible to all users, they will be hidden almost everywhere in the UI and only visible when trying to filter the items in the library view. However, the problem with using labels is that if an item is removed the the IMDB list, the label will still remain for that item in Plex. It would be nice if there were a way to keep item item labels in sync similar to collections and playlists.

**Describe the solution you'd like**
As per our discussion on Discord, please implement the ability to ensure labels remain in sync when an item is removed from an IMDB list without requiring a collection to be made.

**Additional context**
Sample config for the desired outcome mentioned above:

```
collections:
  Bryant's Willbum:
    imdb_list: https://www.imdb.com/list/ls530659964/
    sync_mode: sync
    build_collection: false
    smart_label: audience_rating.asc
```

**Comment by meisnate12** [comment]
so i added `non_item_remove_label` as an option
```yaml
collections:
  Bryant's Willbum:
    imdb_list: https://www.imdb.com/list/ls530659964/
    build_collection: false
    item_label: Bryant's Willbum
    non_item_remove_label: Bryant's Willbum
```

but after reading your problem i have two other solutions for you 
1. You can actually restrict collections per use via sharing Labels which can also be added to the collection.
2. You can also use PMM to make playlists and directly sync them to specific users no labels needed,
