### ISSUE TITLE
Bug: Collections created by `tmdb_collections` operations are considered unmanaged

### ISSUE THREAD

**Issue by foux** [Kometa-Team/Kometa#624]
**Describe the Bug**
When creating `tmdb_collections` using a library `operations`, those collections are considered unmanaged, where they should be managed.

As a result, if we set `delete_unmanaged_collections: true` for the same library, the collections will be created and then deleted at each run.

**Relevant Collection Config**
```
libraries:                                      # Library mappings must have a colon (:) placed after them
  Films:
    metadata_path:
      - file: config/movies/default.yml
      - file: config/movies/directors.yml
    operations:
      mass_trakt_rating_update: true
      delete_unmanaged_collections: false
      tmdb_collections:
        remove_suffix:
          - Collection
          - '- Saga'
        exclude_ids:
          - 11716
          - 750822
        template:
          minimum_items: 2
          tmdb_collection_details: <<collection_id>>
          collection_order: release
          collection_mode: hide_items
```

**Plex Meta Manager Info**
- `1.15.0`

**Link to logs (required)**
https://gist.github.com/foux/3d2e346e410b7cf4a6cd54f3a7ac18cf
