### ISSUE TITLE
Bug:  Track Metadata in music library does not get updated

### ISSUE THREAD

**Issue by CherryKitten** [Kometa-Team/Kometa#633]
**Describe the Bug**

Track Metadata does not actually get updated.
The Log claims that it was done, but it's not reflected on plex. Running PMM again has the exact same result, which means that PMM also gets the original values back when checking on the next run.

**Relevant Config**
```yaml
metadata:
  "Linkin Park":
    country: "United States of America"
    album_sorting: newest
    albums:
      "Hybrid Theory":
        originally_available: "2000-10-24"
        tracks:
          1:
            rating: 5
            original_artist: "Test"
          "One Step Closer":
            rating: 5
            original_artist: "Test"
      "Meteora":
        originally_available: "2003-03-25"
        album_sorting: newest
        tracks:
          9:
            rating: 5
            original_artist: "Test"
          "Numb":
            rating: 5
            original_artist: "Test"
```

**Plex Meta Manager Info**

Version: 1.15.0 

**Link to logs (required)**

https://gist.github.com/CherryKitten/2b518f3d268ad781e0087f7335ed8c1d

Those are logs for two subsequent runs with the same config, showing that the metadata hasn't been updated correctly and is being tried again.
