### ISSUE TITLE
Bug: Playlists with Assets folder not working

### ISSUE THREAD

**Issue by bullmoose20** [Kometa-Team/Kometa#634]
**Describe the Bug**
when trying to setup local assets folder for playlists, PMM won't find the directories to set the poster for that playlist.

I have tried:
creating folders in /config/assets/playlists/<name of playlist>/<image>.ext
creating folders in /config/assets/<name of playlist>/<image>.ext
adding asset directory to the play_files: portion of the yaml, but PMM parses and cleans that out when running

**Relevant Collection Config**

```
playlist_files:
  - file: config/metadata/Playlists.yml
libraries:                                      # Library mappings must have a colon (:) placed after them
  Movies:
    metadata_path:
      - file: config/metadata/movies/Movies.yml
      - file: config/metadata/movies/MovieCharts.yml
      - file: config/metadata/movies/Holidays.yml
      - file: config/metadata/movies/Studios.yml
      - file: config/metadata/movies/Genres-smart.yml
      - file: config/metadata/movies/People.yml
      - file: config/metadata/movies/Decades.yml
    settings:
      missing_path: config/missing
      asset_directory:
        - config/assets/movies/@movies
        - config/assets/movies/moviecharts
        - config/assets/movies/studios
        - config/assets/movies/holidays
        - config/assets/movies/genres
        - config/assets/movies/people
        - config/assets/movies/decades
        - config/assets/movies/years
        - config/assets/playlists
        - config/assets/
    operations:
      split_duplicates: true
      assets_for_all: true
      mass_trakt_rating_update: true
      mass_critic_rating_update: tmdb
      mass_audience_rating_update: tmdb
      mass_genre_update: tmdb
      tmdb_collections:
        template:
          tmdb_collection_details: <<collection_id>>
          sort_title: <<collection_name>>
  TV Shows:
    metadata_path:
      - file: config/metadata/shows/TVShows.yml
      - file: config/metadata/shows/Genres-smart.yml
      - file: config/metadata/shows/ShowCharts.yml
      - file: config/metadata/shows/Networks-smart.yml
      - file: config/metadata/shows/Decades.yml
    settings:
      missing_path: config/missing
      asset_directory:
        - config/assets/shows/@tvshows
        - config/assets/shows/showcharts
        - config/assets/shows/networks
        - config/assets/shows/genres
        - config/assets/shows/studios
        - config/assets/shows/decades
        - config/assets/playlists
        - config/assets/
    operations:
      assets_for_all: true
      mass_trakt_rating_update: true
      mass_critic_rating_update: tmdb
      mass_audience_rating_update: tmdb
      mass_genre_update: tmdb
settings:                                       # Can be individually specified per library as well
  cache: true
  cache_expiration: 60
  asset_folders: true
  asset_depth: 2
  create_asset_folders: true
  dimensional_asset_rename: true
  sync_mode: sync
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: true
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: true
  show_options: true
  show_missing: true
  show_missing_assets: true
  show_missing_season_assets: true
  save_missing: true
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  minimum_items: 1
  default_collection_order:
  download_url_assets: false
  verify_ssl: true
  item_refresh_delay: 0
  asset_directory: config/assets
  missing_path: config/missing
  playlist_sync_to_users: all
```

**Plex Meta Manager Info**
v 1.15.0

**Meta.log Relevant  Info**
```
[2022-01-21 20:13:36,409] [util.py:216]               [INFO]     |====================== Updating Details of Marvel Cinematic Universe Playlist ======================|
[2022-01-21 20:13:36,412] [builder.py:2156]           [INFO]     |                                                                                                    |
[2022-01-21 20:13:36,414] [builder.py:2163]           [INFO]     | Detail: summary updated Playlist Summary                                                           |
[2022-01-21 20:13:36,417] [builder.py:2301]           [INFO]     | No poster playlist detail or asset folder found                                                    |
[2022-01-21 20:13:36,418] [builder.py:2334]           [INFO]     | No background playlist detail or asset folder found                                                |
[2022-01-21 20:13:36,714] [builder.py:2340]           [INFO]     |                                                                                                    |

```
![image](https://user-images.githubusercontent.com/12549033/150643982-4c449946-d99f-4af9-92c7-98623a9ec953.png)
![image](https://user-images.githubusercontent.com/12549033/150643995-93bb97ab-c236-4a16-8265-742893b80eb6.png)

link to Discord conversation: https://discord.com/channels/822460010649878528/826911404866273300/934255470091309067
