### ISSUE TITLE
Bug: smart_filter titles not working as expected

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#638]
**Describe the Bug**
In my yml:
```
collections:
  "TestCollection":
    smart_filter:
      any:
        title:
          - "Title Test -"
          - "Title Test,"
```

results in this:
![image](https://user-images.githubusercontent.com/38122413/150666102-e2936ece-25cd-45e2-8876-75f1e3acea05.png)

**Plex Meta Manager Info**
- Version 1.15.0-develop220122
