### ISSUE TITLE
Pilots Collection

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#650]
### Discussed in https://github.com/meisnate12/Plex-Meta-Manager/discussions/649

<div type='discussions-op-text'>

<sup>Originally posted by **eddik1970** January 24, 2022</sup>
I am looking to make a Collection of first episodes of TV pilots. 

If I could create a collection where filename contains S01E01 that would be perfect? 

Is this possible?

</div>

**Comment by bakes82** [comment]
Does this work with filters?


```
Pilots:
    collection_level: episode
    plex_pilots: true
    filters:
      release: 30
```

Collection Error: filters attribute not allowed with Collection Level: Episode
