### ISSUE TITLE
Crash when attempting to connect to sonarr

### ISSUE THREAD

**Issue by Drapersniper** [Kometa-Team/Kometa#651]
**Describe the Bug**
- Crash when running the script when attempting to connect to sonarr.

**Relevant Collection Config**
```
  Anime:
    metadata_path:
      - file: //config/anime.yml
      - git: meisnate12/Metadata
      - git: cpt-kuesel/metadata/anime/metadata
    sonarr:
      url: ...
      token: ...
      version: v3
      root_folder_path: ...
      monitor: all
      quality_profile: 1080p
      language_profile: English
      series_type: anime
      season_folder: true
      tag: Auto-Collection
      search: true
      cutoff_search: false
      add_missing: true
```
**Plex Meta Manager Info**
- Version: 1.15.0-develop220122 

**Link to logs (required)**
```
[2022-01-24 23:31:51,261] [util.py:162]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "/modules/sonarr.py", line 39, in __init__
                                                                 |     self.api.respect_list_exclusions_when_adding()
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/apis/sonarr.py", line 107, in respect_list_exclusions_when_adding
                                                                 |     self.exclusions = [SonarrExclusion(self, ex).tvdbId for ex in self._raw.get_importlistexclusion()]
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/sonarr.py", line 84, in get_importlistexclusion
                                                                 |     return self._get("importlistexclusion")
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/base.py", line 32, in _get
                                                                 |     return self._request("get", path, **kwargs)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/base.py", line 78, in _request
                                                                 |     raise NotFound(f"({response.status_code} [{response.reason}]) Item Not Found {response_json}")
                                                                 | arrapi.exceptions.NotFound: (404 [Not Found]) Item Not Found {'message': 'NotFound'}
                                                                 | 
                                                                 | During handling of the above exception, another exception occurred:
                                                                 | 
                                                                 | Traceback (most recent call last):
                                                                 |   File "/modules/config.py", line 802, in __init__
                                                                 |     library.Sonarr = Sonarr(self, library, {
                                                                 |   File "/modules/sonarr.py", line 42, in __init__
                                                                 |     raise Failed(e)
                                                                 | modules.util.Failed: (404 [Not Found]) Item Not Found {'message': 'NotFound'}
                                                                 ```

Sonarr version: 3.0.6.1451

**Comment by bakerboy448** [comment]
Sonarr v2 is not supported

You need to be on Sonarr v3

**Comment by Drapersniper** [comment]
3.0.6.1451  Is V2?

**Comment by meisnate12** [comment]
try adding `/sonarr` to the end of your url

**Comment by Drapersniper** [comment]
Adding a `/sonarr` to the url didn't help in fact it made it crash earlier.

At least on the error in comment#1 I was able to authenticate with the sonarr instance (Also this instance doesn't have a `/sonarr` path)

```
-01-25 09:06:37,663] [util.py:158]               [DEBUG]    | Traceback (most recent call last):
                                                                 |   File "//plex_meta_manager.py", line 169, in start
                                                                 |     config = ConfigFile(default_dir, attrs, read_only_config)
                                                                 |   File "/modules/config.py", line 719, in __init__
                                                                 |     library.Sonarr = Sonarr(self, library, {
                                                                 |   File "/modules/sonarr.py", line 38, in __init__
                                                                 |     self.api = SonarrAPI(self.url, self.token, session=self.config.session)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/apis/sonarr.py", line 19, in __init__
                                                                 |     super().__init__(SonarrRawAPI(url, apikey, session=session))
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/sonarr.py", line 7, in __init__
                                                                 |     super().__init__(url, apikey, session=session)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/arrapi/raws/base.py", line 25, in __init__
                                                                 |     if "version" not in status or status["version"] is None:
                                                                 | TypeError: argument of type 'NoneType' is not iterable
                                                                 | 
[2022-01-25 09:06:37,664] [util.py:154]               [CRITICAL] | argument of type 'NoneType' is not iterable
```

This is the config for this error:
```yaml
libraries:
  Anime:
    metadata_path:
      - file: //config/anime.yml
      - git: meisnate12/Metadata
      - git: cpt-kuesel/metadata/anime/metadata
    sonarr:
      url: http://animarr-1080p:8989/sonarr
      token: [redacted]
      version: v3
      root_folder_path: /data/media/Anime/1080p
      monitor: all
      quality_profile: 1080p
      language_profile: English
      series_type: anime
      season_folder: true
      tag: PMM
      search: true
      cutoff_search: false
      add_missing: true
  ```
  
  This is the full config for the crash in comment#1
  ```yaml
  libraries:
  Anime:
    metadata_path:
      - file: //config/anime.yml
      - git: meisnate12/Metadata
      - git: cpt-kuesel/metadata/anime/metadata
    sonarr:
      url: http://animarr-1080p:8989
      token: [redacted]
      version: v3
      root_folder_path: /data/media/Anime/1080p
      monitor: all
      quality_profile: 1080p
      language_profile: English
      series_type: anime
      season_folder: true
      tag: Auto-Collection
      search: true
      cutoff_search: false
      add_missing: true
```
