### ISSUE TITLE
Dummy collection/blank collection

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#660]
### Discussed in https://github.com/meisnate12/Plex-Meta-Manager/discussions/645

<div type='discussions-op-text'>

<sup>Originally posted by **ButtaJones** January 23, 2022</sup>
I've been trying to add a dummy collect. A blank collection with nothing in it. Is this possible? This is what I tried. Maybe I'm trying to hard.

```
  A:
    collection_mode: hide
    sort_title: +08_a
    plex_search:
      any:
        title: khjslahjg
      validate: false
    url_poster: https://raw.githubusercontent.com/zluckytraveler/Plex-Meta-Manager-Configs/master/zluckytraveler/Posters/Networks/Standard/ABC.jpg
```
Script spits out:
```
| A                    |  0  |  0  |  0  | PMM Failure                                               |
| Plex Error: No Items found in Plex
```

Also. Would it be possible to leave the collection name blank insead of "A"?

Any ideas?</div>
