### ISSUE TITLE
Feature Request - Template with multiple poster locations

### ISSUE THREAD

**Issue by Glasti1** [Kometa-Team/Kometa#67]
Is it possible to have a template with a `url_poster` and `file_poster`, or `url_poster` and use the assets folder, so you can choose what you want to use for different collections? 

If so, can you give a short example how to do that?

**Comment by meisnate12** [comment]
Currently No

**Comment by meisnate12** [comment]
this has been added to develop. Now in addition to the `default` attribute I've added the `optional` attribute. You can give the `optional` attribute a list of variables. When the template is called by a collection if an optional variable is not used the whole attribute will be ignored. This allows you to do something like this.

```yaml
templates:
  Actor:
    optional:
      - URL
      - FILE
    actor: tmdb
    tmdb_person: <<person>>
    url_poster: <<URL>>
    file_poster: <<FILE>>
    sort_title: +_<<collection_name>>
    sync_mode: sync
    collection_order: release
collections:
  Ben Affleck:
    template: {name: Actor, person: 880}
  Ben Stiller:
    template: {name: Actor, person: 7399}
  Bill Murray:
    template: {name: Actor, person: 1532, FILE: /images/Bill Murray.png}
  Brad Pitt:
    template: {name: Actor, person: 287, URL: https://theposterdb.com/api/assets/125584/view}
  

```
