### ISSUE TITLE
Feature Request: Cache data retrieved from URLs for reuse

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#671]
**Is your feature request related to a problem? Please describe.**
If the same external lists are used in multiple collections, or across multiple libraries, PMM retrieves and processes the list every time, even though in many cases the source list will not have changed in the interim.  As an example,  I create the same "1001 Movies you should see before you die" collection in each of my 13 movie libraries.  Most likely, that list is not going to change during a single PMM run [maybe not ever], yet PMM makes the same 11 requests to IMDB and does the same processing of the list each time.  This time can add up.

**Describe the solution you'd like**
I'd like PMM to cache its processed version of the list for a configurable time.  Perhaps something like:
```
  1001 Movies You Must See Before You Die:
    template: {name: Collection, source: IMDB}
    summary: "From some random guy on IMDB"
    imdb_list:
      - https://www.imdb.com/list/ls052535080/
    source_cache: 720
```
If PMM processes another collection that calls for that URL within 720 minutes PMM would use the cached version.  After the cache is that old it gets refreshed.

**Describe alternatives you've considered**
I thought at first that scheduling could deal with this, but even if I stagger these things with a schedule, it's still pulling the list from the source more than needed, which adds redundant work to every run.
