### ISSUE TITLE
Bug: 404 Error when updating collection Summary

### ISSUE THREAD

**Issue by Drazzilb08** [Kometa-Team/Kometa#686]
When updating a collection's summary this error is presented. This seems to happen when you create a collection.
```
[2022-02-03 12:55:15,223] [util.py:228]               [INFO]     |========================== Updating Details of Trending Movies Collection ==========================|
[2022-02-03 12:55:15,224] [builder.py:2180]           [INFO]     |                                                                                                    |
[2022-02-03 12:55:15,224] [builder.py:2187]           [INFO]     | Detail: summary updated Collection Summary                                                         |
[2022-02-03 12:55:15,227] [builder.py:2266]           [DEBUG]    | {'summary.value': 'Movies Trending across the internet.', 'summary.locked': 1}                     |
[2022-02-03 12:55:26,035] [util.py:174]               [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "//plex_meta_manager.py", line 840, in run_collection
                                                                 |     builder.update_details()
                                                                 |   File "/modules/builder.py", line 2267, in update_details
                                                                 |     self.library.edit_query(self.obj, edits)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
                                                                 |     return Retrying(*dargs, **dkw).call(f, *args, **kw)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 206, in call
                                                                 |     return attempt.get(self._wrap_exception)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 247, in get
                                                                 |     six.reraise(self.value[0], self.value[1], self.value[2])
                                                                 |   File "/usr/local/lib/python3.9/site-packages/six.py", line 719, in reraise
                                                                 |     raise value
                                                                 |   File "/usr/local/lib/python3.9/site-packages/retrying.py", line 200, in call
                                                                 |     attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
                                                                 |   File "/modules/plex.py", line 521, in edit_query
                                                                 |     item.edit(**edits)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/collection.py", line 367, in edit
                                                                 |     super(Collection, self).edit(**args)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 531, in edit
                                                                 |     self._edit(**kwargs)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 517, in _edit
                                                                 |     self._server.query(part, method=self._server._session.put)
                                                                 |   File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 680, in query
                                                                 |     raise NotFound(message)
                                                                 | plexapi.exceptions.NotFound: (404) not_found; http://192.168.1.200:32400/library/sections/10/all?summary.value=Movies+Trending+across+the+internet.&summary.locked=1&id=611940&type=18 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
                                                                 | 
[2022-02-03 12:55:26,047] [plex_meta_manager.py:889]  [ERROR]    | Unknown Error: (404) not_found; http://192.168.1.200:32400/library/sections/10/all?summary.value=Movies+Trending+across+the+internet.&summary.locked=1&id=611940&type=18 <html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></html>
[2022-02-03 12:55:26,047] [plex_meta_manager.py:892]  [INFO]     | 
```
Example:
```yaml
  Trending Movies:
    trakt_trending: 50
    tmdb_trending_daily: 50
    tmdb_trending_weekly: 50
    sort_title: +++++++++++++++++++_1Trending
    smart_label: year.desc
    summary: Movies Trending across the internet. (Updated daily)
    url_background: https://i.imgur.com/SOVfrIq.png
    url_poster: https://i.imgur.com/4vpMZoA.png
 ```
Then simply change the Summary

  ```yaml
  Trending Movies:
    trakt_trending: 50
    tmdb_trending_daily: 50
    tmdb_trending_weekly: 50
    sort_title: +++++++++++++++++++_1Trending
    smart_label: year.desc
    summary: Movies Trending across the internet. 
    url_background: https://i.imgur.com/SOVfrIq.png
    url_poster: https://i.imgur.com/4vpMZoA.png
 ```
