### ISSUE TITLE
FR: Mass updates to metadata (specifically content ratings)

### ISSUE THREAD

**Issue by meisnate12** [Kometa-Team/Kometa#699]
### Discussed in https://github.com/meisnate12/Plex-Meta-Manager/discussions/696

<div type='discussions-op-text'>

<sup>Originally posted by **burkasaurusrex** February  4, 2022</sup>
Is there a way to update certain metadata from the results of a Plex search? e.g. is there a way to update the content ratings of everything currently labeled as "TV-14" to "PG-13"?

I don't think it's possible because you'd need a `item_content_rating` or something, but just thought I'd check here before opening a feature request.

Was thinking something like this:

```yaml
###
### Content Rating
###
templates:
    Content Rating Filter:
        plex_all: true
        filters:
            content_rating: <<collection_name>>
        build_collection: false
collections:
    ##
    ## TV Ratings
    ##
    TV-G:
        template: {name: Content Rating Filter}
        item_content_rating: "G"
    TV-PG:
        template: {name: Content Rating Filter}
        item_content_rating: "PG"
    TV-14:
        template: {name: Content Rating Filter}
        item_content_rating: "PG-13"
    TV-MA:
        template: {name: Content Rating Filter}
        item_content_rating: "R"
```
</div>

Reply from @meisnate12

> There's not a way currently but we've got two options I think I can either change the genre_mapper to metadata_mapper and allow it to work with many different attributes or change item_label to item_metadata and then give it attributes to specify the attribute and value
