### ISSUE TITLE
"People" search doesn't forward to Radarr

### ISSUE THREAD

**Issue by jfeeser** [Kometa-Team/Kometa#70]
Hi there,

I've got PMM working really well, and have lots of collections set up.  One thing i've noticed is that while "chart" and "list" collections based on IMDB and Trakt seem to add things that are missing from the list to Radarr, (e.g. IMDB top 250, Trakt list of the Criterion Collection movies), when i do a search on TMDB for, say, a Director, it creates the collection properly for *existing* movies, but it doesn't seem to add movies missing from the list to radarr.  Can this behavior be changed?

**Comment by meisnate12** [comment]
can you paste your collection configuration for that collection

**Comment by jfeeser** [comment]
```
templates:

  Director:
    director: tmdb
    tmdb_person: <<person>>
    sort_title: 00 - 03 - Collections - <<collection_name>>
    sync_mode: sync
    collection_order: release

 Collection:
   Sam Raimi Collection:
     summary: Samuel Marshall "Sam" Raimi is an American film director, producer, actor and writer. He is best known for directing cult horror films like the Evil Dead series, Darkman and Drag Me to Hell, as well as the blockbuster Spider-Man films and the producer of the successful TV series Hercules The Legendary Journeys, Xena Warrior Princess, Legend of the Seeker and Spartacus Blood and Sand.
     template: {name: Director, person: 7623}
     schedule: monthly(1)
```
