### ISSUE TITLE
Feature Request: A Today In History feature for TV episodes

### ISSUE THREAD

**Issue by sdavisNL** [Kometa-Team/Kometa#749]
**Is your feature request related to a problem? Please describe.**
Not really a problem, just a feature I'd like to see. The ability to create collection/playlist with all episodes that aired on today's date in history.

**Describe the solution you'd like**
Sohjiro mentioned in the Discord that there is a history filter already built-in for movies, so I guess it'd be something similar for show episdoes.

**Comment by Frazzer951** [comment]
Looking at the wiki for the [history filter](https://metamanager.wiki/en/latest/metadata/filters.html#id8) it looks like it already has episode support. So you could probably make a collection that just has all plex expisodes, set the collection level to episode, and then use the histroy filter. 
Something like:
```yml
collections:
  Today In History:
    plex_all: true
    collection_level: episode
    filters:
      history:
```

I haven't used the history filter or tested it, so you might have to mess around with it to see if you get the desired result
