### ISSUE TITLE
[Bug]: plex_pilots attribute of Plex Builders not working as expected on Playlists

### ISSUE THREAD

**Issue by Frazzer951** [Kometa-Team/Kometa#769]
### Version Number

1.16.1

### What branch are you on?

master

### Describe the Bug

In the [plex builder wiki](https://metamanager.wiki/en/latest/metadata/builders/plex.html), The attribute `plex_pilots` says it works with playlist, but when put into a playlist it returns the error `Playlist Error: plex_pilots attribute not allowed when using playlists` the wiki also says it only works with `collection_level: episode` and I tried adding that but go the same result

### Relevant Collection/Playlist Definition

```yml
playlists:
  Watchlist:
    collection_level: episode
    plex_pilots: true
    sync_to_users:
    sync_mode: sync
    libraries: Movies, TV Shows
    trakt_list: https://trakt.tv/users/frazzer951/watchlist?sort=rank,asc
    summary: Watchlist of TV shows and Movies
```
or
```yml
playlists:
  Watchlist:
    plex_pilots: true
    sync_to_users:
    sync_mode: sync
    libraries: Movies, TV Shows
    trakt_list: https://trakt.tv/users/frazzer951/watchlist?sort=rank,asc
    summary: Watchlist of TV shows and Movies
```

### Logs

https://gist.github.com/Frazzer951/e33432efdce5415842eade862feca18a
