### ISSUE TITLE
[Bug]: Dynamic collection sort_title does not respect 'key_name_override'

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#774]
### Version Number

1.16.1-develop1

### What branch are you on?

develop

### Describe the Bug

Given the definition below, there is a "Palestine" collection created, but the sort title of that collection is set to "World-State of Palestine", which is what it was prior to my setting the "key_name_override".  My expectation would be that the sort title would respect the change made in "key_name_override".

### Relevant Collection/Playlist Definition

```yml
templates:
  country collection:
    sort_title: World-<<country>>
    smart_filter: 
      any:
        country: <<country>>
dynamic_collections:
  Countries:
    type: country
    title_format: <<title>>
    template: country collection
    key_name_override:
      Taiwan, Province of China: Taiwan
      Serbia: Serbia and Montenegro
      Plurinational State of Bolivia: Bolivia
      Bolivarian Republic of Venezuela: Venezuela
      State of Palestine: Palestine
    addons:
      Serbia:
        - Montenegro
```

### Logs

https://gist.github.com/chazlarson/b35ec78f2bed47bc5e307422c9f37247
