### ISSUE TITLE
[Bug]: Dynamic collection 'sort_title" behaves unexpectedly with "add-ons"

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#775]
### Version Number

1.16.1-develop1

### What branch are you on?

develop

### Describe the Bug

Given the definition below, a "Serbia and Montenegro" collection is created with the sort_title "World-['Serbia', 'Montenegro']".  I expected the sort_title to be "World-Serbia and Montenegro"

### Relevant Collection/Playlist Definition

```yml
templates:
  country collection:
    sort_title: World-<<country>>
    smart_filter: 
      any:
        country: <<country>>
dynamic_collections:
  Countries:
    type: country
    title_format: <<title>>
    template: country collection
    key_name_override:
      Taiwan, Province of China: Taiwan
      Serbia: Serbia and Montenegro
      Plurinational State of Bolivia: Bolivia
      Bolivarian Republic of Venezuela: Venezuela
      State of Palestine: Palestine
    addons:
      Serbia:
        - Montenegro
```

### Logs

https://gist.github.com/chazlarson/936b1d357444c6e68da6f4c1eb5d6359
