### ISSUE TITLE
[Bug]: Dynamic collection passes key_override to search, which fails to create collection

### ISSUE THREAD

**Issue by chazlarson** [Kometa-Team/Kometa#776]
### Version Number

1.16.1-develop1

### What branch are you on?

develop

### Describe the Bug

Given the collection definition below, PMM attempts to create a "Taiwan" collection, which I would expect, but it sets up a search for "COUNTRY = Taiwan", which of course fails so the collection is not created.  Oddly, the rest of them work, so maybe it's the comma in the key_name.

### Relevant Collection/Playlist Definition

```yml
templates:
  country collection:
    sort_title: World-<<country>>
    smart_filter: 
      any:
        country: <<country>>
dynamic_collections:
  Countries:
    type: country
    title_format: <<title>>
    template: country collection
    key_name_override:
      Taiwan, Province of China: Taiwan
      Serbia: Serbia and Montenegro
      Plurinational State of Bolivia: Bolivia
      Bolivarian Republic of Venezuela: Venezuela
      State of Palestine: Palestine
    addons:
      Serbia:
        - Montenegro
```

### Logs

https://gist.github.com/chazlarson/ff99691adf35b746d38e30d8a3875db5
