### ISSUE TITLE
[Bug]: Weird metadata error with alt_title on a previously working config

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#793]
### Version Number

1.16.2-develop5

### What branch are you on?

develop

### Describe the Bug

IDK how long this has been an issue, because I haven't actually looked through my logs in a long time. But I noticed this error today, and I know nothing's changed in the configs since around November last year.

I also tested adding quotes around the alt_title, and that didn't make a difference.

### Relevant Collection/Playlist Definition

```yml
collections:
  "Gorillaz":
    collection_mode: hide_items
    smart_filter:
      all:
        title.begins: Gorillaz
metadata:
  "Gorillaz — Clint Eastwood":
    alt_title: 05 - Clint Eastwood - Gorillaz — Clint Eastwood-video
    originally_available: 2016-06-28
    genre:
      - Pop/Rock
      - Rap
```

### Logs

https://gist.github.com/ngInit/ab5e6116f6d4b55c2629ea3d868bf297
