### ISSUE TITLE
[Bug]: Unknown Error: 'Collection' object has no attribute 'batchEdits'

### ISSUE THREAD

**Issue by bakes82** [Kometa-Team/Kometa#810]
### Version Number

1.16.2-develop46  

### What branch are you on?

develop

### Describe the Bug

[2022-04-01 12:50:51,128] [builder.py:1909]           [INFO]     |============================= Removed from Amazon Originals Collection =============================|
[2022-04-01 12:50:51,128] [builder.py:1910]           [INFO]     |                                                                                                    |
[2022-04-01 12:50:54,166] [builder.py:1916]           [INFO]     | 1/1 | Amazon Originals Collection | - | Never Grow Old (2019)                                      |
[2022-04-01 12:50:54,195] [builder.py:1933]           [INFO]     |                                                                                                    |
[2022-04-01 12:50:54,195] [builder.py:1934]           [INFO]     | 1 Movies Removed                                                                                   |
[2022-04-01 12:50:54,204] [builder.py:2363]           [INFO]     |                                                                                                    |
[2022-04-01 12:50:54,204] [builder.py:2364]           [INFO]     |========================= Updating Details of Amazon Originals Collection ==========================|
[2022-04-01 12:50:54,204] [builder.py:2365]           [INFO]     |                                                                                                    |
[2022-04-01 12:50:54,204] [builder.py:2371]           [INFO]     | Detail: summary will update Collection Summary                                                     |
[2022-04-01 12:50:54,208] [plex_meta_manager.py:1018] [DEBUG]    | Traceback (most recent call last):                                                                 |
                                                                 |   File "/plex_metadata_manager/plex_meta_manager.py", line 971, in run_collection
                                                                 |     builder.update_details()
                                                                 |   File "/plex_metadata_manager/modules/builder.py", line 2406, in update_details
                                                                 |     self.obj.batchEdits()
                                                                 |   File "/usr/local/lib/python3.8/dist-packages/plexapi/base.py", line 457, in __getattribute__
                                                                 |     value = super(PlexPartialObject, self).__getattribute__(attr)
                                                                 | AttributeError: 'Collection' object has no attribute 'batchEdits'
                                                                 | 
[2022-04-01 12:50:54,208] [plex_meta_manager.py:1019] [ERROR]    | Unknown Error: 'Collection' object has no attribute 'batchEdits'

### Relevant Collection/Playlist Definition

```yml
Amazon Originals:
   sort_title: +1_AMZN
   smart_label: release.desc
   sync_mode: sync
   trakt_list: https://trakt.tv/users/garycrawfordgc/lists/amazon-prime-movies
   summary: All Amazon Prime Movies
   url_poster: https://pmm.sudoer.dev/logos/png/AMZN_black.png
   url_background: https://i.imgur.com/2jfs7oS.png
   
 Apple Originals:
   sort_title: +1_APPLE
   smart_label: originally_available.desc
   sync_mode: sync
   imdb_list:
     url: https://www.imdb.com/search/title/?title_type=feature,tv_movie,tv_series,tv_special,tv_miniseries,documentary,video,tv_short&release_date=2021-01-01,2025-12-31&genres=!animation&countries=us&languages=en&sort=release_date,desc&count=250&companies=co0546168
   summary: All Apple TV Originals From 2021+
   url_poster: https://pmm.sudoer.dev/logos/png/ATVP.png
   url_background: https://wallpaper-house.com/data/out/8/wallpaper2you_228774.png
```

### Logs

https://gist.github.com/bakes82/ed6bca939eeb580796bb3d9860a305d1
