### ISSUE TITLE
[Bug]: collection_order: custom cannot be used with trakt_recommendations

### ISSUE THREAD

**Issue by fouadchamoun** [Kometa-Team/Kometa#818]
### Version Number

1.16.3

### What branch are you on?

master

### Describe the Bug

when using custom collection order with trakt_recommendations builder i get this error : 
`Collection Error: collection_order: custom cannot be used with trakt_recommendations`

### Relevant Collection/Playlist Definition

```yml
For Me:
    summary: Movies recommended for me
    sort_title: +0_1<<collection_name>>
    sync_mode: sync
    collection_mode: show_items
    collection_order: custom
    trakt_recommendations: 20
    visible_library: false
    visible_home: true
    visible_shared: false
```

### Logs

https://gist.github.com/fouadchamoun/9d2232c327bd78f0cd789f67f178fe10
