### ISSUE TITLE
[Bug]: PMM not adding movies/tv shows to Radarr/Sonarr

### ISSUE THREAD

**Issue by chris6611** [Kometa-Team/Kometa#820]
### Version Number

1.16.3

### What branch are you on?

master

### Describe the Bug

PMM is not adding movies/tv shows to the arr apps. It does successfully connect to them when initially running, but nothing gets added even though it says "*arr Adds:" but then there are python script errors. config.yml is as follows:

```
radarr:                                         # Can be individually specified per library as well
  url: http://127.0.0.1:7878
  token: <redacted>
  add_missing: false
  add_existing: false
  root_folder_path: /home/user1/Media/movies
  monitor: true
  availability: announced
  quality_profile: Movies
  tag:
  search: false
  radarr_path:
  plex_path:
sonarr:                                         # Can be individually specified per library as well
  url: http://127.0.0.1:8989
  token: <redacted>
  add_missing: false
  add_existing: false
  root_folder_path: /home/user1/Media/tvshows
  monitor: all
  quality_profile: TV Shows No Remux
  language_profile: English
  series_type: standard
  season_folder: true
  tag:
  search: false
  cutoff_search: false
  sonarr_path:
  plex_path:
```
EDIT: I am currently doing per-collection adds to test out Sonarr and Radarr functionality which is why it is not in the config.yml.

In my collection I am using:
```
Disney+ Movies:
    radarr_add_missing: true
    template: {name: streaming, ...}
  ...
```

Thanks in advance for any help!

### Logs

https://gist.github.com/Christian-Martinez1/fe9ee6a8a535f14b4248753e1de1ccb1
