### ISSUE TITLE
[Bug]: PMM Add-Overlay feature errors out on specific movies

### ISSUE THREAD

**Issue by chris6611** [Kometa-Team/Kometa#824]
### Version Number

1.16.3

### What branch are you on?

master

### Describe the Bug

When adding an overlay to my 4K library, some random titles do not get the overlay added and an error is thrown and that item is skipped over. An example is Aladdin (2019), as can be seen by a sample of the library's XML file below it matches the metadata/{entry number} in gist of the error thrown from PMM:

...
<Video ratingKey="158" key="/library/metadata/158" guid="plex://movie/5d776c7ffb0d55001f5892da" studio="Walt Disney Pictures" type="movie" title="Aladdin" librarySectionTitle="Movies" librarySectionID="1" librarySectionKey="/library/sections/1" contentRating="PG" summary="A kind-hearted street urchin Aladdin vies for the love of the beautiful princess Jasmine, the princess of Agrabah. When he finds a magic lamp, he uses the genie's magic power to make himself a prince in order to marry her. He's also on a mission to stop the powerful Jafar who plots to steal the magic lamp that could make his deepest wishes come true." rating="5.7" audienceRating="9.4" year="2019" tagline="Choose Wisely." thumb="/library/metadata/158/thumb/1649978426" art="/library/metadata/158/art/1649978426" duration="7678912"
...

This has happened with about 10% of my total library. None of my library has custom artwork yet and it is all Plex default, however I was under the impression that overlays would be able to be added over default artwork (and it seems so as 90% of my library is okay). 

Just want to see if there is something I am missing as I am not sure why some of my library throws basically the exact same error that is in the gist.

Thanks in advance for any help!

-Chris

### Relevant Collection/Playlist Definition

```yml
4K-HDR:
    plex_search:
      all:
        resolution: 4K
        hdr: true
    item_overlay:
      name: 4K-HDR
      url: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Configs/master/yozora/overlays/Notch/4KHDR/overlay.png
    build_collection: false
```

### Logs

https://gist.github.com/Christian-Martinez1/53fa7dab5f48b183f1372c895a6f07c5
