### ISSUE TITLE
[Feature]: force alternative orders

### ISSUE THREAD

**Issue by snickers2k** [Kometa-Team/Kometa#829]
### Is your feature request related to a problem? Please elaborate.

sometimes tmdb/tvdb has the wrong order - but the admins are bullish about it - and for some weird reason won't change it.

good example is "[Archer Season 3](https://www.themoviedb.org/tv/10283-archer/season/03)"
the wrong order was reported multiple times over the last years, but still, no change.
the admins think they got it right and Netflix, [Imdb](https://www.imdb.com/title/tt1486217/episodes?season=3), [Wikipedia](https://en.wikipedia.org/wiki/Archer_(season_3)), Amazon-Prime, Google-Play and so on got it wrong. Of course the admins got it right. Obviously, not?

### Describe the solution you'd like

at least they allow for [alternative-order](https://www.themoviedb.org/tv/10283-archer/episode_group/5d3c708321621b0011eed975/group/5d3c70a4a1d332000f0c5073)

so would be great to have the ability to force alternative order for a specific show either with the tmdb-alternative-order-feature or by changing the order to imdb.

### Additional Information

maybe like
```
Metadata:
  Archer:
    seasons:
      3: 
         episode_ordering: tmdb_alternative
```

or

```
Metadata:
  Archer:
    seasons:
      3: 
         episode_ordering: imdb
```
