### ISSUE TITLE
[Feature]: Smart Playlists

### ISSUE THREAD

**Issue by zpz5HAU-tgc3fgw2xwr** [Kometa-Team/Kometa#830]
### Version Number

1.16.5

### What branch are you on?

develop

### Describe the Bug

From what I can tell on the wiki, the playlists builders are the same as collections. So following the example of my working collections that use smart_filter, I created a new playlist and got a "No builders were found" error.

### Relevant Collection/Playlist Definition

```yml
playlists:
  "Unplayed Subscriptions":
    libraries: YouTube
    smart_filter:
      sort_by: title.desc
      any:
        all:
          title.not:
            - "- Test"
            - "- Test2"
          title.ends: "— Channel3"
        title.ends:
          - "— Channel1"
          - "— Channel2"
```

### Logs

https://gist.github.com/ngInit/925c533b6d02bfb094a0ad6dbea483bb
