### ISSUE TITLE
TV Episodes by custom order

### ISSUE THREAD

**Issue by sych0** [Kometa-Team/Kometa#833]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

When creating a tv episode list, the custom order flag does not work. For example, Simpsons episodes rated 7.5 or higher in descending order of highest rated to lowest results in either an alphabetical list, or a random order list. Alpha and Release flags work properly, but custom does not. There is no error in the log, it just doesnt work as expected. I think something breaks in the moving process as the logs look like it worked, but then you head to plex and the list is not the correct order. 

### Relevant Collection/Playlist Definition

```yml
Simpsons Best of:
    collection_order: custom
    collection_level: episode
    sync_mode: sync
    imdb_list:
      url: https://www.imdb.com/search/title/?series=tt0096697&sort=user_rating,desc
      limit: 250
    sort_title: Simpsons Best of
```

### Logs

https://gist.github.com/sych0/6f15a58a2bd1db036a49a1df8e64585d

**Comment by sych0** [comment]
I also tried using the example from the wiki for the top 100 Simpsons episodes: 

```
Top 100 Simpsons Episodes:
     collection_order: custom
     collection_level: episode
     plex_search:
       type: episodes
       sort_by: audience_rating.desc
       limit: 100
       all:
         title.ends: "Simpsons"
     summary: A collection of the highest rated simpsons epsodes.
```

also fails and results in an alphabetical list in plex.
