### ISSUE TITLE
[Bug]: Unknown Error: 'TMDbShow' object has no attribute 'poster_path'

### ISSUE THREAD

**Issue by calboi91** [Kometa-Team/Kometa#841]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

When running, any collection using 'tmdb_show_details' method seems to generate the error. Logs are from one such collection. 

### Relevant Collection/Playlist Definition

```yml
templates:
    Show:
        tmdb_show_details: <<show>>
        sync_mode: sync
        collection_order: release

collections:
    Amagi Brilliant Park:
        template:
            name: Show
            show: 65332
        url_background: https://www.themoviedb.org/t/p/original/5pl88CUfQnOgPEY7jP5wORX4Kc0.jpg
```

### Logs

https://gist.github.com/calboi91/bf387769757b6adcba5a97d83247ce9c
