### ISSUE TITLE
[Bug]: anilist_search adult:false fails due to api

### ISSUE THREAD

**Issue by AevumDecessus** [Kometa-Team/Kometa#844]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

setting an anilist_search for the current season to adult: false causes an error and is not processed due to the return from anilist

### Relevant Collection/Playlist Definition

```yml
templates:
  Chart:
    sort_title: +1_<<num>><<collection_name>>
    sync_mode: sync
collections:
  Current Anime Season:
    template: { name: Chart, num: 3 }
    anilist_search:
      season: current
      adult: false
      limit: 100
    sync_mode: sync
```

### Logs

https://gist.github.com/AevumDecessus/ac3637ec3bdecf5abab8ee634857a72e
