### ISSUE TITLE
[Bug]: move_prefix in templates appending multiple prefixes to all collections

### ISSUE THREAD

**Issue by AevumDecessus** [Kometa-Team/Kometa#863]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

Using a template with multiple move_prefix list items (such as A, An, The) or in list format as per [documentation](https://metamanager.wiki/en/latest/metadata/templates.html#:~:text=to%20null.-,move_prefix,-can%20be%20given), all of the prefixes are appended to collection items, regardless if they appeared in the original title or not, or if none at all appeared in the collection_name

* Marvel Cinematic Universe -> Marvel Cinematic Univers, A, An, The
* The Fast and the Furious -> Fast and the Furious, A, An, The

![image](https://user-images.githubusercontent.com/1137023/167697527-23d7c311-8e16-4b3d-aaf8-421828039871.png)
![image](https://user-images.githubusercontent.com/1137023/167697754-a3405be1-12ea-42b4-bfd3-160cafef704d.png)

### Relevant Collection/Playlist Definition

```yml
templates:
  Standard:
    move_prefix: 
      - A
      - An
      - The
    default:
      order: release
    optional:
      - poster_id
      - collection
      - list
      - imdb
      - movie
      - trakt
    sort_title: <<collection_name>>
    sync_mode: sync
    tmdb_collection: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_list: <<list>>
    imdb_list: <<imdb>>
    trakt_list: <<trakt>>
    visible_library: true
    visible_home: false
    visible_shared: false
    collection_mode: hide_items
    collection_order: <<order>>
    url_poster: https://theposterdb.com/api/assets/<<poster_id>>
collections:
  "The Fast and the Furious":
    template: { name: Standard, collection: 9485, poster_id: 164783 }
  "Marvel Cinematic Universe":
    template: { name: Standard, list: 8194961, poster_id: 162417 }
```

### Logs

https://gist.github.com/AevumDecessus/a4612dc29d65c7b3ccb247bd96e00959
