### ISSUE TITLE
[Bug]: Unknown Error: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by imjuzcy** [Kometa-Team/Kometa#870]
### Version Number

1.16.5

### What branch are you on?

develop

### Describe the Bug

Error after parsing

### Relevant Collection/Playlist Definition

```yml
collections:
  Netflix:
    plex_all: true
    filter:
      studio: Netflix
```

### Logs

https://gist.github.com/ImjuzCY/28ce055fc07af2acabe1669c7e16f49b
