### ISSUE TITLE
[Bug]: Found duplicate key "Client ID" with value "none"

### ISSUE THREAD

**Issue by m1e1w1** [Kometa-Team/Kometa#871]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

Setup config.yml with everything working; without critical error until i setup Myaninelist

I supplied my client id, and secret id, saved the config.yml and ran the python script. I get this same problem showing my client ID, so I removed the client ID and secret from config.yml and I continue to get this error.

I was able to get through the rest of the script, with anything failing and letting me know; but this breaks the script.

any idea how to fix it if it does not work?

Thank you.

Attached error / script output as log.

### Logs

https://gist.github.com/m1e1w1/929f2849eabf934564db9d3d484c65cd

**Comment by chazlarson** [comment]
What does the config file look like when you see the problem?

**Comment by m1e1w1** [comment]
https://gist.github.com/m1e1w1/5a48a9ea694d3e48024852236bde4820

**Comment by chazlarson** [comment]
There's a duplicate key on line 130 and line 137.  `client_id` twice at the same level under the same heading.  Lines 134, 135, and 136 should be indented like the trakt example above them, so maybe that's causing parsing issues and PMM's inserting the second one due to those problems.

**Comment by m1e1w1** [comment]
Is that something I would need to fix? or wait for an update on the master branch?

I see where it's missing the MAL part. So i replaced that with the template and get the same error with duplicate key.

**Comment by chazlarson** [comment]
If you indent those three lines correctly and remove the duplicate line, what happens when you run it?

**Comment by m1e1w1** [comment]
I did that fix on the config and put my client ID and Secret information into the MAL. I ran the script and i get the prompt to accept the agreement but i get 400 bad request error. URL redirect is set as http://localhost/
main URL is set to plex-meta-manager URL, which shows up on the accept screen.

**Comment by chazlarson** [comment]
If I start with this in the config:
```
mal:
  client_id:
  client_secret:
  authorization:
    access_token:
    token_type:
    expires_in:
    refresh_token:
```
and run the master version of the script, I see:
```
| Connecting to My Anime List...
| Config Error: mal sub-attribute client_id is blank
| My Anime List Connection Failed
```
as expected.

If I fill in the client_id and scret:
```
mal:
    client_id: 82074...
    client_secret: a9b39...
    authorization:
        access_token:
        token_type:
        expires_in:
        refresh_token:
```
and run the script:
```
| Connecting to My Anime List...                                                                     |
|                                                                                                    |
| Navigate to: https://myanimelist.net/v1/oauth2/authorize?response_type=code&client_id=8207...
|                                                                                                    |
| Login and click the Allow option. You will then be redirected to a localhost                       |
| url that most likely won't load, which is fine. Copy the URL and paste it below                    |
| URL: http://localhost/?code=def50...
| Saving authorization information to /path/to/Plex-Meta-Manager/config/config.yml |
| My Anime List Connection Successful                                                                |
```
and config.yml now looks like this:
```
mal:
    client_id: 82074...
    client_secret: a9b39...
    authorization:
        access_token: eyJ0e...
        token_type: Bearer
        expires_in: 2678400
        refresh_token: def50...
```
I can't reproduce any errors.  Where in the process is the 400 coming up? Also, when is the duplicate `client_id` showing up?
