### ISSUE TITLE
[Bug]: PMM cannot see the metadata file

### ISSUE THREAD

**Issue by SturmB** [Kometa-Team/Kometa#876]
### Version Number

1.16.5

### What branch are you on?

master

### Describe the Bug

I've been following the instructions outlined in the [Docker Walkthrough](https://metamanager.wiki/en/latest/home/guides/docker.html) step by step. I am no stranger to Docker and know my way around my Synology NAS pretty well by now.

I've got the docker volume mapped to the correct directory:

```yml
     volumes:
      - ${DOCKERCONFDIR}/plex-meta-manager:/config
```

And I've created the metadata file there:

```
$ l /volume1/docker/appdata/plex-meta-manager
drwxrwxr-x 1 pmm    media 142 B  Mon May 16 23:05:41 2022  .
drwxrwxr-x 1 docker media 322 B  Sun May  1 22:32:48 2022  ..
drwxr-xr-x 1 root   root    0 B  Sun May  1 22:36:45 2022  custom-cont-init.d
drwxr-xr-x 1 root   root    0 B  Sun May  1 22:36:45 2022  custom-services.d
drwxr-xr-x 1 pmm    media 248 B  Mon May 16 23:08:35 2022  logs
.rw-r--r-- 1 pmm    media 272 KB Mon May 16 23:05:41 2022  config.cache
.rw-rw-r-- 1 pmm    media 3.3 KB Mon May 16 23:08:36 2022  config.yml
.rw-rw-r-- 1 pmm    media 680 B  Mon May 16 22:58:50 2022  Movies.yml
$
```

Which is referenced in the config:

```yml
libraries:                                      # This is called out once within the config.yml file
  Movies:                                       # Each library must match the Plex library name
    metadata_path:
      - file: config/Movies.yml
      - folder: config/Movies/
```

However, upon running, PMM just can't "see" it:

```
pmm               | |===================================== Scanning Metadata Files ======================================|
pmm               | |                                                                                                    |
pmm               | | Loading Metadata File: config/Movies.yml                                                           |
pmm               | |                                                                                                    |
pmm               | | Traceback (most recent call last):                                                                 |
pmm               | |   File "/app/pmm/modules/meta.py", line 94, in load_file                                           |
pmm               | |     raise Failed(f"File Error: File does not exist {os.path.abspath(file_path)}")                  |
pmm               | | modules.util.Failed: File Error: File does not exist /run/s6/services/plex-meta-manager/config/Movies.yml |
pmm               | |                                                                                                    |
pmm               | | YAML Error: File Error: File does not exist /run/s6/services/plex-meta-manager/config/Movies.yml   |
pmm               | |                                                                                                    |
```

What am I doing wrong?

### Relevant Collection/Playlist Definition

```yml
templates:
  Actor:
    actor: tmdb
    tmdb_person: <<person>>
    tmdb_actor_details: <<person>>
    sort_title: +_<<collection_name>>
    sync_mode: sync
    collection_order: release
    collection_mode: hide
collections:
  Bill Murray:
    template: {name:  Actor, person: 1532}
  Best of the 1980s:
    tmdb_discover:
      primary_release_date.gte: 01/01/1980
      primary_release_date.lte: 12/31/1989
      with_original_language: en
      sort_by: popularity.desc
      limit: 100
    summary: A collection of the Top Content of the 1980s
  Vulture’s 101 Best Movie Endings:
    letterboxd_list: https://letterboxd.com/brianformo/list/vultures-101-best-movie-endings/
```

### Logs

https://gist.github.com/SturmB/d72866e51203e7e9e5907ef1b4479aa0
