### ISSUE TITLE
More flexibility with plex_search

### ISSUE THREAD

**Issue by Alaksin** [Kometa-Team/Kometa#88]
I have started to setup collections for my concerts and video documentaries and since I can't find proper matches for everything it is causing me some problems. I would like to be able to use plex_search to search for a string in a title, and also to have more control of the AND / OR in the search. 

For my concert library, I use plex_search with the band members as Actors to build collections. This works really well with concerts, as long as they have a match. If they don't then I'm trouble. I tried to set the band name as Writer for the concert, and add that to the search, but then it will search for Actors AND Writer, which will not work. If I could search for Actor OR Writer that would work. Another solution would be to search on the band name in the movie/show title. But I would still need the OR functionality in the search to accomplish my goal.

```
templates:

  Bands:
    sync_mode: sync
    collection_order: release
    name_mapping: /config/assets/- Bands/<<collection_name>>
    plex_search_or:
      actor: <<members>>
      writer: <<collection_name>>
      title: <<collection_name>>

collections:

  Alice in Chains:
    template:
      name: Bands
      members: Layne Staley, Jerry Cantrell
        
  Black Sabbath:
    template:
      name: Bands
      members: Tony Iommi, Ozzy Osbourne

  The Beatles:
    template:
      name: Bands
      members: Paul McCartney, John Lennon, Ringo Starr, George Harrison
```

**Comment by meisnate12** [comment]
you can just do the ors like this and I can see about adding in a title search option.

also name mapping needs only be the name of the folder to look into inside your asset dir not the whole path to it

```yaml
templates:
  Bands:
    sync_mode: sync
    collection_order: release
    name_mapping: <<collection_name>>
    actor: <<members>>
    writer: <<collection_name>>
    title: <<collection_name>>

collections:

  Alice in Chains:
    template:
      name: Bands
      members: Layne Staley, Jerry Cantrell
        
  Black Sabbath:
    template:
      name: Bands
      members: Tony Iommi, Ozzy Osbourne

  The Beatles:
    template:
      name: Bands
      members: Paul McCartney, John Lennon, Ringo Starr, George Harrison
```
