### ISSUE TITLE
[Bug]: 'Episode' object has no attribute '_autoReload'

### ISSUE THREAD

**Issue by KnifeFed** [Kometa-Team/Kometa#895]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

On one of my libraries, no matter which default overlay I'm trying to add, I end up with the error seen in the included log. It works fine on other libraries.

### Relevant Collection/Overlay/Playlist Definition

```yml
overlay_path:
  - git: PMM/overlays/audio_codec
```

### Logs

https://gist.github.com/KnifeFed/af48d7e0382cf34aef64827c1110d37e

**Comment by KnifeFed** [comment]
Turns out it was because I had `Seasons` set to `Hide` in the library advanced settings. Setting it to `Hide for single-season series` works and that serves the same purpose as `Hide` for me.

**Comment by rcdailey** [comment]
Mine is set to hide for single season and I still get this error on shows that have only 1 season.

**Comment by KnifeFed** [comment]
@rcdailey Does it work if you set it to `Show`?

**Comment by rcdailey** [comment]
Sadly no :(

**Comment by rcdailey** [comment]
My YAML:

```yml
TV Shows:
  overlay_path:
  - remove_overlays: false
  - git: PMM/overlays/resolution
    template_variables:
      use_1080p: false
      use_720p: false
      use_480p: false
  - git: PMM/overlays/audio_codec
    template_variables:
      Opus: false
      Dolby-Digital: false
      DTS: false
      DTS-ES: false
      Dolby-Digital-Plus: false
      DTS-X: true
      DTS-HD: true
      Dolby-TrueHD: true
      Dolby-Atmos: true
```
