### ISSUE TITLE
[Bug]: Issue generating overlays for specific collections

### ISSUE THREAD

**Issue by ohmybahgosh** [Kometa-Team/Kometa#908]
### Version Number

1.17.0

### What branch are you on?

develop

### Describe the Bug

I could be really overlooking this, but what would be an example filter to apply overlays to specific collections...

For example, I have two collections that are built via these configs:

```yaml
  Netflix Original Series:
    smart_label: episode_added.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_1Netflix
    tmdb_network: 213
    summary: All Netflix Original Series/Shows
    url_poster: https://i.imgur.com/7kiE1MU.png
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    sonarr_add: false
    sonarr_search: false
    sonarr_monitor: none

  NEW Netflix Original Series:
    smart_label: release.desc
    sync_mode: sync
    sort_title: +++++++++++++++++++++_2Netflix
    imdb_list:
      - https://www.imdb.com/search/title/?title_type=tv_series,tv_special,tv_miniseries&countries=us&languages=en&genres=!animation&sort=release_date,desc&count=250&companies=co0144901&release_date=2021-01-01,2100-01-01
      - https://www.imdb.com/search/title/?title_type=tv_series,tv_special,tv_miniseries&countries=us&languages=en&genres=!animation&sort=release_date,desc&count=250&release_date=2021-01-01,2100-01-01&companies=co0650527
    summary: All NEW Netflix Original Series/Shows
    url_poster: https://i.imgur.com/7kiE1MU.png
    url_background: https://img5.goodfon.com/original/1920x1080/1/61/fon-netflix-logo-raduga-tsvet-fon-background-skachat-oboi-sk.jpg
    sonarr_add: true
    sonarr_search: true
    sonarr_monitor: all
```

How would I format an overlay config file to place the Netflix overlay (code below is trimmed from PMM/overlays) so that it applies only to the collections above...as using `filepath.regex` won't find netflix in the files (at least the way I have my media formatted):

```yaml
templates:
  Streaming:
    optional:
      - overlay_level
      - use_<<slug>>
    default:
      overlay: <<overlay_name>>
      horizontal_offset: 15
      horizontal_align: left
      vertical_offset: 135
      vertical_align: top
    allowed_library_types: <<use_<<slug>>>>
    collection_level: <<overlay_level>>
    overlay:
      name: <<overlay_name>>
      git: PMM/overlays/images/<<overlay>>
      group: streaming
      weight: <<weight>>
      horizontal_offset: <<horizontal_offset>>
      horizontal_align: <<horizontal_align>>
      vertical_offset: <<vertical_offset>>
      vertical_align: <<vertical_align>>
    plex_all: true
    filters:
      .regex: <<regex>>

overlays:

  Netflix:
    template:
      - name: Streaming
        weight: 200
        slug: netflix
        regex: '(?i)\b(nf|netflix)\b'
```

### Logs

https://gist.github.com/ohmybahgosh/b170c577fd9fc32a2dde3863cbadf10e

**Comment by ohmybahgosh** [comment]
I found a way to do this, just wondering if this is the recommend way:

```yaml
overlays:

############################
#    STREAMING SERVICES    #
############################
  Netflix:
    overlay:
      name: Netflix Series
    plex_search:
      any:
        label.regex: '(?i)\b(nf|netflix)\b'

```

**Comment by meisnate12** [comment]
thats one way the other would be to just call the same lists again 
```yaml
overlays:

############################
#    STREAMING SERVICES    #
############################
  Netflix:
    overlay:
      name: Netflix Series
    tmdb_network: 213
    imdb_list:
      - https://www.imdb.com/search/title/?title_type=tv_series,tv_special,tv_miniseries&countries=us&languages=en&genres=!animation&sort=release_date,desc&count=250&companies=co0144901&release_date=2021-01-01,2100-01-01
      - https://www.imdb.com/search/title/?title_type=tv_series,tv_special,tv_miniseries&countries=us&languages=en&genres=!animation&sort=release_date,desc&count=250&release_date=2021-01-01,2100-01-01&companies=co0650527
    
```
