### ISSUE TITLE
[Bug]: Playlists are not able to be deleted.

### ISSUE THREAD

**Issue by cybersteel8** [Kometa-Team/Kometa#910]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

I am trying to delete two playlists for all accounts on my Plex server, but it doesn't seem possible, because this error is appearing.

```
Marvel Cinematic Universe                |     0 |     0 |     0 |  0:00:01 | Unknown Error|
  'delete_not_scheduled'
Star Wars Clone Wars Chronological Order |     0 |     0 |     0 |  0:00:00 | Unknown Error|
  'delete_not_scheduled'
```

### Relevant Collection/Overlay/Playlist Definition

```yml
playlists:
  Marvel Cinematic Universe:
    sync_to_users: all
    sync_mode: sync
    libraries: Movies, TV Shows
    trakt_list: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe?sort=rank,asc
    summary: Marvel Cinematic Universe In Order
    delete_playlist: true
  Star Wars Clone Wars Chronological Order:
    sync_to_users: all
    sync_mode: sync
    libraries: Movies, TV Shows
    trakt_list: https://trakt.tv/users/tomfin46/lists/star-wars-the-clone-wars-chronological-episode-order
    delete_playlist: true
```

### Logs

https://gist.github.com/cybersteel8/b2c3cc9e6cdd4235475b62addc406741
