### ISSUE TITLE
[Bug]: AttributeError: 'Episode' object has no attribute '_autoReload'

### ISSUE THREAD

**Issue by TechJedi51** [Kometa-Team/Kometa#918]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

Getting an unknown error with the following metadata filter:

| Star Trek Collection                   |     0 |     0 |     0 |  0:00:26 | Unknown Error          
| 'Episode' object has no attribute '_autoReload'                                                    

### Relevant Collection/Overlay/Playlist Definition

```yml
## Star Trek Collection
  Star Trek Collection:    
    sort_title: Star Trek
    file_poster: /config/assets/Collections/Star Trek TV/poster.png
    file_background: /config/assets/Collections/Star Trek TV/background.jpg
    collection_order: release
    plex_all: true
    filters:
      filepath:
        - Star Trek

```

### Logs

https://gist.github.com/TechJedi51/bf5d4f0013a0dc944c1ff89a75897f04
