### ISSUE TITLE
[Bug]: PMM Not updating Season Posters

### ISSUE THREAD

**Issue by Drazzilb08** [Kometa-Team/Kometa#924]
### Version Number

1.17.0-develop9 

### What branch are you on?

develop

### Describe the Bug

PMM will not update season posters:

Posters are named:
```
root@Tower:/mnt/user/appdata/plex-meta-manager/pmm-series# tree assets/
assets/
├── 2 Broke Girls (2011).jpg
├── 2 Broke Girls (2011)_Season01.jpg
├── 2 Broke Girls (2011)_Season02.jpg
├── 2 Broke Girls (2011)_Season03.jpg
├── 2 Broke Girls (2011)_Season04.jpg
├── 2 Broke Girls (2011)_Season05.jpg
├── 2 Broke Girls (2011)_Season06.jpg
```
Pathing to media is `/data/media/series/2 Broke Girls (2011)`

Config file:
```yml
    operations:
      delete_unmanaged_collections: true
      assets_for_all: true
    settings:
      asset_directory: config/assets/
```
Posters are placed in the assets directory
The Series poster will update, but not the Seasons

### Logs

https://gist.github.com/Drazzilb08/53e6e15ee6a616fc37413b90265cb636
