### ISSUE TITLE
[Bug]: Space added to collection_sort when using move_prefix

### ISSUE THREAD

**Issue by justinxfisher** [Kometa-Team/Kometa#928]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

I have two templates, one that moves prefixes and one that doesn't, other than that they're the same.

In collections made by the template that move prefixes, there is a space inserted between at the beginning of the formatted `<<collection_sort>>` variable. What I get as the sort name is `++008_ Avengers, The`, `++008_ Bourne Collection, The`, `++008_ Dark Knight, The`, etc. This pushes these before the collections which don't have a prefix moved.

The log is for the Avengers collection, but it's the same for all of them, just a space inserted when the formatted name is inserted.

### Relevant Collection/Overlay/Playlist Definition

```yml
Groupings:
    optional:
      - collection
      - movie
      - posterdb
      - radarr
    tmdb_collection_details: <<collection>>
    tmdb_summary: <<collection>>
    tmdb_poster: <<collection>>
    tmdb_background: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    sort_title: '++008_<<collection_name>>'
    url_poster: https://theposterdb.com/api/assets/<<posterdb>>
    radarr_add_missing: <<radarr>>

  Groupings_Prefixes:
    optional:
      - collection
      - movie
      - posterdb
      - radarr
    tmdb_collection_details: <<collection>>
    tmdb_summary: <<collection>>
    tmdb_poster: <<collection>>
    tmdb_background: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    sort_title: '++008_<<collection_sort>>'
    url_poster: https://theposterdb.com/api/assets/<<posterdb>>
    radarr_add_missing: <<radarr>>
    move_prefix: 'A, An, The'
```

### Logs

https://gist.github.com/justinxfisher/12c1c64708bbdd10c78c69962e03c72a
