### ISSUE TITLE
[Bug]: trakt_chart builder ignores "year" attribute

### ISSUE THREAD

**Issue by mattyteds** [Kometa-Team/Kometa#937]
### Version Number

1.17.0-develop59

### What branch are you on?

nightly

### Describe the Bug

When using the `trakt_chart` builder no matter what chart I use the `year` attribute is completely ignored when fetching results, though it is seen being used by the builder and in the request. I tried adding `time_period: all` to the compatible charts but that made no change. I will provide collection logs for every chart option for both TV and Movie libraries.

Is this dependent on having Trakt VIP? I don't have that.

### Relevant Collection/Overlay/Playlist Definition

```yml
# From TV.yml
collections:
  Test Trakt 80's Trending:
    test: true
    summary: Should be showing the top 30 shows from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: trending
      limit: 30
      year: 1980
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Popular:
    test: true
    summary: Should be showing the top 30 shows from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: popular
      limit: 30
      year: 1980
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Recommendations:
    test: true
    summary: Should be showing the top 30 shows from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: recommended
      limit: 30
      year: 1980
      time_period: all
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Watched:
    test: true
    summary: Should be showing the top 30 shows from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: watched
      limit: 30
      year: 1980
      time_period: all
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Collected:
    test: true
    summary: Should be showing the top 30 shows from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: collected
      limit: 30
      year: 1980
      time_period: all
    collection_order: custom
    sync_mode: sync

# From Movies.yml
collections:
  Test Trakt 80's Trending:
    test: true
    summary: Should be showing the top 30 movies from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: trending
      limit: 30
      year: 1980
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Popular:
    test: true
    summary: Should be showing the top 30 movies from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: popular
      limit: 30
      year: 1980
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Recommendations:
    test: true
    summary: Should be showing the top 30 movies from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: recommended
      limit: 30
      year: 1980
      time_period: all
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Watched:
    test: true
    summary: Should be showing the top 30 movies from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: watched
      limit: 30
      year: 1980
      time_period: all
    collection_order: custom
    sync_mode: sync
  Test Trakt 80's Collected:
    test: true
    summary: Should be showing the top 30 movies from the 1980's.
    sort_title: ++++++Test
    label: Private
    show_missing: false
    minimum_items: 1
    delete_below_minimum: false
    trakt_chart:
      chart: collected
      limit: 30
      year: 1980
      time_period: all
    collection_order: custom
    sync_mode: sync
```

### Logs

https://gist.github.com/mattyteds/ea9bdab485d1757c0a28cba8b3cb552b
