### ISSUE TITLE
remove_overlays not working

### ISSUE THREAD

**Issue by benfishbus** [Kometa-Team/Kometa#940]
### Version Number

1.17.0

### What branch are you on?

master

### Describe the Bug

Using the PMM Default overlays, enabled a whole bunch of overlays and decided there are some I don't want, like audio codec. Just removing them from my config didn't seem to have any effect, so I set `remove_overlays: true` and re-ran, but audio codec, etc. are still in overlays.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:
  movies:
    overlay_path:
    - remove_overlays: true
    - repo: PMM/overlays/audio_language
    - repo: PMM/overlays/imdb_top_250
    - repo: PMM/overlays/ratings
    - repo: PMM/overlays/special_release
```

### Logs

https://gist.github.com/benfishbus/05829ea3804bfd3a15255d720269adea
