### ISSUE TITLE
[Bug]: "Mdblist Error: Invalid Response {'error': 'empty'}" when limiting mdblist builder

### ISSUE THREAD

**Issue by mattyteds** [Kometa-Team/Kometa#947]
### Version Number

1.17.1-develop6

### What branch are you on?

nightly

### Describe the Bug

When limiting my results from a mdblist ([as described here](https://metamanager.wiki/en/latest/metadata/builders/mdblist.html#mdblist-list)) the builder fails indicating the list is empty.

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
  2020's Top 100 Mainstream:
    test: true
    summary: Top released mainstream movies from 2000 to 2029. Ordered by release date.
    sort_title: ++++2020's Top 100 Mainstream
    mdblist_list:
      url: https://mdblist.com/lists/tedford/2020s-top-mainstream/
      limit: 100 # commenting this out will allow it to build
    collection_order: custom
    visible_library: true
    visible_home: false
    visible_shared: false
    sync_mode: sync
```

### Logs

https://gist.github.com/mattyteds/3b90e0ea2c2832420287a76f1926ec73
