### ISSUE TITLE
[Bug]: Movies Library: 504 gateway_timeout

### ISSUE THREAD

**Issue by BigManDave** [Kometa-Team/Kometa#953]
### Version Number

1.17.1

### What branch are you on?

master

### Describe the Bug

Overlays on Movies no longer process. Other metadata seems to be fine.
This seems to have started happening since I changed some Posters for my movies in Plex, although that could be a coincidence.

I've tried refreshing metadata, emptying trash, clearing bundles and deleting/re adding the library in Plex to no success. I've also tried clearing the PMM file caches that I could find.

No issues with TV Shows library. 

### Relevant Collection/Overlay/Playlist Definition

```yml
Movies:
    metadata_path:
    - git: PMM/chart/imdb
      schedule: daily
      template_variables:
        use_lowest: false
    - git: PMM/chart/tmdb
      schedule: daily
      template_variables:
        use_airing: false
    overlay_path:
    - git: PMM/overlays/resolution
      schedule: daily
    - git: PMM/overlays/audio_codec
      schedule: daily
    operations:
      split_duplicates: true
      assets_for_all: false
      mass_trakt_rating_update: true
      mass_critic_rating_update: tmdb
      mass_audience_rating_update: tmdb
      mass_genre_update: tmdb
```

### Logs

https://gist.github.com/BigManDave/f59d1f63389275e27eaaa4cad124d7ab
