### ISSUE TITLE
[Bug]: 0 AniDB IDs Found

### ISSUE THREAD

**Issue by tekwarfare** [Kometa-Team/Kometa#954]
### Version Number

1.17.1

### What branch are you on?

master

### Describe the Bug

I am receiving the message:
> 0 AniDB IDs Found: []

I have a dedicated TV Shows library called Anime
The Scanner and Agent are both _Plex TV Series_ 
All metadata has been recently refreshed

### Relevant Collection/Overlay/Playlist Definition

```yml
#####################################
#     Custom Collection Template    #
#####################################
collections:
 Trending in Anime:
    anidb_popular: 30
    collection_order: custom
    sync_mode: sync
```

### Logs

https://gist.github.com/tekwarfare/334fd7159fe4d094014c7a01858ba8a5
