### ISSUE TITLE
[Bug]: trakt_userlist ignores sort_by

### ISSUE THREAD

**Issue by mattyteds** [Kometa-Team/Kometa#967]
### Version Number

1.17.1-develop32 

### What branch are you on?

nightly

### Describe the Bug

No matter what you set sort_by to for trakt_userlist it will always sort it by rank. The logs show that the builder is using "none" for sort_by regardless of what you put.

### Relevant Collection/Overlay/Playlist Definition

```yml
collections:
  Trakt Watchlist:
    summary: My Trakt watchlist.
    sync_mode: sync
    collection_order: custom
    trakt_userlist: 
      userlist: watchlist
      user: me
      sort_by: released
```

### Logs

https://gist.github.com/mattyteds/2e10b5e9d6c41d7b94378117afe38cad
