### ISSUE TITLE
[Bug]: AttributeError: 'Album' object has no attribute 'locations'   

### ISSUE THREAD

**Issue by jaamarcelis** [Kometa-Team/Kometa#974]
### Version Number

1.17.1

### What branch are you on?

master

### Describe the Bug

When updating an album (any property), an error is raised and the flow is terminated. 
The properties itself are updated successfully, but any other albums / artists in de configfile are not processed any longer.

In this example I update the record_label to 'Bardo' for 9 albums of 2 artists.

Error:

Artist: Annemarie Barendswaard-Van Boven Details Update Not Needed                                 |
| Asset Warning: Unable to find asset folder: 'Annemarie Barendswaard-Van Boven'                     |
|                                                                                                    |
| Updating album Bardo! of Annemarie Barendswaard-Van Boven...                                       |
| Detail: record_label updated to Bardo                                                              |
| Album: Bardo! Details Update Successful                                                            |
| Traceback (most recent call last):                                                                 |
|   File "/app/pmm/plex_meta_manager.py", line 479, in run_libraries                                 |
|     metadata.update_metadata()                                                                     |
|   File "/app/pmm/modules/meta.py", line 789, in update_metadata                                    |
|     self.update_metadata_item(i, title, mapping_name, meta, methods)                               |
|   File "/app/pmm/modules/meta.py", line 1078, in update_metadata_item                              |
|     self.library.item_images(album, album_dict, album_methods, asset_location=asset_location,      |
|   File "/app/pmm/modules/plex.py", line 927, in item_images                                        |
|     asset_poster, asset_background, item_dir, folder_name = self.find_item_assets(item, item_asset_directory=asset_location) |
|   File "/app/pmm/modules/plex.py", line 1032, in find_item_assets                                  |
|     if not starting.locations:                                                                     |
|   File "/usr/lib/python3.9/site-packages/plexapi/base.py", line 468, in __getattribute__           |
|     value = super(PlexPartialObject, self).__getattribute__(attr)                                  |
| AttributeError: 'Album' object has no attribute 'locations'                                        |
|                                                                                                    |
| 'Album' object has no attribute 'locations'                    

### Relevant Collection/Overlay/Playlist Definition

```yml
metadata:
  "Annemarie Barendswaard-Van Boven":
    albums:
      "Bardo!":
        record_label: "Bardo"
      "Bardo zoekt verder":
        record_label: "Bardo"
      "Bardo wordt beroemd":
        record_label: "Bardo"
      "Bardo en de inbreker":
        record_label: "Bardo"
      "Bardo wordt ontvoerd":
        record_label: "Bardo"
      "Bardo vindt een schat":
        record_label: "Bardo"
      "Bardo redt Boris":
        record_label: "Bardo"
      "Bardo op vakantie":
        record_label: "Bardo"
  "Martha Heutink":
    albums:
      "Bardo volgt het spoor":
        record_label: "Bardo"
```

### Logs

https://gist.github.com/jaamarcelis/86be8d30eef424d4215995cb04b9ca6f
