### ISSUE TITLE
[Bug]: 'str' object has no attribute 'startwith'

### ISSUE THREAD

**Issue by csandman** [Kometa-Team/Kometa#979]
### Version Number

1.17.2

### What branch are you on?

master

### Describe the Bug

I'm using the Docker container on Unraid and when trying to make a dynamic collection for my Audiobook library using the mood field, I'm running into the following error:

```
| Traceback (most recent call last):                                                                 |
|   File "/modules/config.py", line 846, in __init__                                                 |
|     library.scan_files(self.operations_only, self.overlays_only, self.collection_only)             |
|   File "/modules/library.py", line 134, in scan_files                                              |
|     meta_obj = MetadataFile(self.config, self, file_type, metadata_file, temp_vars, asset_directory) |
|   File "/modules/meta.py", line 495, in __init__                                                   |
|     final_var = auto_type if auto_type.startwith("album") else f"artist_{auto_type}"               |
| AttributeError: 'str' object has no attribute 'startwith'                                          |
|                                                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "//plex_meta_manager.py", line 218, in start                                                |
|     config = ConfigFile(default_dir, attrs)                                                        |
|   File "/modules/config.py", line 846, in __init__                                                 |
|     library.scan_files(self.operations_only, self.overlays_only, self.collection_only)             |
|   File "/modules/library.py", line 134, in scan_files                                              |
|     meta_obj = MetadataFile(self.config, self, file_type, metadata_file, temp_vars, asset_directory) |
|   File "/modules/meta.py", line 495, in __init__                                                   |
|     final_var = auto_type if auto_type.startwith("album") else f"artist_{auto_type}"               |
| AttributeError: 'str' object has no attribute 'startwith'                                          |
|                                                                                                    |
| 'str' object has no attribute 'startwith'                                                          |
```

As far as I know, this might just be a typo? (not a python expert) In the `meta.py` module file I see three instances of `startwith` which I think should be `startswith`?

You can see the lines here: https://github.com/meisnate12/Plex-Meta-Manager/blob/master/modules/meta.py#L499

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  mood collection:
    smart_filter:
      sort_by: title.asc
      type: albums
      all:
        album_mood: <<value>>

dynamic_collections:
  Series:
    type: mood
    # remove_prefix: "Series: "
    title_format: <<key_name>>
    template: mood collection
```

Also not entirely sure I formatted this right...

### Logs

Can't find the log file, but the above is the section of error I'm seeing in the terminal

**Comment by csandman** [comment]
I ended up trying a non-Docker version to see if replacing the functions seemed to help and they seem to, but I still cannot for the life of me get this auto collection to work.

All I want to do is create collections of albums for every `mood` tag that each album is tagged with (preferably sorted by the album's sort title, not sure if `title.asc` uses that).

Even using [the default `mood` example](https://metamanager.wiki/en/latest/metadata/dynamic.html#mood) from the docs is throwing this error:

```
|================================ Building Moods Dynamic Collections ================================|
|                                                                                                    |
| Mapping Name: Moods                                                                                |
| Type: mood                                                                                         |
| Data: None                                                                                         |
| Exclude: []                                                                                        |
| Addons: {}                                                                                         |
| Template: ['mood collection']                                                                      |
| Other Template: ['mood collection']                                                                |
| Template Variables: {}                                                                             |
| Remove Prefix: []                                                                                  |
| Remove Suffix: []                                                                                  |
| Title Format: <<key_name>>                                                                         |
| Key Name Override: {}                                                                              |
| Title Override: {}                                                                                 |
| Test: False                                                                                        |
| Sync: {}                                                                                           |
| Include: []                                                                                        |
| Other Name: None                                                                                   |
| Keys (Title)                                                                                       |
| YAML Error: metadata, collections, or dynamic_collections attribute is required                    |
|                                                                                                    |
|====================================================================================================|
```

I'm not sure what it means by the YAML error at the bottom as I have a `dynamic_collections` item in the metadata file:

```yml
# config/audiobooks.yml
templates:
  mood collection:
    smart_filter:
      limit: 100
      sort_by: plays.desc
      type: tracks
      all:
        track_mood: <<value>>

dynamic_collections:
  Moods:         # mapping name does not matter just needs to be unique
    type: mood
    title_format: <<key_name>>
    template: mood collection
    sync: true
```

And here's a redacted version of my `config.yml`:

```yml
libraries:
  Audnexus 2:
    metadata_path:
    - file: config/audiobooks.yml
plex:
  url: http://192.168.0.2:32400
  token: XXXXXXXX
  timeout: 60
  clean_bundles: false
  empty_trash: false
  optimize: false
tmdb:
  apikey: XXXXXXXX
  language: en
  cache_expiration: 60
  region:
settings:
# All `settings` left as default
```

Sorry if this isn't the right place for this kind of question, if you'd like me to ask this part somewhere else lmk.
