### ISSUE TITLE
[Bug]: delete_unmanaged_collections operation not working

### ISSUE THREAD

**Issue by peterkogo** [Kometa-Team/Kometa#992]
### Version Number

1.17.2

### What branch are you on?

master

### Describe the Bug

Setting `delete_unmanaged_collections: true` does not seem to delete any collection. 

Steps to reproduce:
1. Create new .yml in metadata folder. (See config below)
2. Add 2 collections  (I am using the Letterboxd List Builder)
3. Run Plex Meta Manager
4. Delete one of the collections from .yml
5. Run Plex Meta Manager

If I understand `delete_unmanaged_collections` correctly it should remove any collections that do not appear in the configuration files anymore, right?

The library operations output shows the configured option correctly as `true` but no unmanaged collections are found nor deleted.

### Relevant Collection/Overlay/Playlist Definition

```yml
libraries:                                                             
  Library:                                      
    metadata_path:
    - folder: ../Plex-Meta-Configs/Library/active
    operations:
      delete_unmanaged_collections: true
settings:
  cache: true
  cache_expiration: 60
  asset_directory: config/assets
  asset_folders: true
  asset_depth: 0
  create_asset_folders: false
  prioritize_assets: false
  dimensional_asset_rename: false
  download_url_assets: false
  show_missing_season_assets: false
  show_missing_episode_assets: false
  show_asset_not_needed: true
  sync_mode: sync
  minimum_items: 1
  default_collection_order:
  delete_below_minimum: true
  delete_not_scheduled: false
  run_again_delay: 2
  missing_only_released: false
  only_filter_missing: false
  show_unmanaged: true
  show_filtered: false
  show_options: false
  show_missing: true
  show_missing_assets: true
  save_report: false
  tvdb_language: eng
  ignore_ids:
  ignore_imdb_ids:
  item_refresh_delay: 0
  playlist_sync_to_user: all
  playlist_report: false
  verify_ssl: true
  custom_repo:
  check_nightly: false
```

### Logs

No logs
