### ISSUE TITLE
[Bug]: Can't create smart collection with unplayed items for current user if admin already saw all items

### ISSUE THREAD

**Issue by hbooo** [Kometa-Team/Kometa#997]
### Version Number

1.17.2-develop21

### What branch are you on?

develop

### Describe the Bug

I try to create a Smart Collection of Wizarding World with only unplayed items for current user. But generation of the collection failed as I already saw all movies.

### Relevant Collection/Overlay/Playlist Definition

```yml
templates:
  Chart:
    collection_filtering: user
    collection_mode: show_items
    sort_title: +00_<<num>><<collection_name>>
    test: true
    sync_mode: sync
    url_poster: https://raw.githubusercontent.com/meisnate12/Plex-Meta-Manager-Images/master/franchise/<<poster>>.jpg
    smart_label:
      sort_by: release.desc
      all:
        label: <<smart_label>>
        unplayed: True
collections:
######################################################
#                Franchise Collections                   #
######################################################
  Wizarding World:
    template: { name: Chart, num: 6, poster: Wizarding World }
    visible_home: true
    visible_shared: true
    trakt_list:
      - https://trakt.tv/users/strangerer/lists/harry-potter
```

### Logs

https://gist.github.com/hbooo/f1d5ce6fe95af2d8aa9f10438ca7b842
